### ISSUE TITLE
[riverpod_lint] analyzer just get crushed repeatedly 

### ISSUE THREAD

**Issue by devnoaman** [rrousselGit/riverpod#2197] opened 2023-02-18 07:03 UTC
**Describe the bug**
i had tried riverpod_lint in my project, after globaly activate it the flutter analyzer just get crashing ,
i have removed the package and upgraded flutter and the same problem appear 

```



Dart Code extension: 3.58.0
Flutter extension: 3.58.0 (activated)

App: Visual Studio Code
Version: 1.75.1
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/noamanmonther/flutterDev/flutter/bin/cache/dart-sdk
    Ver: 3.0.0-245.0.dev
Flutter SDK:
    Loc: /Users/noamanmonther/flutterDev/flutter
    Ver: 3.8.0-13.0.pre.92

HTTP_PROXY: undefined
NO_PROXY: undefined
[9:56:46 AM] [FlutterDaemon] [Info] Spawning /Users/noamanmonther/flutterDev/flutter/bin/flutter with args ["daemon"]
[9:56:46 AM] [FlutterDaemon] [Info] ..  in /Users/noamanmonther/flutterDev/flutter
[9:56:46 AM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[9:56:46 AM] [FlutterDaemon] [Info]     PID: 53801
[9:56:46 AM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"emulator.getEmulators"}]
[9:56:46 AM] [Analyzer] [Info] Spawning /Users/noamanmonther/flutterDev/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.58.0"]
[9:56:46 AM] [Analyzer] [Info]     PID: 55236
[9:56:46 AM] [General] [Info] Returning cached results for project search
[9:56:46 AM] [General] [Info] Activating Flutter extension for Flutter project...
[9:56:46 AM] [General] [Info] Extension:Startup timing: 18ms
[9:56:46 AM] [DevTools] [Info] Spawning /Users/noamanmonther/flutterDev/flutter/bin/cache/dart-sdk/bin/dart with args ["devtools","--machine","--try-ports","10","--allow-embedding","--port","9100"]
[9:56:46 AM] [DevTools] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[9:56:46 AM] [DevTools] [Info]     PID: 53801
[9:56:46 AM] [General] [Info] Version last used for Pub is 3.0.0-245.0.dev (3.0.0), current is 3.0.0-245.0.dev (3.0.0)
[9:56:46 AM] [General] [Info] Found 0 folders requiring "pub get" or "pub upgrade":
[9:56:46 AM] [General] [Info] Done!
[9:56:46 AM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.58.0
Flutter extension: 3.58.0 (activated)

App: Visual Studio Code
Version: 1.75.1
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/noamanmonther/flutterDev/flutter/bin/cache/dart-sdk
    Ver: 3.0.0-245.0.dev
Flutter SDK:
    Loc: /Users/noamanmonther/flutterDev/flutter
    Ver: 3.8.0-13.0.pre.92

HTTP_PROXY: undefined
NO_PROXY: undefined
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 6467
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":53801,"clientInfo":{"name":"Visual Studio Code","version":"1.75.1"},"locale":"en","rootPath":"/Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord","rootUri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","n…
[9:56:46 AM] [Analyzer] [Info] <== Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":7,"jsonrpc":"2.0","result":null}
[9:56:46 AM] [FlutterDaemon] [Info] Process /Users/noamanmonther/flutterDev/flutter/bin/flutter terminated! 0, null
[9:56:46 AM] [DevTools] [Info] Process /Users/noamanmonther/flutterDev/flutter/bin/cache/dart-sdk/bin/dart terminated! null, SIGTERM
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 67
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"exit","clientRequestTime":1676703406232}
[9:56:46 AM] [General] [Info] Loaded 20000 from vscode-userdata:/Users/noamanmonther/Library/Application%20Support/Code/User/globalStorage/dart-code.dart-code/package_cache.json
[9:56:46 AM] [DevTools] [Info] <== {"event":"server.started","method":"server.started","params":{"host":"127.0.0.1","port":9100,"pid":55238,"protocolVersion":"1.1.0"}}
[9:56:46 AM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":55235}}]
[9:56:46 AM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"device.enable"}]
[9:56:46 AM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[9:56:46 AM] [FlutterDaemon] [Info] <== [{"id":"2"}]
[9:56:46 AM] [FlutterDaemon] [Info] <== [{"id":"1","result":[{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"},{"id":"Pixel_2","name":"Pixel 2","category":"mobile","platformType":"android"},{"id":"Pixel_3a_API_31","name":"Pixel 3a API 31","category":"mobile","platformType":"android"},{"id":"flutter_emulator","name":"flutter emulator","category":"mobile","platformType":"android"}]}]
[9:56:46 AM] [Analyzer] [Info] <== Content-Length: 432
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:46 AM] [Analyzer] [Info] <== {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["edit.sortMembers","edit.organizeImports","edit.fixAll","edit.sendWorkspaceEdit","refactor.perform","move_top_level_to_file"],"workDoneProgress":true},"workspace":{"workspaceFolders":{"changeNotifications":true,"supported":true}},"workspaceSymbolProvider":true},"serverInfo":{"name":"Dart SDK LSP Analysis Server","version":"3.0.0-245.0.dev"}}}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 86
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"initialized","params":{},"clientRequestTime":1676703406709}
[9:56:46 AM] [General] [Info] Analyzer:Startup timing: 535ms
[9:56:46 AM] [Analyzer] [Info] <== Content-Length: 205
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:46 AM] [Analyzer] [Info] <== {"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord","section":"dart"},{"section":"dart"}]}}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 6907
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"result":[{"additionalAnalyzerFileExtensions":[],"analysisExcludedFolders":[],"analyzeAngularTemplates":true,"analyzerAdditionalArgs":[],"analyzerDiagnosticsPort":null,"analyzerPath":null,"analyzerSshHost":null,"analyzerVmServicePort":null,"notifyAnalyzerErrors":true,"onlyAnalyzeProjectsWithOpenFiles":false,"showTodos":true,"useLegacyAnalyzerProtocol":false,"updateDevTools":true,"devToolsBrowser":"chrome","devToolsPort":null,"devToolsReuseWindows":true,"devToolsTheme"…
[9:56:46 AM] [Analyzer] [Info] <== Content-Length: 5082
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:46 AM] [Analyzer] [Info] <== {"id":2,"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"0","method":"textDocument/didOpen","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"},{"language":"yaml","pattern":"**/pubspec.yaml","scheme":"file"},{"language":"yaml","pattern":"**/analysis_options.yaml","scheme":"file"},{"language":"yaml","pattern":"**/lib/fix_data.yaml","scheme":"file"}]}},{"id":"1","method":"textDocument/didClose","registerOptions":{"documentSelector":[…
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 72
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"result":null,"clientRequestTime":1676703406749}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 842
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart","languageId":"dart","version":1,"text":"import 'package:flutter/material.dart';\nimport 'package:flutter_riverpod/flutter_riverpod.dart';\nimport 'package:fresh_admin_dashbord/extenstions.dart';\npart './components/components.dart';\n\nclass Home extends ConsumerWidget {\n  const Home({super.key});\n\n  @override…
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 232
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"}},"clientRequestTime":1676703406751}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 232
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"}},"clientRequestTime":1676703406752}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 231
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"method":"textDocument/documentColor","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"}},"clientRequestTime":1676703406752}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 349
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":4,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"},"range":{"start":{"line":22,"character":1},"end":{"line":22,"character":1}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1676703406752}
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 302
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":5,"method":"textDocument/inlayHint","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":23,"character":0}}},"clientRequestTime":1676703406753}
[9:56:46 AM] [Analyzer] [Info] <== Content-Length: 188
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:46 AM] [Analyzer] [Info] <== {"id":1,"jsonrpc":"2.0","error":{"code":-32007,"data":"/Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart","message":"File is not being analyzed"}}Content-Length: 188
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":2,"jsonrpc":"2.0","error":{"code":-32007,"data":"/Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart","message":"File is not being analyzed"}}
[9:56:46 AM] [Analyzer] [Info] <== Content-Length: 36
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":4,"jsonrpc":"2.0","result":[]}Content-Length: 188
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":3,"jsonrpc":"2.0","error":{"code":-32007,"data":"/Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart","message":"File is not being analyzed"}}Content-Length: 188
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":5,"jsonrpc":"2.0","error":{…
[9:56:46 AM] [Analyzer] [Info] ==> Content-Length: 230
[9:56:46 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":6,"method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"}},"clientRequestTime":1676703406951}
[9:56:46 AM] [General] [Info] Returning cached results for project search
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 214
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:47 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/android/app/src/profile/AndroidManifest.xml"}}
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 211
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/android/app/src/main/AndroidManifest.xml"}}
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 212
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:47 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/android/app/src/debug/AndroidManifest.xml"}}
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 192
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:47 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/analysis_options.yaml"}}Content-Length: 183
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:47 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/pubspec.yaml"}}
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":3,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:56:47 AM] [Analyzer] [Info] ==> Content-Length: 72
[9:56:47 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"result":null,"clientRequestTime":1676703407767}
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 228
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:47 AM] [Analyzer] [Info] <== {"id":6,"jsonrpc":"2.0","result":[{"endLine":3,"kind":"imports","startLine":0},{"endLine":22,"startLine":5},{"endLine":21,"startLine":9},{"endLine":20,"startLine":10},{"endLine":19,"startLine":12},{"endLine":16,"startLine":14}]}
[9:56:47 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 191
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/extenstions.dart"}}Content-Length: 204
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/network/dio/dio_provider.dart"}}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 207
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/models/card_type.dart"}}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 518
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"avoid_print","codeDescription":{"href":"https://dart-lang.github.io/linter/lints/avoid_print.html"},"message":"Don't invoke 'print' in production code.\nTry using a logging framework.","range":{"end":{"character":9,"line":17},"start":{"character":4,"line":17}},"severity":3,"source":"dart"}],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/components/ord…
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 579
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"prefer_const_constructors","codeDescription":{"href":"https://dart-lang.github.io/linter/lints/prefer_const_constructors.html"},"message":"Use 'const' with the constructor to improve performance.\nTry adding the 'const' keyword to the constructor invocation.","range":{"end":{"character":45,"line":16},"start":{"character"…
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 207
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/scaffold/destinations.dart"}}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:56:48 AM] [General] [Info] Analyzer:FirstAnalysis timing: 958ms
[9:56:48 AM] [Analyzer] [Info] ==> Content-Length: 237
[9:56:48 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":7,"method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"}},"clientRequestTime":1676703408751}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"id":4,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 45
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":7,"jsonrpc":"2.0","result":{"data":[]}}
[9:56:48 AM] [Analyzer] [Info] ==> Content-Length: 72
[9:56:48 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":4,"result":null,"clientRequestTime":1676703408817}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:56:48 AM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:48 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:56:50 AM] [Analyzer] [Info] ==> Content-Length: 261
[9:56:50 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":8,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"},"position":{"line":14,"character":19}},"clientRequestTime":1676703410635}
[9:56:50 AM] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:50 AM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"macos","name":"macOS","platform":"darwin","emulator":false,"category":"desktop","platformType":"macos","ephemeral":false,"emulatorId":null,"sdk":"macOS 13.1 22C65 darwin-arm64","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":true,"hardwareRendering":true,"startPaused":true}}}]
[9:56:50 AM] [General] [Info] Returning cached results for project search
[9:56:50 AM] [General] [Info] Checking 1 projects for supported platforms
[9:56:50 AM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord"}}]
[9:56:50 AM] [Analyzer] [Info] <== {"id":5,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:56:50 AM] [Analyzer] [Info] ==> Content-Length: 72
[9:56:50 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":5,"result":null,"clientRequestTime":1676703410696}
[9:56:50 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:50 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:56:50 AM] [Analyzer] [Info] <== Content-Length: 186
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:50 AM] [Analyzer] [Info] <== {"id":8,"jsonrpc":"2.0","error":{"code":-32013,"data":"/Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart","message":"Analysis failed for file"}}
[9:56:50 AM] [FlutterDaemon] [Info] <== [{"id":"3","result":{"platforms":["linux","macos","windows","ios","android","web"]}}]
[9:56:50 AM] [General] [Info] Supported platforms for the workspace are linux, macos, windows, ios, android, web
[9:56:50 AM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:56:50 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:56:54 AM] [Analyzer] [Info] ==> Content-Length: 351
[9:56:54 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":9,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/noamanmonther/FreeLance/Noon/Fresh-Eco/fresh_admin_dashbord/lib/views/home/home.dart"},"range":{"start":{"line":16,"character":10},"end":{"line":16,"character":10}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1676703414694}
[9:56:54 AM] [Analyzer] [Error] Unhandled exception:
Null check operator used on a null value
#0      MetadataResolver.visitExportDirective (package:analyzer/src/summary2/metadata_resolver.dart:104:17)
#1      ExportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:4344:50)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9606:20)
#3      MetadataResolver.visitCompilationUnit (package:analyzer/src/summary2/metadata_resolver.dart:64:21)
#4      CompilationUnitImpl.accept (package:analyzer/src/dart/…
[9:56:54 AM] [Analyzer] [Info] Spawning /Users/noamanmonther/flutterDev/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.58.0"]
[9:56:54 AM] [Analyzer] [Info]     PID: 55300
```

**Comment by devnoaman** [comment] 2023-02-18 08:33
it was solved after i moved the part and part of !

**Comment by lucavenir** [comment] 2023-02-18 10:46
Have you tried using the "newest" lints? Add `riverpod_lint: ^1.0.1` to `pubspec.yaml`.

**Comment by rrousselGit** [comment] 2023-02-18 11:22
The stacktrace says Analyzer itself is the problem, not custom_lint/riverpod_lint

Do you have a way to reproduce the error?

**Comment by devnoaman** [comment] 2023-02-18 17:55
@rrousselGit  , as i mention, i has part and part of in my code , after remove them every thing just work fine , need to find out more

**Comment by pattobrien** [comment] 2023-02-19 07:14
I'm also experiencing the same crashing while using `riverpod_lint: ^1.0.1`, immediately when adding it to a Dart project.

So far, I'm unsure of what the cause could be and don't have a work around; if you need additional info about my project or something else, I can try to be of help.

```
[✓] Flutter (Channel stable, 3.3.5, on macOS 13.2.1 22D68 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

**Comment by rrousselGit** [comment] 2023-02-19 16:10
If you could create a git repository to reproduce the issue, that would be great

**Comment by rrousselGit** [comment] 2023-03-13 09:52
I can't progress on this issue without any more information.

If anyone has this issue, it'd be lovely if you could make a GitHub repository with your project that faces this issue.

**Comment by rrousselGit** [comment] 2023-03-18 09:50
Closing as there's nothing I can do.

If you still have the problem, please open a new issue with more information.

**Closed by rrousselGit** 2023-03-18 09:50 UTC
Labels: bug, question, linter
