### ISSUE TITLE
ProviderObserver does not trigger didDisposeProvider?

### ISSUE THREAD

**Issue by TreyThomas93** [rrousselGit/riverpod#1646] opened 2022-09-17 17:46 UTC
**Is your feature request related to a problem? Please describe.**
I am wanting to call ref.invalidate for my providers upon the destruction of the StateNotifier.autoDispose and was wondering if there is or could be a method for this?

**Describe the solution you'd like**
Have an override method like destroy that is called the moment the StateNotifier is auto disposed of. I was using dispose, but that only fires upon recreation of the StateNotifier.

**Describe alternatives you've considered**
Right now I create a custom method within the StateNotifier that I then call from outside of it, but this is messy and annoying. Would be easier to handle it all within the StateNotifier.

**Comment by rrousselGit** [comment] 2022-09-17 20:32
> I was using dispose, but that only fires upon recreation of the StateNotifier.

What do you mean by this?

Overriding `StateNotifier.dispose` or using `Ref.onDispose`should be what you're looking for.

**Comment by TreyThomas93** [comment] 2022-09-17 20:44
@rrousselGit
```
final sessionsFormStateNotifier =
    StateNotifierProvider<SessionsFormNotifier, bool>(
        (ref) => SessionsFormNotifier(ref),
        name: "sessionsFormStateNotifier");

class SessionsFormNotifier extends StateNotifier<bool> {
  SessionsFormNotifier(this.ref) : super(false);

  final Ref ref;

  @override
  void dispose() {
    ref.invalidate(provider);
    super.dispose();
  }
}
```

The dispose method did not get called when I no longer was using the StateNotifier with autoDispose. It only fired when I recreated the StateNotifier when going back into the page I was using it with.

**Comment by TreyThomas93** [comment] 2022-09-17 20:52
Ok so the dispose method is firing correctly upon disposal of notifier, but the ref.invalidate is not calling the didDisposeProvider in ProviderObserver until the next time I read, watch, listen to the provider. Does that mean that invalidate is not disposing until the next time it's being used?

**Comment by rrousselGit** [comment] 2022-09-17 20:58
That shouldn't be the case. In theory the provider should be disposed almost immediately (although not necessarilysynchronously).

**Comment by TreyThomas93** [comment] 2022-09-17 20:59
@rrousselGit Here's a better recap

```
I/flutter ( 8727): Notifier Created! 2022-09-17 15:54:31.235771 <-- Entered page 
I/flutter ( 8727): ┌─────────────────────────────────────────────────
I/flutter ( 8727): │ 🐛 [Riverpod] Disposing sessionsFormStateNotifier 2022-09-17 15:54:48.596277 <-- Left page | ref.invalidate called
I/flutter ( 8727): └─────────────────────────────────────────────────
I/flutter ( 8727): ┌───────────────────────────────────────────────── 
I/flutter ( 8727): │ 🐛 [Riverpod] Disposing sessionsViewProvider 2022-09-17 15:54:51.082159 <-- Re-entered page | Now shows disposal of provider.
I/flutter ( 8727): └─────────────────────────────────────────────────
```

**Comment by rrousselGit** [comment] 2022-09-17 21:06
I wouldn't trust ProviderObserver.

ref.onDispose is a better source of information.

**Comment by TreyThomas93** [comment] 2022-09-17 21:35
@rrousselGit How do I know for sure that the provider has been disposed of?

**Comment by rrousselGit** [comment] 2022-09-18 17:29
ref.onDispose does exactly that. Since that's quite literally the dispose method of a provider

ProviderObserver should too, but it's not impossible that it is currently bugged.

**Comment by TreyThomas93** [comment] 2022-09-18 17:32
Is there a way to add all providers to a container an simple call a dispose method that disposes all at once?

**Comment by rrousselGit** [comment] 2023-11-26 16:14
From my tests, there are no ways for onDispose to be executed but ProviderObservers not to be triggered.

I'll close this for now as I lack information to do anything. If you have the problem, please share a running example to reproduce

**Closed by rrousselGit** 2023-11-26 16:14 UTC
Labels: bug, needs triage
