### ISSUE TITLE
Give the option to tell riverpod what name the generated provider should have

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#2279] opened 2023-03-07 18:01 UTC
**Is your feature request related to a problem? Please describe.**
Related to #2262 
In many cases, the source of a generated provider can collide with the type of the data in the state it contains
for example, I might want a `profileProvider` which provides my `Profile`s
for a function that's easy, name it `profile(...)`
for a class? i cant do that. i would have to name it `ProfileNotifier` which results in `profileNotifierProvider` which adds an inconsistency to the names of my providers

**Describe the solution you'd like**
One possible solution is to allow us to define within the annotation a renameTo or something like that `@Riverpod(renameTo: 'profile')` where the default behavior is equivalent to `@Riverpod(renameTo: 'profileNotifier')`
(parameter name could be whatever makes the most sense. `name`, maybe?)

Possibly could require defining it as `@Riverpod(renameTo: 'profileProvider')` if we wanted it to also act as an override of the suffix, though that may be necessarily extra

**Describe alternatives you've considered**
I could simply alias as: `final profileProvider = profileNotifierProvider;' but as mentioned in #2262 this is not supported

This could be a separate annotation  `@RiverpodRename('profile')`/`@RiverpodRename('profileProvider', applySuffix: false)` but that seems unnecessary

**Additional context**
Some inspiration could be taken from `json_serializable`'s `@JsonKey(...)`

**Comment by rrousselGit** [comment] 2023-03-07 18:36
Duplicate of https://github.com/rrousselGit/riverpod/issues/2244

**Closed by rrousselGit** 2023-03-07 18:36 UTC
Labels: enhancement, riverpod_generator
