### ISSUE TITLE
riverpod_generator : warnings in 2.4.3 - No way to use 2.6.0

### ISSUE THREAD

**Issue by icodeyou** [rrousselGit/riverpod#3794] opened 2024-10-21 08:50 UTC
**Describe the bug**
There is a warning when using riverpod_generator 2.4.3 :
```
'FutureProviderRef' is deprecated and shouldn't be used. will be removed in 3.0.0. Use Ref instead.
Try replacing the use of the deprecated member with the replacement.
```

Maybe the warning won't be here anymore using the last version : 2.6.0.
The problem is I can't use the last version. When I run `flutter pub outdated`, it says that it can't be higher than 2.4.3

I use the last version of Flutter on , and I specify the last Dart version in my pubspec.

*Note : We can use the version 2.6.0 if we use the master channel*
-> And it removes the warning ✅

---

**To Reproduce**

1. Use the stable or dev channel
2. `flutter upgrade`
3. `flutter create newriverpodapp`
4. `cd newriverpodapp/`
5. `flutter pub add --dev riverpod_generator`
6. `flutter pub upgrade --major-versions`
7.  Check version of riverpod_generator in pubspec.yaml : It is still 2.4.3

**Expected behavior**
We want to be able to use the version 2.6.0 on this new project.

**Comment by rrousselGit** [comment] 2024-10-21 10:41
You should be able to use a dependency_override on `analyzer` to fix it.

Supporting lower analyzer versions is a pain. I'd have to maintain two versions of Riverpod for months whenever analyzer releases some breaking changes (which is quite often).

**Comment by sharpsan** [comment] 2024-10-21 18:57
> You should be able to use a dependency_override on `analyzer` to fix it.
> 
> Supporting lower analyzer versions is a pain. I'd have to maintain two versions of Riverpod for months whenever analyzer releases some breaking changes (which is quite often).

You're not the only package we use.  This is a strange attitude to take when there is no need to be on the latest cutting-edge version of deps.

**Comment by rrousselGit** [comment] 2024-10-21 19:23
That's a bit paradoxical, considering the very reason you're complaining about this is because you're trying to be on the latest Riverpod cutting-edge 😛 

Generally the problem is fairly easy to fix: Loosen your version constraint

```yaml
dependencies:
  riverpod: ^2.0.0
  riverpod_annotation: ^2.0.0

dev_dependencies:
  riverpod_generator: ^2.0.0
```

Pub will pick the most relevant one itself.

**Comment by sharpsan** [comment] 2024-10-21 19:28
> That's a bit paradoxical, considering the very reason you're complaining about this is because you're trying to be on the latest Riverpod cutting-edge 😛
> 
> Generally the problem is fairly easy to fix: Loosen your version constraint
> 
> ```yaml
> dependencies:
>   riverpod: ^2.0.0
>   riverpod_annotation: ^2.0.0
> 
> dev_dependencies:
>   riverpod_generator: ^2.0.0
> ```
> 
> Pub will pick the most relevant one itself.

I _prefer_ to be on the latest version, but I don't * require* it ;)

**Comment by l1qu1d** [comment] 2024-10-21 19:38
We are using `Flutter` on the `stable channel`. Would it be a better solution to have Riverpod's packages always be compatible with the latest stable version of Flutter? I know it's not always feasible and there are a lot of packages that aren't compatible, but Riverpod is such an important and amazing package. We all want to use the latest 😊. 

I started a fresh project in Flutter and followed the install instructions for Riverpod and this is the `flutter pub outdated`'s results:
<details>
  <summary>flutter pub outdated (click me)</summary>

```terminal

Package Name                  Current        Upgradable     Resolvable     Latest        

direct dependencies: all up-to-date.

dev_dependencies:
custom_lint                   *0.6.8         *0.6.8         *0.6.8         0.6.10        
riverpod_generator            *2.4.3         *2.4.3         *2.4.3         2.6.0
riverpod_lint                 *2.3.13        *2.3.13        *2.3.13        2.4.0

transitive dependencies:     
characters                    *1.3.0         *1.3.0         *1.3.0         1.3.1
collection                    *1.18.0        *1.18.0        *1.18.0        1.19.1        
material_color_utilities      *0.11.1        *0.11.1        *0.11.1        0.12.0        
meta                          *1.15.0        *1.15.0        *1.15.0        1.16.0        
path                          *1.9.0         *1.9.0         *1.9.0         1.9.1
stack_trace                   *1.11.1        *1.11.1        *1.11.1        1.12.0        

transitive dev_dependencies: 
_fe_analyzer_shared           *72.0.0        *72.0.0        *72.0.0        76.0.0        
analyzer                      *6.7.0         *6.7.0         *6.7.0         6.11.0        
async                         *2.11.0        *2.11.0        *2.11.0        2.12.0        
custom_lint_builder           *0.6.8         *0.6.8         *0.6.8         0.6.10        
custom_lint_core              *0.6.5         *0.6.5         *0.6.5         0.6.10        
fake_async                    *1.3.1         *1.3.1         *1.3.1         1.3.2
http_parser                   *4.0.2         *4.0.2         *4.0.2         4.1.1
leak_tracker                  *10.0.5        *10.0.5        *10.0.5        10.0.7        
leak_tracker_flutter_testing  *3.0.5         *3.0.5         *3.0.5         3.0.8
lints                         *5.0.0         *5.0.0         *5.0.0         5.1.0
macros                        *0.1.2-main.4  *0.1.2-main.4  *0.1.2-main.4  0.1.3-main.0
matcher                       *0.12.16+1     *0.12.16+1     *0.12.16+1     0.12.17
riverpod_analyzer_utils       *0.5.4         *0.5.4         *0.5.4         0.5.5
shelf                         *1.4.1         *1.4.1         *1.4.1         1.4.2
string_scanner                *1.2.0         *1.2.0         *1.2.0         1.4.0
test_api                      *0.7.2         *0.7.2         *0.7.2         0.7.3
vm_service                    *14.2.5        *14.2.5        *14.2.5        14.3.0
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```
</details>

**Comment by snapsl** [comment] 2024-10-21 19:41
The issue is that `riverpod` resolves to 2.6.0 while `riverpod_generator` resolves to 2.5.* .

**Comment by colinbes** [comment] 2024-10-21 20:51
I am not getting same warning messages as @icodeyou when using generator 2.4.3. I am on stable channel and after update today to 2.6.0  I had warnings of deprecated in defining provider reference and that we need to use the new `Ref` which I did. 
Before dependency updates my providers looked like:
```
@riverpod
BioChargerAPI biochargerApiClient(BiochargerApiClientRef ref) {...}
```

Code was then updated to:
```
@riverpod
BioChargerAPI biochargerApiClient(Ref ref) {...}
```

Warning I was getting before after change is still  the same:
'AutoDisposeProviderRef' is deprecated and shouldn't be used. will be removed in 3.0.0. Use Ref instead.
Try replacing the use of the deprecated member with the replacement.
Offending line shown below.
```
typedef BiochargerApiClientRef = AutoDisposeProviderRef<BioChargerAPI>;
```

I am assuming this is due to `riverpod_generator` still being version 2.4.3. If I try to update dependency to 2.4.4 or 2.6.0 I soon disappear down dependency hell hole.

```
Because riverpod_generator >=2.6.0 <3.0.0-dev.2 depends on riverpod_analyzer_utils 0.5.5 which depends on analyzer ^6.9.0, riverpod_generator >=2.6.0 <3.0.0-dev.2 requires analyzer ^6.9.0.
And because analyzer >=6.8.0 depends on collection ^1.19.0 and every version of flutter_test from sdk depends on collection 1.18.0, riverpod_generator >=2.6.0 <3.0.0-dev.2 is incompatible with flutter_test from sdk.
So, because flutter_ng_flex depends on both flutter_test from sdk and riverpod_generator ^2.6.0, version solving failed.
```

Again I am seeing issues with collections module on flutter sdk being pinned to 1.18.0 I don't see a way out.

It's very possible that I am missing some salient point.

**Comment by 0xdanny** [comment] 2024-10-21 22:53
`collection` is pinned to version 1.18.0 by flutter_test from the flutter SDK.
See [SDK version pinning](https://dart.dev/go/sdk-version-pinning) for details.


Because `riverpod_lint >=2.3.14 <3.0.0-dev.0` depends on `analyzer ^6.9.0` which depends on `collection ^1.19.0`, `riverpod_lint >=2.3.14 <3.0.0-dev.0` requires `collection ^1.19.0`.
And because every version of `flutter_test` from `sdk` depends on `collection 1.18.0`, riverpod_lint >=2.3.14 <3.0.0-dev.0 is incompatible with flutter_test from sdk.

version solving failed.

**Comment by rrousselGit** [comment] 2024-10-22 01:26
I'll look into loosening the analyzer version for riverpod_generator.
But riverpod_lint probably won't be able to upgrade.

**Comment by arnoutvandervorst** [comment] 2024-10-22 05:42
When trying to do a dependency_override for analyzer, I get:

Resolving dependencies...
Because analyzer >=6.9.0 depends on macros >=0.1.3-main.0 <0.1.4 which depends on _macros 0.3.3 from sdk, analyzer >=6.9.0 requires _macros 0.3.3 from sdk.
So, because no versions of _macros from sdk match 0.3.3 and stylesnap depends on analyzer ^6.11.0, version solving failed.

**Comment by icodeyou** [comment] 2024-10-22 06:37
Maybe I shouldn't, because the build error is related to the fact that I override the analyzer.
Here is the log :

```text
Resolving dependencies in `/Users/mb/Documents/projects/Flutter/MY_PROJECTS/ALCHEMY/hello_riverpod/MASTERBRANCH`... 
Downloading packages... 
Got dependencies in `/Users/mb/Documents/projects/Flutter/MY_PROJECTS/ALCHEMY/hello_riverpod/MASTERBRANCH`.
Building package executable... (2.3s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 157ms
[WARNING] ../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:818:30: Error: Type 'NullAwareElement' not found.
  void visitNullAwareElement(NullAwareElement node) {
                             ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:2160:28: Error: Type 'NullAwareElement' not found.
  final List<_Subscription<NullAwareElement>> _forNullAwareElement = [];
                           ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:2162:33: Error: Type 'NullAwareElement' not found.
      String key, void Function(NullAwareElement node) listener) {
                                ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:3365:42: Error: Type 'NullAwareElement' not found.
  void addNullAwareElement(void Function(NullAwareElement node) listener) {
                                         ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/riverpod_analyzer_utils-0.5.5/lib/src/riverpod_ast/ref_invocation.dart:24:10: Error: The getter 'enclosingElement3' isn't defined for the class 'MethodElement'.
 - 'MethodElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../../../.pub-cache/hosted/pub.dev/analyzer-6.7.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement3'.
        .enclosingElement3;
         ^^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/riverpod_analyzer_utils-0.5.5/lib/src/riverpod_ast/widget_ref_invocation.dart:29:10: Error: The getter 'enclosingElement3' isn't defined for the class 'MethodElement'.
 - 'MethodElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../../../.pub-cache/hosted/pub.dev/analyzer-6.7.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement3'.
        .enclosingElement3;
         ^^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:818:30: Error: 'NullAwareElement' isn't a type.
  void visitNullAwareElement(NullAwareElement node) {
                             ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:820:11: Error: Superclass has no method named 'visitNullAwareElement'.
    super.visitNullAwareElement(node);
          ^^^^^^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:2160:28: Error: 'NullAwareElement' isn't a type.
  final List<_Subscription<NullAwareElement>> _forNullAwareElement = [];
                           ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:2162:33: Error: 'NullAwareElement' isn't a type.
      String key, void Function(NullAwareElement node) listener) {
                                ^^^^^^^^^^^^^^^^
../../../../../../../.pub-cache/hosted/pub.dev/custom_lint_core-0.6.10/lib/src/node_lint_visitor.g.dart:3365:42: Error: 'NullAwareElement' isn't a type.
  void addNullAwareElement(void Function(NullAwareElement node) listener) {
                                         ^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 2.3s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

Note : I didn't have this warning before overriding the analyzer.

Note 2 : I still have the build error when I fix Riverpod version to 2.4.3 (without "^")

**Comment by PROGrand** [comment] 2024-10-22 08:24
Even `riverpod-2.6.0` itself does not compile on `stable` flutter
```shell
$ flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (6 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

$ git checkout tags/riverpod-v2.6.0

$ dart pub global run melos bs
melos bootstrap
  └> D:\temp\riverpod

Running "flutter pub get" in workspace packages...
Note: this may take a while in large workspaces such as this one.
  ✓ generate_providers
    └> tools/generate_providers
  - riverpod_graph
    └> packages/riverpod_graph
       └> Failed to install.

Resolving dependencies...
Because analyzer >=6.9.0 depends on macros >=0.1.3-main.0 <0.1.4 which depends on _macros 0.3.3 from sdk, analyzer >=6.9.0 requires _macros 0.3.3 from sdk.
So, because no versions of _macros from sdk match 0.3.3 and riverpod_graph depends on analyzer 6.9.0, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on analyzer: dart pub add analyzer:^6.8.0
BootstrapException: Failed to install.: riverpod_graph at d:\temp\riverpod\packages\riverpod_graph.
```

Only the limiting of riverpod version works in projects:

pubspec.yaml:

```yaml
dependencies:
  riverpod: "<2.6.0"
  flutter_riverpod: "<2.6.0"
  hooks_riverpod: "<2.6.0"
dev_dependencies:
  riverpod_annotation: "<2.6.0"
  riverpod_generator: "<2.6.0"

```

**Comment by arnoutvandervorst** [comment] 2024-10-22 08:42
_macros 0.3.3, is that part of the master channel? When I switch to beta, I still cannot upgrade to analyzer 6.9.0 due to this _macros package...

**Comment by rrousselGit** [comment] 2024-10-22 10:18
@icodeyou  6.7.0 isn't compatible with Riverpod since it uses 6.9.0 ;)

My suggestion is to do:

```dart
dependency_overrides:
  analyzer: ^6.9.0
```

**Closed** 2024-10-22 12:45 UTC
Labels: bug, needs triage

**Comment by JPM84** [comment] 2024-10-22 13:43
> @icodeyou 6.7.0 isn't compatible with Riverpod since it uses 6.9.0 ;)
> 
> My suggestion is to do:
> 
> ```dart
> dependency_overrides:
>   analyzer: ^6.9.0
> ```

But does this really work with flutter stable? The reason being:
```sh
Because every version of flutter_test from sdk depends on collection 1.18.0 and analyzer >=6.8.0 depends on collection ^1.19.0, flutter_test from sdk is incompatible with analyzer >=6.8.0.
```
Guess I will have to wait for a flutter stable release supporting analyzer > 6.8.0 before updating to Riverpod 2.6.0?

**Comment by zonda-alias** [comment] 2025-03-08 14:48
@riverpod
class RepoProvider extends _$RepoProvider {
  @override
  XXRepository build() {
    return XXRepository();
  }
}
