### ISSUE TITLE
Issue mocking family async notifier

### ISSUE THREAD

**Issue by imtoori** [rrousselGit/riverpod#2667] opened 2023-06-20 06:31 UTC
### Discussed in https://github.com/rrousselGit/riverpod/discussions/2665

<div type='discussions-op-text'>

<sup>Originally posted by **imtoori** June 19, 2023</sup>
I'm having an issue while mocking an AsyncNotifier

My controller is something like this 
```dart
@riverpod
class AlertGroupsController extends _$AlertGroupsController {
  @override
  Future<AlertGroupsUiState> build(AGListFilter? filter) async {
    final alertGroupRepository = await ref.watch(AlertGroupRepository.provider);
    final alertGroups = await alertGroupRepository.getLocalAlertGroups(
      filter: filter,
    );

    return AlertGroupsUiState(alertGroups: alertGroups);
  }
...
```

This is my mock
```dart

class MockAlertGroupsController
    extends AutoDisposeFamilyAsyncNotifier<AlertGroupsUiState, AGListFilter?>
    with Mock
    implements AlertGroupsController {
  @override
  Future<AlertGroupsUiState> build(AGListFilter? filter) async {
    return const AlertGroupsUiState(alertGroups: []);
  }

  @override
  Future<void> getMoreAlertGroups() async {}
}

```

During tests I get this error

```
Error: type 'MockAlertGroupsController' is not a subtype of type 'AutoDisposeAsyncNotifier<AlertGroupsUiState>' in type cast
```

Following the stacktrace this happens right when I call ref.read/watch on the generated provider.

Any ideas on how to fix this? I managed to solve </div>

I even tried extending `_$AlertGroupsController` instead of `AutoDisposeFamilyAsyncNotifier<AlertGroupsUiState, AGListFilter?>`, but it didn't work.
I built a small poc [here](https://github.com/imtoori/test_riverpod). You can clone it and run `flutter test` and you'll get the same error.

**Comment by rrousselGit** [comment] 2023-06-20 13:10
Afaik it's a duplicate of #2047

It should be fixed soon enough

**Closed** 2023-06-20 13:10 UTC

**Comment by tomadimitrie** [comment] 2023-08-23 20:54
@imtoori see my comment: https://github.com/rrousselGit/riverpod/issues/2047#issuecomment-1690624080
