### ISSUE TITLE
General problems with `keepAlive`

### ISSUE THREAD

**Issue by FaFre** [rrousselGit/riverpod#2511] opened 2023-05-01 16:09 UTC
It seems like keep alive never does what it supposed to do.

I have the following Notifier:
```dart
@Riverpod(keepAlive: true)
Duration ntpOffsetLifetime(NtpOffsetLifetimeRef ref) {
  return const Duration(minutes: 1);
}

@riverpod
class Ntp extends _$Ntp {
  void _cacheOffset(Duration lifetime) {
    final link = ref.keepAlive();
    final timer = Timer(lifetime, () {
      logger.i('Invalidating NTP offset');
      link.close();
    });
    ref.onDispose(() => timer.cancel());
  }

  @override
  FutureOr<Duration> build() async {
    final lifetime = ref.watch(ntpOffsetLifetimeProvider);

    final offset =
        await NTP.getNtpOffset(lookUpAddress: 'pool.ntp.org').then((value) {
      _cacheOffset(lifetime);
      return value;
    }).onError((error, stackTrace) {
      logger.e('Cannot fetch NTP offset', error, stackTrace);
      return 0;
    });

    logger.i('Set NTP offset to ${offset}ms');

    return Duration(milliseconds: offset);
  }

  Future<DateTime> now() {
    return future.then((offsetDuration) => DateTime.now().add(offsetDuration));
  }
}
```

In the example above, the provider is supposed to cache the value for one Minute. However, after canceling the link, the Notifier is not getting rebuilt. From my logs I can see, that `cancel()` is getting called indeed.

I obtain the notifier like this in my widget: `final ntpNotifier = ref.watch(ntpProvider.notifier);`

Previously I posted the old version of above on Discord and asked for help. Here the problem is the opposite, the provider is not getting kept alive and rebuilt every time:

```dart
@riverpod
Future<_NtpDateTime> _ntp(_NtpRef ref) async {
  final localTime = DateTime.now();

  final offset = await NTP
      .getNtpOffset(localTime: localTime, lookUpAddress: 'pool.ntp.org')
      .onError((error, stackTrace) {
    logger.e('Cannot fetch NTP offset', error, stackTrace);
    return 0;
  });

  ref.keepAlive();

  logger.i('Set NTP offset to ${offset}ms');

  return _NtpDateTime(localTime, offset);
}
```

**Comment by FaFre** [comment] 2023-05-02 17:08
> what's the point to use `await` and `then` at the same time?

You can read more about futures and error hanfling in this article: https://dart.dev/guides/libraries/futures-error-handling

**Comment by rrousselGit** [comment] 2024-03-01 17:17
Sorry for the long delay. I cannot reproduce the issue, so either you need to share more steps to reproduce the issue, or this was fixed.

Considering this is a year old, I'll close this. 
Please open a new issue if that's still a problem, and sorry for the inconvenience.

**Closed by rrousselGit** 2024-03-01 17:17 UTC
Labels: bug, needs triage
