### ISSUE TITLE
Watching an overriden provider prevents listening on a dependent provider

### ISSUE THREAD

**Issue by gazialankus** [rrousselGit/riverpod#2089] opened 2023-01-16 06:13 UTC
**Describe the bug**

I have a `baseProvider` and a `dependentProvider`. I override `baseProvider` and then listen to `dependentProvider` under it in the widget tree. Listening to `dependentProvider` works well, until I start to watch `baseProvider`. Watching `baseProvider` prevents listening to `dependentProvider`. This is unexpected and it seems to be a bug. @rrousselGit also thinks so: https://stackoverflow.com/questions/75122119/riverpod-overriding-and-watching-prevents-listening-on-a-dependent-provider#comment132570000_75122119

**To Reproduce**

The StackOverflow question has a couple of ways to reproduce this: https://stackoverflow.com/questions/75122119/riverpod-overriding-and-watching-prevents-listening-on-a-dependent-provider

Among these, the DartPad example is the easiest to experience: https://dartpad.dev/?id=3aefed6429499de5a939a6c50d158534 Run it, press the button and check the console. When you uncomment the line that it refers to, the bug manifests and as a result the console output is no longer printed. 

There is also a public repository here that demonstrates this issue: https://github.com/gazialankus/riverpod_query_play master branch is the same as the DartPad example. The `stateprovider_instead_of_scope` branch there shows that the bug only happens when you actually override `baseProvider`. 

**Expected behavior**
Listening to `dependentProvider` should be possible even when you watch the overriden`baseProvider`.

**Comment by gazialankus** [comment] 2023-01-16 06:43
A very simple workaround is to add a `baseProxyProvider` and watching it. This bypasses the issue. https://github.com/gazialankus/riverpod_query_play/commit/c6bbc97265c139dd4c1556aeb8c2d331481656bb

```
final baseProxyProvider = Provider<int>(
  (ref) {
    return ref.watch(baseProvider);
  },
  dependencies: [baseProvider],
);

    // uncommenting this prevents listen
    // final q = ref.watch(baseProvider);

    // using a proxy provider bypasses this issue.
    // this is a dummy provider that relays baseProvider
    // baseProvider above still prevents listen. however this one allows listen.
    final c = ref.watch(baseProxyProvider);

    ref.listen(
      dependentProvider,

```

**Comment by gazialankus** [comment] 2023-01-16 07:44
I think the crux of the issue here is that the change happens without a rebuild in the provider. Change happens because of overriding the provider with a different value. 

The baseProxyProvider in the workaround is actually rebuilt and therefore listen works.

**Comment by gazialankus** [comment] 2023-01-16 11:15
The difference is that the listened (String) provider has zero dependencies here: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L527

Without the watch there is one, which calls listen.

**Comment by gazialankus** [comment] 2023-01-16 12:04
Having the watch for the overriden provider forces the element to be built prematurely, which naturally clears listeners and the listen does not execute as a result.

**Comment by gazialankus** [comment] 2023-01-16 12:28
So when an override's value is changed, and watch executes, this `markNeedsRebuild` here forces an immediate build, not waiting for our ref.listen. That rebuild prevents ref.listen from executing 
https://github.com/rrousselGit/riverpod/blob/master/packages/flutter_riverpod/lib/src/consumer.dart#L560

Maybe we need something softer here, like a _markDependencyChanged of element?

**Comment by rrousselGit** [comment] 2023-01-16 12:44
Thanks or investigating this. Although honestly I have other things on top of my end right now, so I can't really confirm any of this yet.

But I suppose a workaround is to refactor to a ConsumerStatefulWidget and use `ref.listenManual`

**Comment by gazialankus** [comment] 2023-01-16 12:48
Thanks. I actually found something that works for me and created a PR for you to have a look. It might be breaking other things, I'm not sure right now.

**Comment by gazialankus** [comment] 2023-01-16 22:31
This comment here is very telling. Our listen that depends on the changed overriden provider might be a listen that needs to be preserved between widget rebuilds, at least for the first build after the change in override. https://github.com/rrousselGit/riverpod/blob/master/packages/flutter_riverpod/lib/src/consumer.dart#L597
```
    // We can't implement a fireImmediately flag because we wouldn't know
    // which listen call was preserved between widget rebuild, and we wouldn't
    // want to call the listener on every rebuild.
```

**Comment by rrousselGit** [comment] 2023-01-16 22:55
One potential solution could be to remove the previous listeners _after_ `build` has been completed instead of before.

**Comment by rrousselGit** [comment] 2023-01-16 22:59
This probably would be weird though, as you wouldn't be able to call `showSnackbar` & co within the listener. Which I doubt would match people's expectations.

Honestly, I'm tempted to keep things as they are and implement a warning for them.  
It should be simple to detect, as it's a matter of preventing `ref.listen(providerWithDependencies)`

**Comment by gazialankus** [comment] 2023-01-16 23:11
I would love to be able to `ref.listen` on providers with dependencies without warnings, we rely on them to animate between previous and next states. But if we could detect the exact situation together with the specific `ref.watch` and warn about that, that would be perfect. 

[ValueProvider](https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/value_provider.dart) does not seem to have any use other than overriding and [ConsumerStatefulElement](https://github.com/rrousselGit/riverpod/blob/master/packages/flutter_riverpod/lib/src/consumer.dart#L505) seems to be where the problem really occurs, so I would expect the full solution to be somewhere in between them, if there will be any.

**Comment by rrousselGit** [comment] 2023-01-17 08:56
ValueProvider isn't the problem
The issue is in how providers rebuild.

Providers rebuild by themselves when the widget tree isn't building. Or when you try to read them

The widget tree is building when overrides update. So you are reading your provider before they update on their own. Trigerring this issue

To begin with, you wouldn't be able to use this to show modals/dialogs. So a solution other than ref.listen for your animations sounds fine

There's a bunch of possible solutions, like hooks or TweenAnimatedBuilder

**Comment by gazialankus** [comment] 2023-01-17 09:41
Very interesting and eye opening stuff. 

ref.listen should in general work just like a button press would, away from the build time, right? So, does this not beg for some kind of larger solution to ensure ref.listen works in the way it's expected to work despite overrides? 

Actually, "sanitizing" the overriden provider with a simple proxy provider that just relays the information fixes everything, it seems. Here the listen works fine and I'm able to open a dialog just fine: 

https://github.com/gazialankus/riverpod_query_play/blob/workaround/lib/main.dart#L79
https://github.com/gazialankus/riverpod_query_play/blob/workaround/lib/data.dart#L15

So, would it make sense for Riverpod to internally to "sanitize" each overriden provider with a hidden one? Maybe we can avoid such issues altogether this way?

**Comment by rrousselGit** [comment] 2023-01-17 09:48
> ref.listen should in general work just like a button press would, away from the build time, right? So, does this not beg for some kind of larger solution to ensure ref.listen works in the way it's expected to work despite overrides?

Yes, but that's the point: You can't have that with overrides. Because overrides update when the tree is locked.

Hence why I said I'd lean toward having a warning for this case and leaving it as is. Realistically, whatever we pick, we wouldn't be able to show modals/dialogs inside `ref.listen(scopedProvider)` – which would defeat the point of the feature. 

I don't understand what you mean by sanitizing the providers though.

**Comment by gazialankus** [comment] 2023-01-17 10:15
Ah yes, you mean listening to the overriden provider cannot open dialogs. You are right, I just tried and `showDialog` does not work if you `listen` to it. But `listen`ing to a provider that depends on the overriden provider works just fine. Which is exactly whan I mean by sanitization.  

Let me try to do a better job at explaining it. 

A. Here's our `scopedProvider`:
```
final scopedProvider = Provider<int>(
  (ref) => 0,
);

            ProviderScope(
              overrides: [
                scopedProvider.overrideWithValue(overridingValue),
              ],
              child: const MyConsumer(),
            ),
```
Problems with it:

A.1. Cannot listen to `scopedProvider` and `showDialog`
```
    // does not work!
    // Unhandled Exception: setState() or markNeedsBuild() called during build.
    ref.listen(scopedProvider,
      (previous, next) => showDialog(...),
    );
 ```
A.2. Cannot watch `scopedProvider` and listen to a dependent provider at the same time (my original issue)
```
    final q = ref.watch(scopedProvider);
    ref.listen(
      dependentProvider, (previous, next) => print('this should print but will not'),
    );
```

I believe we can overcome these difficulties by having Riverpod insert a hidden dummy provider for each `scopedProvider`. I call this dummy provider `sanitizedScopedProvider` below.

B. Here's our original `scopedProvider` and sanitized version of it: `sanitizedScopedProvider`. 
```
final scopedProvider = Provider<int>(
  (ref) => 0,
);

final sanitizedScopedProvider = Provider<int>(
  (ref) => ref.watch(scopedProvider),
  dependencies: [scopedProvider],
);
```

B.1. We can listen to `sanitizedScopedProvider` and `showDialog` just fine!
```
    ref.listen(sanitizedScopedProvider,
      (previous, next) => showDialog(...),
    );
```

B.2. We aan listen to a dependent provider and watch `sanitizedScopedProvider` at the same time!
```
    final q = ref.watch(sanitizedScopedProvider);

    ref.listen(
      dependentProvider,
      (previous, next) {
        showDialog(context: context, builder: (context) => AlertDialog(
          title: Text('WORKS FINE!'),
        ),);
      },
    );
```

The `dependentProvider` here can either depend on `sanitizedScopedProvider` or `scopedProvider`, it works fine in either case. This solves my original complaint. So, either of these work fine with the `ref.listen(dependentProvider)` example above: 

```
final dependentProvider = Provider<int>(
  (ref) => ref.watch(scopedProvider),
  dependencies: [scopedProvider],
);

final dependentProvider = Provider<int>(
  (ref) => ref.watch(sanitizedScopedProvider),
  dependencies: [sanitizedScopedProvider],
);
```

So here's what I'm proposing: since using `scopedProvider` directly is dangerous for the programmer (see A.1. and A.2.), let's have Riverpod create an internal `sanitizedScopedProvider` for each `scopedProvider`. Internally use `sanitizedScopedProvider` whenever the programmer wants to `ref.watch()` or `ref.listen()` to `scopedProvider`. This way we avoid the issues A.1. and A.2. and it would work as in B.1. and B.2. without the user creating a separate provider to avoid issues with the `scopedProvider`.

**Comment by gazialankus** [comment] 2023-01-18 08:28
Alternatively, since we talked about displaying a warning, maybe display a warning when someone tries to `ref.listen(scopedProvider)` or `ref.watch(scopedProvider)` since that's where the problem is. Listening to dependent provider as in `ref.listen(providerWithDependencies)` is only a problem when it depends on `scopedProvider`. `scopedProvider` has other issues (`showDialog`). So, warning is better warranted on `scopedProvider`. We can offload the burden of sanitizing to the user this way.

**Comment by rrousselGit** [comment] 2023-01-18 10:35
Specifying `dependencies` means that the provider is scoped though.

**Comment by gazialankus** [comment] 2023-01-18 11:33
I'm not sure I understand. Scoped means overriden in `ProviderScope`, right? You mean `sanitizedScopedProvider` is also scoped? I guess, but it sure does not have the problems associated with `scopedProvider`.

**Comment by rrousselGit** [comment] 2023-01-18 11:41
I mean that specifying "dependencies" means "this provider will be scoped".

Otherwise there's no point on specifying dependencies.

**Comment by rrousselGit** [comment] 2023-01-18 11:41
As such we can warn on "ref.listen(providerWithDependencies)"

**Comment by gazialankus** [comment] 2023-01-18 21:14
Oh I see what you mean. You specify dependencies for providerWithDependencies because you most likely will override one of those dependencies. Thus warn on "ref.listen(providerWithDependencies)" just in case you watch one of those dependencies.  This does something for the A.2. problem I summarized above (with false positives I must say) but problem A.1. remains.

**Comment by rrousselGit** [comment] 2023-01-18 21:48
No, A1 wouldn't be an issue.

because we'd likely have a separate lint that says "don't override providers with no dependencies".
And for the root of the tree, you could do `Provider(..., dependencies: [])` to silence the lint.

**Comment by gazialankus** [comment] 2023-01-23 18:22
Interestingly, I tried to use package:provider for overriden stuff in addition to riverpod and had a similar experience where a .listen() does not fire. 

About using listen() and animations, we have a complicated viewmodel that comes in through listen, we hold on to the previous and current, and run a bunch of animations between the two. I guess we could also check for changes in build(), or add a new widget and use its didUpdateWidget to catch the two versions of the model.

**Comment by rrousselGit** [comment] 2023-02-14 11:27
Closing in favour of https://github.com/rrousselGit/riverpod/issues/2101 and https://github.com/rrousselGit/riverpod/issues/2163

**Closed by rrousselGit** 2023-02-14 11:27 UTC
Labels: bug

**Comment by gazialankus** [comment] 2024-10-30 22:59
For the record, this does not seem to be an issue at all. The Dartpad example I had shared does not manifest the problem anymore.
