### ISSUE TITLE
Code generator for generic type

### ISSUE THREAD

**Issue by xantocoder** [rrousselGit/riverpod#2499] opened 2023-04-27 01:59 UTC
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.

**Code generator show that it ignores "extends TodoModel" in the generated file.**

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

```
@riverpod
class ClassExample<T extends TodoModel> extends _$ClassExample<T> {
  @override
  List<T> build() => <T>[];
}
```

**Comment by rrousselGit** [comment] 2023-04-27 07:27
Please correctly fill the issue template. I do no understand what this is about

**Comment by xantocoder** [comment] 2023-04-27 11:16
> Please correctly fill the issue template. I do no understand what this is about

I am sorry not to fill clearly. I mean that if we use code generator to process the following code.

@riverpod
class ClassExample<**T extends TodoModel**> extends _$ClassExample<T> {
  @override
  List<T> build() => <T>[];
}


**T extends TodoModel** should also be copy to the generated file.

However, this is the generated file. You can see the **extends TodoModel** is ignored by the code generator. I don't know if it's a bug.

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'c.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$classExampleHash() => r'3747b65ab76db0ad409d2aece1c00c56152337e1';

/// See also [ClassExample].
@ProviderFor(ClassExample)
final classExampleProvider =
    AutoDisposeNotifierProvider<ClassExample, List<T>>.internal(
  ClassExample.new,
  name: r'classExampleProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$classExampleHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$ClassExample = AutoDisposeNotifier<List<T>>;
// ignore_for_file: unnecessary_raw_strings, subtype_of_sealed_class, invalid_use_of_internal_member, do_not_use_environment, prefer_const_constructors, public_member_api_docs, avoid_private_typedef_functions

**Comment by xantocoder** [comment] 2023-04-27 11:23
Just found a bug of github, I post the following in the website, but it remove the key information “extend TodoModel”.
This is final post.
![截屏2023-04-27 下午7 17 34](https://user-images.githubusercontent.com/54810259/234847719-293c1c30-5111-4e9c-9b91-1bdabf436bb8.png)

This is the post of editing view.
![截屏2023-04-27 下午7 14 10](https://user-images.githubusercontent.com/54810259/234847752-699565ae-3aac-4c72-8def-0cea8e37a908.png)

**Comment by rrousselGit** [comment] 2023-04-27 12:32
Oh, that's because you didn't use code blocks. So github thought those <> were you typing html, because that's possible too ;) 


In any case, that's a duplicate of https://github.com/rrousselGit/riverpod/issues/2150.
This has been implemented recently in a dev channel and will be released relatively soon.

**Closed by rrousselGit** 2023-04-27 12:32 UTC
Labels: documentation, question

**Comment by xantocoder** [comment] 2023-04-28 00:56
> Oh, that's because you didn't use code blocks. So github thought those <> were you typing html, because that's possible too ;)
> 
> In any case, that's a duplicate of #2150. This has been implemented recently in a dev channel and will be released relatively soon.

Thanks for your quick reply.
