### ISSUE TITLE
`ListView.builder` is crashing because of `AutoDispose`.

### ISSUE THREAD

**Issue by hasanmhallak** [rrousselGit/riverpod#2728] opened 2023-07-13 18:48 UTC
**Describe the bug**
When using a `Listview.builder` to make a fetch on demand effect, the sliver will throw `'earliestUsefulChild != null': is not true` when you try to scroll back to old items that are currently out side of the view port due to the fact the provider is disposed. Apparently the sliver would keep track of the old items offset as they have been laid out even though they're not showing on the screen any more which will cause the problem as the providers are disposed.

when you force the provider to `keepAlive` everything works as expected.

The problem with not using auto dispose is when you use a family modifier is when calling with different argument would return a new provider. so we're just creating a new provider for every page and would be hard to keep track of which provider to dispose.

<details><summary>To Reproduce</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'main.g.dart';

@riverpod
Future<List<String>> fetchItem(FetchItemRef ref,
    {required int page, bool? te}) async {
  if (page == 4) return ['done'];
  await Future.delayed(const Duration(seconds: 3));
  return List.generate(50, (index) => '${index + page * 50}');
}

void main() {
  runApp(
    const ProviderScope(child: MaterialApp(home: MyHomePage())),
  );
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: ListView.builder(
        itemBuilder: (context, index) {
          final page = (index ~/ 50);

          final itemIndex = index % 50;
          print(index);

          final s = ref.watch(FetchItemProvider(page: page));

          return s.when(
            data: (data) {
              if (itemIndex >= data.length) return null;
              return Text(data[itemIndex]);
            },
            error: (error, stack) => const Text('error'),
            loading: () {
              if (itemIndex != 0) return null;
              return const Text('loading');
            },
          );
        },
      ),
    );
  }
}

```

</details>

**Expected behavior**
I'm not really sure about this or if this is possible or not but we should find a way to know for sure if the widgets on lazy loading are being cached by flutter or not. and then determine to dispose the provider or not.

https://github.com/rrousselGit/riverpod/assets/95232508/6d6e0369-5825-4608-8a9a-c0bdd5fc7168

**Comment by rrousselGit** [comment] 2023-07-15 09:45
Technically, it's more of a Flutter issue.
The issue could be reproduced without Riverpod.

It's probably worth making a separate bug report on the Flutter SDK

**Comment by hasanmhallak** [comment] 2023-07-15 11:30
hey @rrousselGit I apologize if I miss explained the issue. But it Appears that the problem is in my code.
```dart
loading: () {
              if (itemIndex != 0) return null;   // here
              return const Text('loading');
            },
```

After some digging with flutter implementation it appears that we can't remove the items after they've been laid out by `RenderSliverList`'s `preformLayout` method without rebuilding the whole builder widget and adjusting the `itemCount`.  this works fine though for getting new data because flutter rely on the offset of the first child to keep track of the layout offset.

I'll be closing this and move it to flutter. Thank you.

**Comment by rrousselGit** [comment] 2023-07-15 11:44
If you make a Flutter issue, could you link it here? I want to follow that issue

**Comment by hasanmhallak** [comment] 2023-07-15 11:53
of course. I'm just trying to reproduce the issue without riverpod with minimal code to make easy to identify the bug. Once I open a ticket I'll link it here.

**Comment by rrousselGit** [comment] 2023-07-15 12:11
I assume doing:

```dart
List<String> items = List.generate(100, (i) => 'Item $i');

ListView.builder(
  builder: (context, index) {
    if (index >= items.length) return null;
    return Text(items[index]);
  }
);
```

followed by:

```dart
setState(() {
  items = List.generate(50, (i) => 'Item $i');

});
```


would do the trick.

Assuming that before the setState, the user scrolled down.

**Comment by hasanmhallak** [comment] 2023-07-15 12:48
hmm this is weird I can't actually reproduce it. Here's what I've tried:
```dart
class _MyHomePageState extends State<MyHomePage> {
  List<String> items = List.generate(300, (i) => 'Item $i');
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(onPressed: () {
        setState(() {
          items.replaceRange(10, 30, ['Loading']);
          Future.delayed(const Duration(seconds: 10), () {
            setState(() {
              items.insertAll(10, List.generate(20, (i) => 'Item $i'));
            });
          });
        });
      }),
      body: ListView.builder(itemBuilder: (context, index) {
        if (index >= items.length) return null;
        return Text(items[index]);
      }),
    );
  }
}

``` 

The interesting thing is that the exception is thrown only when are awating the fetch the items, as soon as the provider updates the state, everything will works normally.

I'll try to create a way to simulate changing the state like provider and see what I'll get.

**Comment by AhmedLSayed9** [comment] 2023-07-15 12:52
> body: ListView.builder(itemBuilder: (context, index) {
        if (index >= items.length) return null;
        return Text(items[index]);
      }),

I think you should do `if (index >= items.length || items[index] == 'Loading') return null;`

**Comment by hasanmhallak** [comment] 2023-07-15 12:58
@AhmedLSayed9  You are right, I'm sorry I was so focused on the exception itself that I did not gave that much of a thought on the code. Thanks.

**Comment by hasanmhallak** [comment] 2023-07-15 13:26
linking https://github.com/flutter/flutter/issues/130658

**Comment by rrousselGit** [comment] 2023-07-15 16:13
Great thanks!
Depending on the outcome I may have to offer a unique Riverpod feature for infinite lists.

**Comment by hasanmhallak** [comment] 2023-07-15 17:30
That's great to hear. Thanks!

**Comment by kylianSalomon** [comment] 2023-07-31 15:34
A tweak I found for this issue is to setup a caching strategy for your autodisposed provider. 

You may follow Andrea Bizotto article about provider life-cycle and create your own strategy : 
[https://codewithandrea.com/articles/flutter-riverpod-data-caching-providers-lifecycle/]

I my case, I used an extension (Thanks to @bizz84) for my paginated list provider like so:

`
extension AutoDisposeRefExtension on AutoDisposeRef {
  /// Dispose fetched data when time is up and reset timer if the provided is
  /// listen again.
  ///
  /// [_defaultTimeout] is set to 30 seconds.
  ///
  /// This code has been copied from Andrea Bizotto tutorial :
  /// https://codewithandrea.com/articles/flutter-riverpod-data-caching-providers-lifecycle/
  void cacheFor({
    Duration duration = _defaultTimeout,
  }) {
    // get the [KeepAliveLink]
    final link = keepAlive();
    // a timer to be used by the callbacks below
    Timer? timer;

    // When the provider is destroyed, cancel the timer
    onDispose(() {
      timer?.cancel();
    });

    // When the last listener is removed, start a timer to dispose the cached data
    onCancel(() {
      timer = Timer(
        _defaultTimeout,
        () => link.close(),
      );
    });

    listenSelf(
      (_, next) {
        // Disposed the cached data on error
        if (next.hasError) {
          link.close();
        }
      },
    );

    // If the provider is listened again after it was paused, cancel the timer
    onResume(() {
      timer?.cancel();
    });
  }
}
`

`
@riverpod
FutureOr<PaginatedList<Language>> availableLanguages(
  AvailableLanguagesRef ref, {
  required int page,
}) {
  final repository = ref.watch(repositoryProvider);

  ref.cacheFor(duration: const Duration(hours: 2));

  return repository.getLanguages(page: page);
}
`

This is not ideal because it stores data that is no longer needed but is the only way I found to tweak the error. 
Open to suggestions.

**Comment by hasanmhallak** [comment] 2023-07-31 15:56
hey @kylianSalomon, thank you for the suggestion.  
Setting up a timer to dispose the provider will only *delay* the problem.  

As we discussed above the problem with flutter itself, I'm not sure what it is but it seems that it keeps a reference to the previously laid out children even if we use the `builder` constructor.

**Comment by rrousselGit** [comment] 2023-07-31 15:57
The issue is marked as P2 at the moment. Hopefully that means they'll fix it when they can.

**Comment by rrousselGit** [comment] 2023-11-26 15:13
One solution is to have index `n` "watch" the result of `n - 1`. 

This means that  scrolling down won't cause out of view items to dispose. But it also means scrolling up is no-longer an issue.

**Comment by hasanmhallak** [comment] 2023-12-09 09:39
> One solution is to have index n "watch" the result of n - 1.

isn't this would make riverpod watch the entire list? why not just disable `autoDispose`?

**Comment by lucavenir** [comment] 2023-12-24 15:55
> why not just disable `autoDispose`?
the suggestion is different. the nth-provider will be disposed of, as soon as you scroll up
Still...

> One solution is to have index n "watch" the result of n - 1.

Potentially, this might cause out-of-memory problems, right?

**Comment by rrousselGit** [comment] 2024-03-09 16:56
Although this is inconvenient, that's not quite a Riverpod bug.


But Riverpod will offer a way to better deal with infinite lists.

**Closed by rrousselGit** 2024-03-09 16:56 UTC
Labels: bug

**Comment by Trung15010802** [comment] 2024-04-24 02:37
> Great thanks! Depending on the outcome I may have to offer a unique Riverpod feature for infinite lists.

Can we use it right now?
