### ISSUE TITLE
Invalidating `FutureProvider` might throw

### ISSUE THREAD

**Issue by derolf** [rrousselGit/riverpod#2265] opened 2023-03-06 08:23 UTC
**Describe the bug**

I have two `FutureProvider`s. The second one propagates its invalidation to the first one.

**To Reproduce**

```
import "dart:math";

import "package:flutter_riverpod/flutter_riverpod.dart";

var iteration = 0;

final aProvider = FutureProvider(
  (ref) => Future.delayed(
    const Duration(milliseconds: 100),
    () => "latest news #${++iteration}",
  ),
);

final bProvider = FutureProvider((ref) {
  // propgate refreshing upstream
  if (ref.state.isRefreshing) {
    print("bProvider is refreshing -> invalidate aProvider");
    ref.invalidate(aProvider);
  }
  return ref.watch(aProvider.future).then((value) => value.toUpperCase());
});

final dummy = Provider((ref) {
  final a = ref.watch(aProvider);
  final b = ref.watch(bProvider);
  print("a: $a");
  print("b: $b");
  print("");
});

Future<void> main() async {
  final container = ProviderContainer();
  container.listen(dummy, (previous, next) {});
  await Future.delayed(const Duration(milliseconds: 500));
  container.invalidate(bProvider);
  await Future.any([]);
}
```

Output:

```
a: AsyncLoading<String>()
b: AsyncLoading<String>()

a: AsyncData<String>(value: latest news #1)
b: AsyncData<String>(value: LATEST NEWS #1)

bProvider is refreshing -> invalidate aProvider
a: AsyncData<String>(isLoading: true, value: latest news #1)
b: AsyncError<String>(value: LATEST NEWS #1, error: 'package:riverpod/src/async_notifier/base.dart': Failed assertion: line 352 pos 18: '_lastFuture == null': bad state, stackTrace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      FutureHandlerProviderElementMixin._handleAsync.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:352:18)
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:323:11)
#4      FutureHandlerProviderElementMixin._handleAsync (package:riverpod/src/async_notifier/base.dart:344:47)
#5      FutureHandlerProviderElementMixin.handleFuture (package:riverpod/src/async_notifier/base.dart:290:5)
#6      FutureProviderElement.create (package:riverpod/src/future_provider/base.dart:103:5)
#7      ProviderElementBase.buildState (package:riverpod/src/framework/element.dart:418:7)
#8      ProviderElementBase._performBuild (package:riverpod/src/framework/element.dart:356:5)
#9      ProviderElementBase.flush (package:riverpod/src/framework/element.dart:319:7)
#10     _ProviderScheduler._performRefresh (package:riverpod/src/framework/scheduler.dart:62:41)
#11     _ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:50:5)
#12     new Future.<anonymous closure> (dart:async/future.dart:253:37)
#13     _rootRun (dart:async/zone.dart:1390:47)
#14     _CustomZone.run (dart:async/zone.dart:1300:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#17     _rootRun (dart:async/zone.dart:1398:13)
#18     _CustomZone.run (dart:async/zone.dart:1300:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
)

a: AsyncData<String>(value: latest news #2)
b: AsyncData<String>(value: LATEST NEWS #2)
```

**Expected behavior**

Should not throw.

**Comment by AhmedLSayed9** [comment] 2023-03-06 09:37
I think this is duplicated of https://github.com/rrousselGit/riverpod/issues/2265

**Comment by rrousselGit** [comment] 2023-03-18 09:31
Definitely duplicate of https://github.com/rrousselGit/riverpod/issues/2041

**Closed by rrousselGit** 2023-03-18 09:31 UTC
Labels: bug, needs triage
