### ISSUE TITLE
"Null check operator used on a null value" in migration tool

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/riverpod#937] opened 2021-11-18 09:39 UTC
## Description

<details><summary>Click to expand logs</summary>

```
There was an error during migration, please submit a bug report to riverpod, with any relevant logs and code

The following files were not able to be successfully migrated
        <...>/helpers.dart: had error when visiting a method invocation CustomTheme.of(context)
Null check operator used on a null value
#0      RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitMethodInvocation (package:riverpod_cli/src/migrate/unified_syntax.dart:809:50)
#1      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7156:50)
#2      PropertyAccessImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8382:14)
#3      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#4      GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#5      GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#6      GeneralizingAstVisitor.visitPropertyAccess (package:analyzer/dart/ast/visitor.dart:489:50)
#7      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8378:50)
#8      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7353:17)
#9      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#10     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#11     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#12     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:443:52)
#13     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7348:50)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#15     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:381:16)
#16     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#17     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:143:46)
#18     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:377:50)
#19     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6131:19)
#20     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#21     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#22     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#23     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:387:7)
#24     RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitInstanceCreationExpression (package:riverpod_cli/src/migrate/unified_syntax.dart:601:11)
#25     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6125:15)
#26     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8550:18)
#27     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#28     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:528:40)
#29     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:500:52)
#30     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8546:50)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#32     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1056:17)
#33     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#34     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:528:40)
#35     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#36     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1052:50)
#37     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1011:12)
#38     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#39     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:330:46)
#40     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#41     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1007:50)
#42     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4950:11)
#43     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#44     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#45     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#46     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:341:58)
#47     RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitFunctionExpression (package:riverpod_cli/src/migrate/unified_syntax.dart:374:11)
#48     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4944:50)
#49     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7353:17)
#50     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#51     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#52     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#53     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:443:52)
#54     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7348:50)
#55     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#56     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:381:16)
#57     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#58     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:143:46)
#59     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:377:50)
#60     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6131:19)
#61     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#62     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#63     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#64     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:387:7)
#65     RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitInstanceCreationExpression (package:riverpod_cli/src/migrate/unified_syntax.dart:601:11)
#66     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6125:15)
#67     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7353:17)
#68     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#69     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#70     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#71     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:443:52)
#72     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7348:50)
#73     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#74     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:381:16)
#75     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#76     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:143:46)
#77     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:377:50)
#78     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6131:19)
#79     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#80     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#81     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#82     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:387:7)
#83     RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitInstanceCreationExpression (package:riverpod_cli/src/migrate/unified_syntax.dart:601:11)
#84     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6125:15)
#85     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8550:18)
#86     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#87     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:528:40)
#88     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:500:52)
#89     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8546:50)
#90     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#91     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1056:17)
#92     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#93     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:528:40)
#94     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#95     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1052:50)
#96     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1011:12)
#97     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#98     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:330:46)
#99     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#100    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1007:50)
#101    MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7016:11)
#102    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#103    GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:48)
#104    GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:235:44)
#105    GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:186:44)
#106    GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:429:56)
#107    RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitMethodDeclaration (package:riverpod_cli/src/migrate/unified_syntax.dart:731:11)
#108    MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7007:50)
#109    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#110    ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1530:13)
#111    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#112    GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:48)
#113    GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:235:44)
#114    GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:205:7)
#115    GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:440:7)
#116    GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:184:7)
#117    RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitClassDeclaration (package:riverpod_cli/src/migrate/unified_syntax.dart:228:11)
#118    ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1500:50)
#119    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#120    CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2091:21)
#121    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#122    GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#123    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2084:50)
#124    AstVisitingSuggestor.call (package:codemod/src/ast_visiting_suggestor.dart:79:10)
<asynchronous suspension>
```

</details>

```
Next Steps - either
        1: Revert your changes and wait for the migration tool to be fixed
        2: Run flutter pub upgrade and finish the migration manually using the migration guide https://riverpod.dev/docs/migration/0.14.0_to_1.0.0
```

The method call in question is defined in another package, in a file that is annotated with `// @dart=2.13`:

```dart
  static CustomThemeData of(BuildContext context) {
    return context
        .dependOnInheritedWidgetOfExactType<_InheritedCustomTheme>()!
        .theme;
  }
```

The referenced line looks like this:

```dart
@override
Widget build(BuildContext context) {
  return CustomTheme(
    data: CustomThemeData(),
    child: Builder(builder: (context) {
      return MaterialApp(
        theme: CustomTheme.of(context).materialThemeData,
        home: child,
      );
    }),
  );
}
```

### Removing the line

Removing this line will make the migration tool "succeed", but it will not apply any changes, see #938.

## Steps to reproduce

The versions are:

```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

I am not sure how to build a minimal sample out of this. When I remove that line, the tool does not crash anymore, even though the same method call is used in a hundred other files.  
What might be relevant is that the project is not using sound nulll safety. When annotating the file with `// @dart=2.14` and migrating it to null safety, the error is dropped and #938 occurs.

**Comment by creativecreatorormaybenot** [comment] 2021-11-18 09:44
Since I am not able to provide a minimal sample without additional details, I am happy to follow up with any details to further debug this.

**Comment by TimWhiting** [comment] 2021-11-18 13:52
Thanks for this, I'll try to reproduce the error and fix the migration tool

**Comment by rrousselGit** [comment] 2023-01-09 11:52
I'll close this. I have no plan to fix the remaining bugs for the migration tool as it's been quite a while now since the breaking change happened.

**Closed by rrousselGit** 2023-01-09 11:52 UTC
Labels: bug, wontfix, migration tool
