### ISSUE TITLE
ref.listen doesn't work inside the build() method

### ISSUE THREAD

**Issue by maherjaafar** [rrousselGit/riverpod#2897] opened 2023-09-13 08:43 UTC
**ref.listen(...,) doesn't work inside the build() method**

When I declare a provider and use `ref.listen()` it doesn't work even if the widget is already built and the state of the provider is changed.

**To Reproduce**

**Doesn't work:**
```
    ref.listen(
      myProvider,
      (previous, next) {
        print('listened to the changes');
      },
    );
```

**Work:**

```
@riverpod
void myProviderListener(
  MyProviderListenerRef ref,
) {
  ref.listen<bool>(
    myProvider,
    (bool? previous, bool next) {
      logger.d('previous: $previous');
      logger.d('shouldAskForNotificationPermissionProvider: $next');
    },
    fireImmediately: true,
  );
}
```

Then I call the code below inside the build mehod:
`ref.read(myProviderListenerProvider);`

**Comment by rrousselGit** [comment] 2023-09-13 08:58
What does "doesn't work mean"?

Please share a full example. What you shared isn't enough to reproduce the issue

**Comment by rrousselGit** [comment] 2023-09-27 11:54
Closing due to the lack of a way to go forward on this issue.

If you still have the problem, please open a new issue with more description. I'd be more than happy to help :)

**Closed by rrousselGit** 2023-09-27 11:54 UTC
Labels: bug, question
