### ISSUE TITLE
Allow defining/overriding the name for the generated provider (and all helper types)

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/riverpod#3203] opened 2023-12-10 16:26 UTC
I wan my provider function to be private, but the generated provider to be public. (I don't want anybody try to call the function.) The generator derives the name of the provider and all of the generated helpers form the function name, so if it contains the `_` prefix (making it private to the library), the generated stuff also has it (and so is also private).

It would be nice to be able to configure the generator more to allow somehow help it decide about the names.

**Comment by rrousselGit** [comment] 2023-12-10 17:04
Duplicate of https://github.com/rrousselGit/riverpod/issues/2244

**Closed by rrousselGit** 2023-12-10 17:04 UTC
Labels: enhancement, needs triage
