### ISSUE TITLE
Only in release mode: Provider gets invalidated during build

### ISSUE THREAD

**Issue by derolf** [rrousselGit/riverpod#2941] opened 2023-10-01 21:52 UTC
# Description

In release mode (but not debug mode), I am seeing a `FutureProvider` being invalidated while its building, which results in the `FutureProvider` built twice and "weird" consequences.

While tracing down the bug, I found a difference in the behaviour between debug and release mode when a provider A watches B.

In debug mode:
* Flush B: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L726
* Add B as dependency: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L734
* Read B: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L739

In release mode, the first step is missing:
* Add B as dependency: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L734
* Read B: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L739

The results is that in debug mode, B is built BEFORE B is added as dependency to A. However, in release mode, B is added as dependency and the B is built (`readSelf -> flush -> _performBuild`), which results in B calling `_markDependencyChanged` on A.

I validated this behaviour by via some `_isBuilding` flag:

```
void invalidateSelf() {
    if (_isBuilding) {
      print("");
      print("XXX invalidateSelf ISBUILDING!!! $this");
      print(StackTrace.current.toString());
    }
...
```

```
  void buildState() {
...
      _isBuilding = true;
      try {
        create(didChangeDependency: previousDidChangeDependency);
      } finally {
        _isBuilding = false;
      }
...
```

When running the app in release mode, I see this log:

```
flutter: XXX invalidateSelf ISBUILDING!!! AutoDisposeFutureProviderElement<List<SearchResultItem>>(provider: AutoDisposeFutureProvider<List<SearchResultItem>>#988e5(Mode.idle()), origin: AutoDisposeFutureProvider<List<SearchResultItem>>#988e5(Mode.idle()))
flutter: #0      ProviderElementBase.invalidateSelf (package:riverpod/src/framework/element.dart:302)
#1      ProviderElementBase._markDependencyChanged (package:riverpod/src/framework/element.dart:636)
#2      ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:602)
#3      ProviderElementBase._performBuild (package:riverpod/src/framework/element.dart:401)
#4      ProviderElementBase.flush (package:riverpod/src/framework/element.dart:348)
#5      ProviderElementBase.readSelf (package:riverpod/src/framework/element.dart:841)
#6      ProviderElementBase.watch (package:riverpod/src/framework/element.dart:771)
#7      exploreResultProvider.<anonymous closure> (package:services/state/modes_providers.dart:260)
#8      AutoDisposeFamilyBase.call.<anonymous closure> (package:riverpod/src/framework/family.dart:196)
#9      AutoDisposeFutureProvider._create (package:riverpod/src/future_provider/auto_dispose.dart:44)
#10     FutureProviderElement.create.<anonymous closure> (package:riverpod/src/future_provider/base.dart:104)
```

# Repro

1. Comment out assertion to emulate release mode: https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/lib/src/framework/element.dart#L726

2. Run:

```
import "package:riverpod/riverpod.dart";

var unique = 0;

final B = Provider(
  (ref) {
    final value = unique++;
    print("Buidling B -> $value");
    return value;
  },
);

final A1 = Provider(
  (ref) {
    print("Buidling A1");
    ref.watch(B);
  },
);

final A2 = Provider(
  (ref) {
    print("Buidling A2");
    ref.watch(B);
  },
);

Future<void> main() async {
  final container = ProviderContainer();

  container.read(A1);
  container.read(A1);
  container.read(A1);
  print("");
  print("PUMP");
  await container.pump();
  print("");
  container.invalidate(B);
  container.read(A2);
  container.read(A2);
  container.read(A2);
  print("");
}
```

Output is:

```
Buidling A1
Buidling B -> 0

PUMP

Buidling A2
Buidling B -> 1
Buidling A2          <--- THIS SHOULD NOT HAPPEN
```

**Comment by rrousselGit** [comment] 2023-10-02 00:54
That's quite the unique bug. Thanks for the report, I'll investigate

**Comment by derolf** [comment] 2023-10-02 07:22
Took me a few hours to trace down. Btw. the result of this bug is that the first Future in such a double-build is outliving and might later resolve and set the state even if there was already a new Future. That’s how I found it.

**Comment by rrousselGit** [comment] 2023-10-02 07:29
You certainly didn't need to go that far :)

But looks like you effectively found the problem and got a text for it.
Do you want to make a PR to fix it?

It should be as simple as moving thar "flush" out of the assert

**Comment by derolf** [comment] 2023-10-02 08:59
What about just calling readSelf before adding the dependency?

**Comment by derolf** [comment] 2023-10-02 09:01
And btw why is “_container.readProviderElement(listenable);” already flushing/building in the other cases, but not here?

**Comment by rrousselGit** [comment] 2023-10-02 13:33
flush is the correct thing to call, not readSelf.

Calling flush was deemed unnecessary here because readSelf already does it. The debug mode does an extra one for assert purposes. Since it was thought to be needed only for asserts, for optimization it's done only in debug mode. But if that's necessary, we can decide to always do it.

Although to be honestly, this is going to be fixed anyway by a broader update on the flushing mechanism. https://github.com/rrousselGit/riverpod/issues/2041 is in a way related to flushing issues, and its fix is going to fix that too.

**Comment by derolf** [comment] 2023-10-02 14:15
Got that, but why is it ONLY invalidating twice in the given scenario?

**Comment by rrousselGit** [comment] 2023-10-02 15:02
"flush" doesn't necessarily triggers a rebuild. It only check if a build is needed (and if so, triggers it).

**Comment by derolf** [comment] 2023-10-02 15:04
Yes, I got that. But I am still wondering, why we not always see the invalidation problem, but only in the scenario above.

**Comment by Tomburgs** [comment] 2024-01-26 16:49
We are seeing this in production as well.

@derolf have you found a workaround for this issue?

**Comment by rrousselGit** [comment] 2024-01-26 17:55
This is getting fixed as part of 3.0

It's going to be hard to fix it in the 2.0 version.

**Comment by derolf** [comment] 2024-01-26 22:30
> We are seeing this in production as well.
> 
> 
> 
> @derolf have you found a workaround for this issue?

Yes, put a "ref.read(provider)" before "ref.watch(provider)" inside the FutureProvider's create.

**Comment by joachimbulow** [comment] 2024-02-09 12:19
Fyi have upgraded Flutter to `3.16.9`and XCode to `15.2`, and fyi we now also see this error in debug mode, running `Riverpod 3.0.0-dev.0. `

Were not so far able to fix using the `read` before the `watch` tho. Good thing is, it is not seemingly breaking functionality.

**Comment by rrousselGit** [comment] 2024-03-10 10:50
This was in fact a duplicate of the `_lastFuture` assert error.

Closing as this is now fixed :)

**Closed by rrousselGit** 2024-03-10 10:50 UTC
Labels: bug
