### ISSUE TITLE
Error: The getter 'createdType' isn't defined for the class 'ClassBasedProviderDeclaration'.

### ISSUE THREAD

**Issue by dbergan** [rrousselGit/riverpod#2943] opened 2023-10-02 14:46 UTC
Thank you for riverpod! It's been wonderful for me.

**Describe the bug**
I get the below errors when I run this command today.

`dart run build_runner watch -d`

I had no issues running this command 12 hours ago, which makes me think that a package update is at fault.

**Terminal output**

Building package executable... (8.1s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 468ms
[WARNING] ../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/class_based_provider.dart:101:33: Error: The getter 'createdType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
    final returnType = provider.createdType;
                                ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/class_based_provider.dart:115:66: Error: The getter 'valueType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
final $providerName = $providerType<${provider.name}, ${provider.valueType}>.internal(
                                                                 ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/class_based_provider.dart:123:61: Error: The getter 'valueType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
typedef $notifierTypedefName = $notifierBaseType<${provider.valueType}>;
                                                            ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:55:32: Error: The getter 'createdType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
    var createdType = provider.createdType.toString();
                               ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:57:33: Error: The getter 'createdType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
    final returnType = provider.createdType;
                                ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:65:44: Error: The getter 'valueType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
        createdType = 'FutureOr<${provider.valueType}>';
                                           ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:90:38: Error: The getter 'valueType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
      providerGenerics: '<${provider.valueType}>',
                                     ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:134:33: Error: The getter 'createdType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
    final returnType = provider.createdType;
                                ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:167:56: Error: The getter 'valueType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
      providerGenerics: '<${provider.name}, ${provider.valueType}>',
                                                       ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:172:74: Error: The getter 'valueType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
abstract class $notifierTypedefName extends $notifierBaseType<${provider.valueType}> {
                                                                         ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:175:14: Error: The getter 'createdType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
  ${provider.createdType} build($parameterDefinition);
             ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:180:14: Error: The getter 'createdType' isn't defined for the class 'ClassBasedProviderDeclaration'.
 - 'ClassBasedProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
  ${provider.createdType} runNotifierBuild(
             ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:248:45: Error: The getter 'exposedType' isn't defined for the class 'GeneratorProviderDeclaration'.
 - 'GeneratorProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'exposedType'.
class $familyName extends Family<${provider.exposedType}> {
                                            ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/family.dart:332:43: Error: The getter 'valueType' isn't defined for the class 'GeneratorProviderDeclaration'.
 - 'GeneratorProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
mixin $refNameImpl on $refType<${provider.valueType}> {
                                          ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/functional_provider.dart:38:33: Error: The getter 'createdType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'createdType'.
    final returnType = provider.createdType;
                                ^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/functional_provider.dart:61:48: Error: The getter 'valueType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
final $providerName = $providerType<${provider.valueType}>.internal(
                                               ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_generator-2.3.3/lib/src/templates/functional_provider.dart:69:50: Error: The getter 'valueType' isn't defined for the class 'FunctionalProviderDeclaration'.
 - 'FunctionalProviderDeclaration' is from 'package:riverpod_analyzer_utils/src/riverpod_ast.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/riverpod_analyzer_utils-0.3.5/lib/src/riverpod_ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueType'.
typedef $refName = ${providerType}Ref<${provider.valueType}>;
                                                 ^^^^^^^^^

[INFO] Precompiling build script... completed, took 1.3s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

**Comment by dbergan** [comment] 2023-10-02 15:00
When I specify `riverpod_analyzer_utils: 0.3.4` in pubspec.yaml, the error messages go away.

**Comment by rrousselGit** [comment] 2023-10-02 15:08
Looks like a breaking change landed in riverpod_analyzer_util with an incorrect version number bump.

I'll pull down the versions and fix this. Thanks for the report!

**Closed** 2023-10-02 15:09 UTC
Labels: bug, needs triage

**Comment by dbergan** [comment] 2023-10-02 15:12
Thanks for the quick fix!

**Comment by bitjunk** [comment] 2023-10-19 22:21
I am getting the same error with all the latest stable versions. Here is my pubspec 

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  flutter_riverpod: ^2.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.4
```

**Comment by Nicoeevee** [comment] 2023-10-20 07:00
> I am getting the same error with all the latest stable versions. Here is my pubspec
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^1.0.2
>   flutter_screenutil: ^5.9.0
>   dio: ^5.3.3
>   riverpod: ^2.4.4
>   riverpod_annotation: ^2.2.1
>   flutter_riverpod: ^2.4.4
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   flutter_lints: ^2.0.0
>   build_runner: ^2.4.6
>   riverpod_generator: ^2.3.4
> ```

Work for me
Flutter 3.13.8

```yaml
dependencies:
  # riverpod
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  custom_lint: ^0.5.3
  riverpod_generator: 2.3.3
  riverpod_lint: ^2.1.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1

```

**Comment by bitjunk** [comment] 2023-10-20 07:42
@Nicoeevee Yup that works for me too! The issue is with `riverpod_generator: 2.3.4` and  since you seem to use `2.3.3` it's working fine.

**Comment by apratim-arora** [comment] 2023-10-20 18:27
> Looks like a breaking change landed in riverpod_analyzer_util with an incorrect version number bump.
> 
> I'll pull down the versions and fix this. Thanks for the report!

I spent my last 2 days trying to fix the issue. But it has not been resolved from riverpod's side as of time of writing.
For now, way to go with riverpod_generator is to unpin riverpod_generator and riverpod_lint dependencies and use:
 riverpod_generator: 2.3.3
 riverpod_lint: 2.1.0
 As they are the latest combinations of last working versions.

**Comment by mz2** [comment] 2023-10-21 07:09
I am also seeing this with flutter_riverpod 2.3.4, 2.3.3 works around.
