### ISSUE TITLE
Read a "disposed" notifier

### ISSUE THREAD

**Issue by lwj1994** [rrousselGit/riverpod#3679] opened 2024-07-26 10:19 UTC
version：riverpod 2.5.1

**Describe the bug**
In A chatList page.
I sent a message to A, but it was delivered to B. After checking the logs, I discovered that while on A’s page, the notifier for B was retrieved. The probability is extremely low; I can’t reproduce it myself and can only determine it through the logs.

the log from production user: the msg's chatId is not match the page's chatId. 

Is it possible that there is a bug about `ref.read(_provider.notifier)`? help pls.

log:

```log
2024-07-26 15:27:27.413820-chat.sendMessage
: chatId:djE6cDJwOjM3OTA3NDkzODgzNDk5NDA0MDo2MzEwOTQwNzYzMzg1MjcwNjU=, userId:631094076338527065, text:Text(text: 111)

current page: /chat?chatId=djE6cDJwOjM3OTA3NDkzODgzNDk5NDA0MDo2Mjg3OTc0NTg1NDExNjgxMDk=
stacks: AppMainRoute -> ChatRoute
```

this its some code;
```dart
// provider 
final chatProvider =
    StateNotifierProvider.autoDispose.family<ChatListViewModel, ChatListState, String>((ref) {
  return ChatListViewModel(ChatListState(loadingState: Async.initializing()));
});


class ChatViewModel extends StateNotifier<ChatState>{ }


class ChatPageState extends  ConsumerState{
  ChatState get _state => ref.read(_provider);
  final _provider = chatProvider(chatId);
  ChatViewModel get _viewModel => ref.read(_provider.notifier);


  sendMsg(String inputText){
    // bug the _viewModel is not match with _provider
    final send = await _viewModel.sendText(inputText);
  }
}

```

![QQ20240726-180624](https://github.com/user-attachments/assets/60a04fd4-af50-46a6-89a7-48675e16cc4f)

**Comment by rrousselGit** [comment] 2024-07-26 10:33
Hello!

There's no way for me to know what's happening due to the lack of information.
But my guess is that you used providers after the widget was unmounted.

Without any extra information, I can't do anything though. So unless you give me a mininal reproducible example, I'll likely close this

**Comment by lwj1994** [comment] 2024-07-26 18:09
finally i found this can avoid the case: __get viewModel only once in `initState`__  instead of `ChatViewModel get _viewModel => ref.read(_provider.notifier);` every time. 

```dart
class _ChatPage extends BasePageState<ChatPage> {
  late ChatViewModel _viewModel;

  @override
  void initState() {
    super.initState();
    _viewModel = ref.read(_provider.notifier);
  }
}
```

**Closed** 2024-07-29 08:32 UTC
Labels: bug, question
