### ISSUE TITLE
Bad state: No ProviderScope found

### ISSUE THREAD

**Issue by Apach3Q** [rrousselGit/riverpod#2684] opened 2023-06-28 10:03 UTC
Bad state: No ProviderScope found
I add ProviderScope to the main() function, like this:
```
runApp(
  UncontrolledProviderScope(
    container: Providers.instance.providerContainer,
    child: const MyApp(),
  ),
);
```

However, when using it, it suddenly throws an error: 'Bad state: No ProviderScope found', and I cannot reproduce it. This was seen as a crash on Firebase.

I used flutter_riverpod 2.3.6.

**Comment by rrousselGit** [comment] 2023-06-28 11:07
If you can't reproduce it with your full application, I can't either with only a few lines ;)

**Comment by ggirotto** [comment] 2023-07-22 01:15
I'm facing the same issue, crashes on the analytics tool but I couldn't create a reproducible example yet. This is happening with very few users, so it may happen under very specific circumstances

**Comment by rrousselGit** [comment] 2023-07-22 07:57
Closing as I have no means to reproduce this issue.

If you have this problem, please open a new issue with a steps to reproduce the problem.

**Closed by rrousselGit** 2023-07-22 07:57 UTC
Labels: bug, question

**Comment by Apach3Q** [comment] 2023-07-25 00:59
> I'm facing the same issue, crashes on the analytics tool but I couldn't create a reproducible example yet. This is happening with very few users, so it may happen under very specific circumstances

Yes, I can't reproduce it either. The issue seems to arise when there are many providers of the same class with different family distinctions. However, I'm not sure and it's really frustrating me.

**Comment by ggirotto** [comment] 2023-07-25 01:02
I don't think this is related with the family distinction, since I'm experiencing with providers that are not families. I started to investigate this weekend but didn't find anything interesting yet

**Comment by Apach3Q** [comment] 2023-07-25 01:40
The strange thing is that even though my app is already wrapped in ProviderScope, I still encounter the error "Bad state: No ProviderScope found". 
I think many users may encounter this issue, so it shouldn't be closed. We should all work together to follow up on the problem and find ways to reproduce and solve it.

**Comment by rrousselGit** [comment] 2023-07-25 08:48
I don't think many people are facing this, no.
Unless you find a way to reproduce this issue, there's nothing actable on my side, so closing it makes sense.

It's very unlikely to be a Riverpod bug. If you _did_ wrap your app in a ProviderScope, there's no way for that error to happen.

Maybe you didn't wrap it correctly. For example, maybe you're using `runApp` in different places, and one of those places doesn't use ProviderScope.
Or maybe you placed ProviderScope inside MyApp instead of above everything

**Comment by ggirotto** [comment] 2023-07-25 12:18
About the issue, I don't think it should be opened without a reproducible example, since we would be just creating theories about why the issue is happening, and we are not sure yet if this is related with Riverpod.

About the root cause of the issue, I'm not sure yet, but it's not related with bad wrapping of the app root `ProviderScope`. In my case, we have around 30k active users monthly, and this issue happens with around 20/month. I know that the percentage of affected is almost none, but I'm very curious about how is this happening.

I strongly believe that this issue is intermittent and based on a specific context of the application, since it's happening in some places of my codebase that, if it wasn't, all users should be experiencing the same problem. I'm still investigating what could be causing this issue, but since I can't reproduce it's very hard to find. As soon as I have any new information I post here.

**Comment by GP4cK** [comment] 2023-08-04 08:18
I've only managed to reproduce this issue on a real device and it seemed to be related a call in an initState to

```dart
SystemChrome.setPreferredOrientations([
  DeviceOrientation.landscapeRight,
  DeviceOrientation.landscapeLeft,
]);
```

Like what is suggested in the comment above, for some reason I can't explain, the widget that was calling `ref.read` was disposed.
After removing the call to `SystemChrome.setPreferredOrientations`, I couldn't reproduce the issue despite many tries.

I'm leaving some details below. Hopefully it may help someone:

<details>
<summary>More details</summary>

I have a provider like this:

```dart
final myStateProvider = StateProvider.family.autoDispose<MyState?, String>(
  (ref, id) => ref.watch(anotherProvider(id)).valueOrNull,
  dependencies: [anotherProvider],
);
```

Then, on a screen, I have a widget with an onChange like this:

```dart
class MyScreen extends ConsumerWidget {
  // ...
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // This widget is inside a SliverList
    MyInputWidget(
      onChanged: (value) => ref.read(myStateProvider(id).notifier).updateValue(value),
    )
  }
}
```

The `MyInputWidget` is a GestureDetector that will push a new screen, wait for its result and call the onChanged like so:

```dart
class MyInputWidget extends StatelessWidget {
  final ValueChanged<Value> onChanged;

  Future<void> _onTap(BuildContext context) async {
    final value = await Navigator.of(context).push<Value>(
      MaterialPageRoute(
        builder: (context) => ScreenThatRotatesThePhone(),
      ),
    );

    if (value != null) onChanged(returnedSignature);
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () async => _onTap(context),
      child: child,
    );
  }
}
```

`ScreenThatRotatesThePhone` is a stateful widget with the call to `SystemChrome.setPreferredOrientations` in its initState.
</details>

**Comment by carpentierchloe** [comment] 2023-09-12 15:34
I am also having this issue many times, very randomly for my users in production and without using Stateful widget.

**Comment by thachhoang1909** [comment] 2023-10-30 09:03
From my firebase analystic, this error happens to many users. My case, the ref called is put inside a async server call. 
```
Future<void> task() async {
    await servercall();
    ref.read(someProvider.notifier).func();
}
```

**Comment by ggirotto** [comment] 2023-10-30 12:26
All the occurrences that I've seen in the project are in async callbacks and all of them were fixed by checking if the widget is mounted. If you are in a stateful consumer widget, you may just do

```dart
final result = await asyncCall();
if (mounted) ref.read(...)
```

or just use `useIsMounted` hook for stateless widgets

```dart
final mounted = useIsMounted();
final result = await asyncCall();
if (mounted()) ref.read(...)
```

**Comment by rrousselGit** [comment] 2023-10-30 12:56
I've mentioned this in the docs https://riverpod.dev/docs/essentials/faq#i-have-the-error-cannot-use-ref-after-the-widget-was-disposed-whats-wrong
