### ISSUE TITLE
`setState() or markNeedsBuild() called during build.` when using `ProviderScope(parent:` to share scoped providers with modals

### ISSUE THREAD

**Issue by js2702** [rrousselGit/riverpod#3261] opened 2024-01-08 11:36 UTC
**Describe the bug**
We've recently encountered an issue after updating to 2.4.8. 

We have a ChangeNotifier scoped which was working fine in 2.4.7. When we updated we found this issue, here is the stack trace from the provided example. From our app the stack trace is a bit different as in the part that says:

```
The widget on which setState() or markNeedsBuild() was called was:
  CounterBlock
The widget which was currently being built when the offending call was made was:
  DialogContent

```

We have: 

```
The widget on which setState() or markNeedsBuild() was called was:
 _BottomSheetDialog
The widget which was currently being built when the offending call was made was:
UncontrolledProviderScope
```

Hopefully they are the same issue as it's replicated with a very similar architecture.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This CounterBlock widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  CounterBlock
The widget which was currently being built when the offending call was made was:
  DialogContent
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5033:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5045:6)
#2      ConsumerStatefulElement.watch.<anonymous closure>.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:569:20)
#3      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#4      ProviderElementBase._notifyListeners.<anonymous closure> (package:riverpod/src/framework/element.dart:537:24)
#5      ResultData.map (package:riverpod/src/result.dart:74:16)
#6      ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:534:14)
#7      ProviderElementBase._performBuild (package:riverpod/src/framework/element.dart:374:7)
#8      ProviderElementBase.flush (package:riverpod/src/framework/element.dart:325:7)
#9      ProviderElementBase.readSelf (package:riverpod/src/framework/element.dart:809:5)
#10     _ExternalProviderSubscription.read (package:riverpod/src/framework/provider_base.dart:179:29)
#11     ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:571:8)
#12     DialogContent.build (package:riverpod_bug/main.dart:97:33)
#13     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:479:19)
#14     StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#15     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:542:20)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)

```

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final currentCounterIdProvider = Provider<String>((ref) => throw UnimplementedError());

final counterProvider = StateProvider.autoDispose<int>((ref) => 0, dependencies: [currentCounterIdProvider]);

final multiplyFamilyProvider = Provider.family.autoDispose<int, int>(
  (ref, multiplier) => ref.watch(counterProvider) * multiplier,
  dependencies: [counterProvider],
);

void main() {
  runApp(const ProviderScope(child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}


class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Column(
        children: [
          ProviderScope(
            overrides: [currentCounterIdProvider.overrideWithValue("A")],
            child: CounterBlock(),
          ),
          ProviderScope(
            overrides: [currentCounterIdProvider.overrideWithValue("B")],
            child: CounterBlock(),
          )
        ],
      ),
    );
  }
}

class CounterBlock extends ConsumerWidget {
  const CounterBlock({super.key});

  @override
  Widget build(BuildContext context, ref) {
    final counterId = ref.watch(currentCounterIdProvider);
    final counterValue = ref.watch(counterProvider);
    final multipliedValue = ref.watch(multiplyFamilyProvider(2));
    return Column(
      children: [
        Text("Counter $counterId: currentValue: $counterValue"),
        Text("Multiplied value $multipliedValue"),
        ElevatedButton(
          onPressed: () {
            openDialog(context, counterId);
          },
          child: Text("Open dialog"),
        )
      ],
    );
  }

  void openDialog(BuildContext parentContext, String counterId) {
    showDialog(
      context: parentContext,
      builder: (context) => ProviderScope(parent: ProviderScope.containerOf(parentContext), child: DialogContent()),
    );
  }
}

class DialogContent extends ConsumerWidget {
  const DialogContent({super.key});

  @override
  Widget build(BuildContext context, ref) {
    final counterValue = ref.watch(counterProvider);
    final multipliedValue = ref.watch(multiplyFamilyProvider(2));
    return AlertDialog(
      title: Text("Counter $counterValue"),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text("Multiplied value ${multipliedValue.toString()}"),
          ElevatedButton(
            onPressed: () {
              ref.read(counterProvider.notifier).state++;
            },
            child: Text("Increment"),
          ),
        ],
      ),
    );
  }
}
```

**Comment by davidmartos96** [comment] 2024-01-23 15:39
Any update on this? 
Is the error expected due to an invalid usage of Riverpod or is it a valid bug?

**Comment by mcastro-rpp** [comment] 2024-02-02 19:51
We have the same issue with a similar setup; we use `showModalBottomSheet`. Here's our minimum code to reproduce:

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

final overridenProvider = Provider<String>((ref) => throw UnimplementedError());

final futureProvider = FutureProvider<bool>(
  (ref) => Future<bool>.delayed(const Duration(seconds: 2), () => true),
);

final infoProvider = Provider<String>(
  (ref) {
    final overriden = ref.watch(overridenProvider);
    final asyncBool = ref.watch(futureProvider);

    return asyncBool.maybeWhen(
      orElse: () => 'orElse: $overriden',
      data: (data) => 'data: $overriden + $data',
    );
  },
  dependencies: [overridenProvider],
);

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const ProviderScope(child: MaterialApp(home: Screen())));
}

class Screen extends StatelessWidget {
  const Screen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        body: ProviderScope(
          overrides: [overridenProvider.overrideWithValue('value')],
          child: const ScaffoldContent(),
        ),
      );
}

class ScaffoldContent extends StatelessWidget {
  const ScaffoldContent({super.key});

  @override
  Widget build(BuildContext context) => Center(
        child: ElevatedButton(
          onPressed: () {
            showModalBottomSheet<void>(
              context: context,
              builder: (_) => ProviderScope(
                parent: ProviderScope.containerOf(context),
                child: const ModalContent(),
              ),
            );
          },
          child: const Text('Test'),
        ),
      );
}

class ModalContent extends ConsumerWidget {
  const ModalContent({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final info = ref.watch(infoProvider);

    return SafeArea(child: Text(info));
  }
}
```

Error is thrown consistently in the debug console, not in the first build of `ModalContent` but when `futureProvider` returns a new value after the 2 second delay. Once it happens, the ui doesn't reflect the new state.

Version 2.4.7 works fine for us as well and error persists in 2.4.9. Hope this is of any help.

**Comment by PROGrand** [comment] 2024-02-06 09:37
@mcastro-rpp

Changing from:
```dart
ProviderScope.containerOf(context)
```
to:
```dart
ProviderScope.containerOf(context, listen: false)
```
solves problem. Also I have to add `listen: false` to all overlay launchers like `showDialog`, drawers etc.

Still need explanation or fix for this...

**Comment by rrousselGit** [comment] 2024-03-01 16:57
Note that nowadays, you don't necessarily need `ProviderScope(parent:` for modals.

Some time ago, `Overlay` was updated to allow adding overlays in a route, yet render them in a different route.
This allows overlays (such as modals) to use the content from the route that pushed them.

This is similar to a project I made a while ago: [flutter_portal](https://pub.dev/packages/flutter_portal)


That might be the actual solution to our problem. Rather than using `parent:`, we could change how we display our modals :)

**Comment by rrousselGit** [comment] 2024-03-09 12:30
Flagging `ProviderScope.parent` as deprecated and removing it in 3.0.0.  
For now I cannot think of a good solution to this problem. Keeping a massively broken API  doesn't make sense.

I'll keep thinking about a good solution to this and possibly reintroduce the API in the future.

**Closed by rrousselGit** 2024-03-09 12:30 UTC
Labels: bug

**Comment by AhmedLSayed9** [comment] 2024-03-10 17:07
Is it safe to use `UncontrolledProviderScope` for modals if we don't share scoped providers using `overrideWithValue`?

**Comment by rrousselGit** [comment] 2024-03-10 17:45
No the problem doesn't change whether we use `ProviderScope(parent:` or `UncontrollerProviderScope`.
The issue is about having a ProivderContainer from one part of the widget tree inserted into another part of the widget tree.

**Comment by justincbeck** [comment] 2024-03-11 16:43
@rrousselGit - I need access to the `ref` in my `main.dart` file. I have a different `main.dart` file for each environment and I hold the environment in a provider. So in each of the different `main.dart` files, I set the environment name.

For example, in my `develop` file I do this:
```
final providerScope = ProviderScope(
  parent: ProviderContainer(overrides: []),
  child: const MainClass(),
);

providerScope.parent!.read(environmentProvider.notifier).update((state) => 'develop');
```
...then else where in the app, when I request environment variables, it knows to use the variables specific to the `develop` environment.

With the `parent` attribute being deprecated, what is my best approach for gaining access to the `ref` so that I can do that I need?

**Comment by AhmedLSayed9** [comment] 2024-03-11 16:50
@justincbeck 

Remi mentioned that using `UncontrollerProviderScope` in main is fine, but in your case, I'd use basic `Provider<String>` that just throws in the build and override it:
```
ProviderScope(
overrides: [
        environmentProvider.overrideWith((ref) => 'develop'),
```

**Comment by justincbeck** [comment] 2024-03-11 16:52
> @justincbeck
> 
> Remi mentioned that using `UncontrollerProviderScope` in main is fine, but in your case, I'd use basic `Provider<String>` that just throws in the build and override it:
> 
> ```
> ProviderScope(
> overrides: [
>         environmentProvider.overrideWith((ref) => 'develop'),
> ```

Oh, interesting... Huh, let me play around with that. That's a good idea.

**Comment by justincbeck** [comment] 2024-03-11 16:55
> @rrousselGit Should using `ProviderScope(parent:` just in the main trigger the issue?

I've been doing that for a while without seeing this issue. But your method is way better.

**Comment by AhmedLSayed9** [comment] 2024-03-11 17:09
> I've been doing that for a while without seeing this issue. But your method is way better.

I need it for other things (warming-up services and stuff).

The thing is I got the issue when using `ProviderScope(parent:` in the main "just in the main", without sharing ProviderContainer in different parts of the widget tree.

**Comment by justincbeck** [comment] 2024-03-11 17:11
@AhmedLSayed9 - I imagine you've thought it through already, but can you not take the approach you suggested to me?

**Comment by AhmedLSayed9** [comment] 2024-03-11 17:26
> @AhmedLSayed9 - I imagine you've thought it through already, but can you not take the approach you suggested to me?

For async providers, no. You better warm-up them in a startup widget to offer error handling.

`UncontrolledProviderScope` works fine for me but I'm just skeptical about if the issue is about sharing ProviderContainer in different parts of the widget tree or not.

**Comment by rrousselGit** [comment] 2024-03-11 20:26
> Should using ProviderScope(parent: just in the main trigger the issue?

In the main it should be alright, but why have this parameter to only allow it in the`main` when `UncontrolledProviderScope` is here

**Comment by AhmedLSayed9** [comment] 2024-03-11 20:36
> In the main it should be alright

It triggered the same issue when only used in the `main`, should I create a sample that reproduces it?

> but why have this parameter to only allow it in the`main` when `UncontrolledProviderScope` is here

IIRC `parent` was encouraged over `UncontrolledProviderScope`

**Comment by rrousselGit** [comment] 2024-03-12 12:28
> It triggered the same issue when only used in the main, should I create a sample that reproduces it?

Sure

> IIRC parent was encouraged over UncontrolledProviderScope

ProviderScope is encouraged over UncontrolledProviderScope, not `parent`

**Comment by Reprevise** [comment] 2024-03-12 19:42
@rrousselGit 

> Some time ago, Overlay was updated to allow adding overlays in a route, yet render them in a different route.
This allows overlays (such as modals) to use the content from the route that pushed them.

Are you talking about [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html)? If so, I'm not sure that's a good enough solution, it's definitely not as easy as using `showDialog()` Right now, the `parent` parameter is crucial to my modals so that I don't have to pass in the state of my app to each of them.

**Comment by rrousselGit** [comment] 2024-03-12 20:08
Yes, OverlayPortal.

You may find it inconvenient, but it has been build for this very purpose.

**Comment by FaFre** [comment] 2024-03-13 10:48
I use the `parent` like this at the moment:

```dart
await showDialog<Location>(
  context: context,
  builder: (dialogContext) => ProviderScope(
    parent: ProviderScope.containerOf(context),
    overrides: [
      scopedMapSearchProvider.overrideWith(() => ScopedMapSearch()),
    ],
    child: _LocationPickDialog(property),
  ),
)
```

What will be an appropriate replacement after deprecation of `parent` for this scenario?

**Comment by rrousselGit** [comment] 2024-03-13 11:55
What's the use of `parent` in your case here?

**Comment by FaFre** [comment] 2024-03-13 14:53
@rrousselGit previously my overridden providers lost there state. I figured it was necessary to set the parent.

**Comment by rrousselGit** [comment] 2024-03-13 15:02
Depends on where the override is.

If you are scoping a value and using `parent` to pass it to modals, you'll have to manually pass the values to modals somehow.
But ideally your value should not be scoped. In which case, it would naturally be available in modals.

So either refactor it to not use scoping, or manually pass things around

**Comment by itsJoKr** [comment] 2024-03-18 19:24
Overlays and overrides to the side, how do we do something like this without `parent` now?

```dart
    ProviderContainer container = ProviderContainer();
    await container.read(sharedPrefsRepositoryProvider).init();
    final isFirstRun = await container.read(sharedPrefsRepositoryProvider).isFirstRun();

    runApp(
      ProviderScope(
        parent: container,
        child: MyApp(),
      ),
    );
```

**Comment by rrousselGit** [comment] 2024-03-18 19:26
UncontrolledProviderScope, or follow the initialization doc https://riverpod.dev/docs/essentials/eager_initialization

**Comment by tofylion** [comment] 2024-03-26 20:47
@rrousselGit I have another use case where parent is kinda needed. I'm using FCM, so the handlers are callbacks that only take the FCM message. The handlers need to be run before `runApp`, so I can't access providers. My workaround was to use a container so I can access the same providers from the message handlers. What do you suggest I do now?

**Comment by rrousselGit** [comment] 2024-04-02 14:29
The migration is unclear tbh.

For now my suggestion would be to try and refactor your `showDialogs` to the now OverlayPortal.

**Comment by rrousselGit** [comment] 2024-04-03 11:42
flutter_portal wasn't stable. OverlayPortal is.

**Comment by rrousselGit** [comment] 2024-04-03 16:55
There's a controller, so that is kind of like a "show".

**Comment by rrousselGit** [comment] 2024-04-03 19:37
It's not a straightforward migration, sure.

But that's probably the most "long term" one.

**Comment by davidmartos96** [comment] 2024-05-28 08:17
@rrousselGit As stated, this is quite a difficult migration because the Overlay solutions currently lack some functionality like focus that Navigator does by default.
Because the problem lies in the order the widgets are built, would there be some workaround where the pushed ProviderContainer listens one frame behind? There could be use cases where that lag is acceptable.

**Comment by AradhyaNepal** [comment] 2024-06-07 15:34
I can't understand everything what said in the discussion, but after the migration one of my way to use provider in the places where ref is too hard to pass on constructor will not work after the deprecation. What are the migration procedure? 


**Setup:**

```
  runApp(
    ProviderScope(
      parent: MyApp.globalRef,
      child: const MyApp(),
  );
  
  
  
class MyApp extends StatefulWidget {
  static final navKey = GlobalKey<NavigatorState>();

------------------
}
```


**Usage**
if(MyApp.globalRef.read(someProvider)){

} 

In places where its hard to pass ref in constructor.

This way was like shortcut to me.

**Comment by rrousselGit** [comment] 2024-06-09 15:43
> Because the problem lies in the order the widgets are built, would there be some workaround where the pushed ProviderContainer listens one frame behind? There could be use cases where that lag is acceptable.

That's not a solution I'm willing to add in Riverpod itself.
If it's in Riverpod, it should be a reliable solution. 

>  As stated, this is quite a difficult migration because the Overlay solutions currently lack some functionality like focus that Navigator does by default.

It may be harder, but it is doable.
This is just a matter of time. Flutter keeps evolving.

Ultimately this issue an issue unique to Riverpod. It's just that Riverpod tried to offer a solution, and it ended up not working well.

**Comment by FaFre** [comment] 2024-06-16 04:16
Is there a new way for `showModalBottomSheet` as well? Using the `bottomSheet` property of `Scaffold` is a pain.

**Comment by ashiq-mvp** [comment] 2024-10-31 06:44
@rrousselGit 

Hello, I have been using the parent: providerContainer approach to update the provider state within the onResponse method of my Dio interceptor, specifically with the call providerContainer.read(userProvider).updateUser(user). However, since the parent parameter is set to be deprecated, what alternative solutions can I use to achieve the same functionality?

**Comment by ValeriusGC** [comment] 2024-11-27 06:56
> @rrousselGit I have another use case where parent is kinda needed. I'm using FCM, so the handlers are callbacks that only take the FCM message. The handlers need to be run before `runApp`, so I can't access providers. My workaround was to use a container so I can access the same providers from the message handlers. What do you suggest I do now?

Hi there! Have you managed to solve this one?

**Comment by mikeborodin** [comment] 2025-01-19 20:25
My use case was also about running initialization code, but I found an alternative with `widgetsBinding. deferFirstFrame /  allowFirstFrame();` 👍

**Comment by JulienElkaim** [comment] 2025-01-28 22:58
Hi, I also use parent so I can do initialization in `main()` before starting the widget tree (I then pass the ProviderContainer to the widget tree, so I make sure the same instance of my provider used during initialization is passed)

@mikeborodin  can you explain how you use these methods? You end up doing initialization in the first widget anyway right?
@rrousselGit do you have an "official" / preferred alternative to replace the usage of `parent:` for init scenario

**Comment by mikeborodin** [comment] 2025-01-29 05:16
Sure @JulienElkaim 

My case is pretty simple, I used to show 2 splash screens where one is native and one is in Flutter.
This is worse ux cause you see this jumping so I call
`WidgetsFluttetBinding.deferFirstFrame();` from the main function before runApp.

The app has initial route set to splash but it does not matter what's exactly there, can be also SizedBox, the user does not see that.

Then there's a call to a function that does the asynchronous loading which is started from useEffect in App, it will navigate to the next route and finally, allow flutter to draw now by calling `WidgetsFluttetBinding.allowFirstFrame()`

https://api.flutter.dev/flutter/rendering/RendererBinding/allowFirstFrame.html

**Comment by OmarBakry-eg** [comment] 2025-02-17 16:41
@ashiq-mvp 
I have the same concept and looking for new solutions at the moment.
