### ISSUE TITLE
Consider doing a configurable replace on generated providers

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#3130] opened 2023-11-17 22:40 UTC
**Is your feature request related to a problem? Please describe.**
Often times, when creating a class provider, you may want to have `somethingProvider`.

To do this, you would have to name the class `Something`

However, what if the state of your class is also called `Something`?

You could rename the notifier, but then the resulting provider would no longer be called `somethingProvider`

**Describe the solution you'd like**

Consider stripping `Notifier` from class names to allow the distinction

Perhaps that could be an option in `@Riverpod()`? (probably opt-in? perhaps add a global option to change the default?)

Perhaps even a manual rename parameter to specify the exact resulting name?

**Describe alternatives you've considered**
Simply aliasing the incorrectly named generated provider
`final somethingProvider = somethingNotifierProvider;`
This has the caveat of breaking `riverpod_lints` unless you apply the `@ProviderFor(...)` internal annotation yourself

**Additional context**
```dart
class Data {}
// we want: dataProvider
// what's generated: dataNotifierProvider
// we are forced to:
final dataProvider = dataNotifierProvider; // breaks lints unless we add @ProviderFor(DataNotifier)
@riverpod
class DataNotifier extends _$DataNotifier {
  Data build() => Data();
 ...
}
```

**Comment by rrousselGit** [comment] 2023-11-20 11:14
Possible duplicate of https://github.com/rrousselGit/riverpod/issues/2244

**Comment by rrousselGit** [comment] 2024-03-01 10:58
Closing in favour of https://github.com/rrousselGit/riverpod/issues/2244

**Closed by rrousselGit** 2024-03-01 10:58 UTC
Labels: enhancement
