### ISSUE TITLE
Missing when `mounted` is to be used in case of `async` + provider rebuild

### ISSUE THREAD

**Issue by mpszczolinski** [rrousselGit/riverpod#1908] opened 2022-11-15 06:25 UTC
**Describe what scenario you think is uncovered by the existing examples/articles**
Documentation is missing examples/description/usecase when `mounted` is to be used in case of `async` + provider rebuild.

**Describe why existing examples/articles do not cover this case**
The entire riverpod.dev page is missing any example with `mounted` case.

**Additional context**
A StateNotifier might rebuild when watching other provider, e.g.:

```
final providerThatMayRebuild = StateProvider.family<SomeStateController, AsyncValue<SomeState>, int>((ref, id) {
  final selectedFilter = ref.watch(filterProvider);
  final repo = ref.watch(repositoryProvider);

  return SomeStateController(
    id: id,
    filter: selectedFilter,
    repository: repo,
  );
});

class SomeStateController extends StateNotifier<AsyncValue<SomeState>> {
  final int id;
  final int filter;
  final MyRepo repository;

  SomeStateController(this.id, this.filter, this.repository)
      : super(const AsyncLoading()) {
    init();
  }

  Future<void> init() async {
    state = const AsyncLoading();

    final either = await repository.getSomething(id, filter);
    either.fold(
      (l) => state = const AsyncError('some error', StackTrace.empty),
      (r) {
        if (mounted) { 
          state = AsyncData(r); // without "if(mounted)" it was throwing Bad state exception here
        }
      },
    );
  }
}
```

As you can see, `providerThatMayRebuild` rebuild every time when `selectedFilter` changes.
If there is pending `await repository.getSomething(id, filter)` operation, and new `SomeStateController` instance is created, then the previous one is disposed, and `state = AsyncData(r)` will throw `Bad state` exception.

I've found in StackOverflow, that a solution for that is to check `if(mounted)` however Riverpod documentation is missing how to handle cases when StateNotifier is disposed while there's an async operation in progress.

**Alternatively** documentation is silent whether rebuild of `StateNotifier` is a good/bad practice at all, or how to do it to avoid `Bad state` exception

**Comment by rrousselGit** [comment] 2022-11-15 09:28
Duplicate of https://github.com/rrousselGit/riverpod/issues/1879

**Comment by rrousselGit** [comment] 2022-11-15 09:28
Oh wait no, I confused the issues. My bad

**Comment by rrousselGit** [comment] 2022-11-15 09:31
I don't really recommend using `mounted` anyway.    `mounted` is not even present in the new `Notifier` syntax

I'd suggest canceling whatever async operation you have on dispose, instead of checking mounted.
There are already some docs about this, with plans to include more.

https://riverpod.dev/docs/concepts/modifiers/auto_dispose/#example-canceling-http-requests-when-no-longer-used


Since this is already in the issue triaging the list of things to cover, I'll close this

**Closed by rrousselGit** 2022-11-15 09:31 UTC
Labels: documentation, needs triage

**Comment by mpszczolinski** [comment] 2022-11-17 06:13
Hi @rrousselGit,
Thank for your answer. Kindly consider following case:

In my case my **async** operation was against `sqflite` database.

Sqflite is pretty popular solution and it is missing `cancel` option, e.g.:
`Future<int> delete(String table, {String? where, List<Object?>? whereArgs});`
or
```
Future<List<Map<String, Object?>>> query(String table,
      {bool? distinct,
      List<String>? columns,
      String? where,
      List<Object?>? whereArgs,
      String? groupBy,
      String? having,
      String? orderBy,
      int? limit,
      int? offset});
```

What would you suggest in this case?
