### ISSUE TITLE
Pause providers if listened only by paused providers

### ISSUE THREAD

**Issue by Wishmater** [rrousselGit/riverpod#1360] opened 2022-04-14 14:48 UTC
With the new features in 2.0, an AutoDispose provider can be kept alive after all listeners are removed, by setting chacheTime/disposeDelay. In this state, if a dependency of said provider is refreshed, this provider will also immediately refresh, even though it currently has no listeners, so the data it provides is not required at the moment. It is even possible that the cacheTime will run out without it ever being listened, so this calculation was completely unnecessary.

Proposed solution: for AutoDispose providers that have no listeners, but are being kept alive by chacheTime/disposeDelay; when a dependency refreshes, the provider should be invalidated, instead of refreshing immediately. This way the refresh will only be performed when a new listener appears, which is when the data will actually be required.

There might be cases when the immediate refresh is desired, so maybe an option can be added. I think for most cases, it will be better for performance to wait until the data is actually needed to refresh the provider. This is specially true for my specific case, where several providers that make heavy API calls are refreshed at the same time, causing network issues and hurting performance.

**Comment by rrousselGit** [comment] 2022-04-14 15:01
That shouldn't be the case to begin with. Sounds like a regression due to the `keepAlive` change

I'll look into it

**Comment by rrousselGit** [comment] 2022-04-21 06:56
I'm unable to reproduce it.  Could you share an example where this happens?

**Comment by Wishmater** [comment] 2022-04-22 12:52
Ok, so this is more complicated than I thought, sorry.

In my app, there is second provider watching the first one, which causes them both to be refreshed, because I assume a second provider watching it counts as a listener. If you modify your test like this, then it fails:

```
      final container = createContainer();
      final dep = StateProvider((ref) => 0);
      var buildCount = 0;
      final provider = Provider.autoDispose((ref) {
        buildCount++;
        ref.watch(dep);
        ref.keepAlive();
      }, cacheTime: const Duration(seconds: 5));
      final secondProvider = Provider.autoDispose((ref) {
        ref.watch(provider);
      });

      expect(buildCount, 0);
      container.read(secondProvider);
      expect(buildCount, 1);

      container.read(dep.notifier).state++;
      await container.pump();

      expect(buildCount, 1);
      container.read(provider);
      expect(buildCount, 2);
```

It looks like when there are two providers and one watches the other like this, they will both be immediately refreshed when a dependency changes, even if they have no other listeners, which is not necessary.

Proposal:  If the only listener(s) on a provider is another paused provider(s), the first provider should also be paused (like if it had no listeners).

I don't know if this is even possible, but it would be really useful. Thanks for your attention.

**Comment by rrousselGit** [comment] 2022-04-23 06:18
Hum I see. That sounds reasonable. I'll see if something can be done

**Comment by rrousselGit** [comment] 2022-05-09 14:04
I'll close this in favor of #1377

That issue will fix this

**Closed by rrousselGit** 2022-05-09 14:04 UTC
Labels: enhancement
