### ISSUE TITLE
[riverpod_generator] Add the ability to change the generated Provider's name

### ISSUE THREAD

**Issue by NicoGorr** [rrousselGit/riverpod#3224] opened 2023-12-16 18:36 UTC
# Is your feature request related to a problem? Please describe.
Most of the time I work with `riverpod_generator`, I struggle to find a consistent naming system according to the current `riverpod_generator` implementation.

Let's go straight to 2 fast examples.

### Example 1
Sometimes I would like to name the `Provider's class/function` and the `model` the same

```dart
[Filename: user.dart]

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    required int id,
    @Default('User') String displayName, 
  }) = _User;
}

@riverpod
class UserState extends _$UserState {
  @override
  User build() => // ...
  
  void changeName(String name) =>
    state = state.copyWith(displayName: name);
  
  // ...
}

/* ---------------------------------- */

[Filename: my_app.dart]

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'user.dart';

class MyApp extends ConsumerWidget {
  // ...
 
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final anotherUser = User(id: 4);

    // ...
  
    return MaterialApp(
      // ...
      home: MyScreen(
        user: ref.watch(userStateProvider);
        onNameChanged: (name) => ref.read(userStateProvider.notifier).changeName(name),
      ),
      // ...
    );
  }
}
```

**Problem:** I have to rename the Provider's class to something else (`UserState` in this case), creating a `userStateProvider` instead of the desired `userProvider`

### Example 2
In this example I would like to use `ThemeMode` inside a Provider in order to dynamically change the app theme mode (system/light/dark).

```dart
[Filename: theme_states.dart]

import 'package:flutter/material.dart' as material;
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'theme_states.g.dart';

@riverpod
class ThemeMode extends _$ThemeMode {
  @override
  material.ThemeMode build() => material.ThemeMode.system;
 
  void set(material.ThemeMode mode) => state = mode;
}

/* ---------------------------------- */

[Filename: my_app.dart]

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'theme_states.dart' hide ThemeMode;

class MyApp extends ConsumerWidget {
  // ...
 
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      // ...
      themeMode: ref.watch(themeModeProvider),
      home: MyScreen(
        onMyButtonTap: () => ref.read(themeModeProvider.notifier).set(ThemeMode.dark),
      ),
      // ...
    );
  }
}
```

**Problem:** I have to put an alias on `package:flutter/material.dart` and hide `ThemeMode` wherever I use `flutter/material` and the `themeModeProvider` provider together.

# Describe the solution you'd like
My solution is to add a prop to the `@Riverpod()` annotation called `name`.
What this prop does it's to change the resulting variable name associated with the Provider's class/function to `the annotation's name prop + configSuffix` (ex. Let's say that we use the default prefix: `@Riverpod(name: 'user') + 'Provider' = 'userProvider'`).

Let's go through the examples I wrote before and fix them using the proposed solution.

### Example 1
```dart
[Filename: user.dart]

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    required int id,
    @Default('User') String displayName, 
  }) = _User;
}

@Riverpod(name: 'user')
class UserProvider extends _$UserProvider {
  @override
  User build() => // ...
  
  void changeName(String name) =>
    state = state.copyWith(displayName: name);
  
  // ...
}

/* ---------------------------------- */

[Filename: my_app.dart]

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'user.dart';

class MyApp extends ConsumerWidget {
  // ...
 
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final anotherUser = User(id: 4);

    // ...

    return MaterialApp(
      // ...
      home: MyScreen(
        user: ref.watch(userProvider);
        onNameChanged: (name) => ref.read(userProvider.notifier).changeName(name),
      ),
      // ...
    );
  }
}
```

**Solution:** 
- `UserState` changed to something more meaningful like `UserProvider` and added `name: 'user'` prop to `@Riverpod()` annotation
- The resulting provider name will be `@Riverpod(name) + configSuffix = userProvider`

### Example 2
```dart
[Filename: theme_states.dart]

import 'package:flutter/material.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'theme_states.g.dart';

@Riverpod(name: 'themeMode')
class ThemeModeProvider extends _$ThemeModeProvider {
  @override
 ThemeMode build() => ThemeMode.system;
 
  void set(ThemeMode mode) => state = mode;
}

/* ---------------------------------- */

[Filename: my_app.dart]

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'theme_states.dart';

class MyApp extends ConsumerWidget {
  // ...
 
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      // ...
      themeMode: ref.watch(themeModeProvider),
      home: MyScreen(
        onMyButtonTap: () => ref.read(themeModeProvider.notifier).set(ThemeMode.dark),
      ),
      // ...
    );
  }
}
```

**Solution:** 
- `ThemeMode` changed to something more meaningful like `ThemeModeProvider` and added `name: 'themeMode'` prop to `@Riverpod()` annotation
- The resulting provider name will be `@Riverpod(name) + configSuffix = themeModeProvider`
- Since the classes names are different now, I can remove the aliases and the `hide` keyword when importing

# Describe alternatives you've considered
Another solution could be not to add the suffix to the generated provider's name if the annotated class/function already ends with it. 

### Example

Let's suppose that I didn't changed my `build.yaml`, so the suffix is `Provider`:
```dart
[Filename: user.dart]

import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'user.g.dart';

@riverpod
class UserProvider extends _$UserProvider {
  // ...
}
```

Since the suffix is `Provider` and the end of `UserProvider` too, we get:
```dart
[Filename: user.g.dart]

// ...

final userProvider = Provider(...);
```

Instead of the current implementation:
```dart
[Filename: user.g.dart]

// ...

final userProviderProvider = Provider(...);
```

# Additional notes
Maybe I'm missing something. If it is like so, please tell me.

If this solution will be approved I could try to take care of the implementation myself through a PR, if you prefer.

Thank you for your time.

Niccolò Gorraz

**Comment by NicoGorr** [comment] 2023-12-16 19:05
Possible overlap with issues #2244, #2261, #2279, #3130, #3130, #3189 and #3203

**Comment by rrousselGit** [comment] 2023-12-16 19:54
Duplicate of https://github.com/rrousselGit/riverpod/issues/2244

**Closed by rrousselGit** 2023-12-16 19:54 UTC
Labels: enhancement, needs triage
