### ISSUE TITLE
Get the error when watching only `FutureProvider.future` on creating `FutureProvider`.

### ISSUE THREAD

**Issue by KyoheiG3** [rrousselGit/riverpod#2138] opened 2023-02-06 10:02 UTC
**Describe the bug**
Get the error when watching only `FutureProvider.future` on creating `FutureProvider`.

**To Reproduce**
The code below is an example from my modified `riverpod` project.
It can get the error when the `FloatingActionButton` was tapped.

```dart
final counterProvider = StateProvider((ref) => 0);

final counterFutureProvider1 = FutureProvider((ref) {
  return ref.watch(counterProvider);
});

final counterFutureProvider2 = FutureProvider((ref) {
  return ref.watch(counterProvider);
});

final allFutureProvider = FutureProvider((ref) {
  return Future.wait([
    ref.watch(counterFutureProvider1.future),
    ref.watch(counterFutureProvider2.future),
  ]);
});

class Home extends ConsumerWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter example')),
      body: Center(
        // Consumer is a widget that allows you reading providers.
        child: Consumer(
          builder: (context, ref, _) {
            final count = ref.watch(allFutureProvider);
            print(count.error);
            // flutter: 'package:riverpod/src/async_notifier/base.dart': Failed assertion: line 333 pos 18: '_lastFuture == null': bad state [base.dart:333]
            return Text('$count');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // The read method is a utility to read a provider without listening to it
        onPressed: () => ref.read(counterProvider.notifier).state++,
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Expected behavior**
Can get value without error.

**Comment by rrousselGit** [comment] 2023-02-06 10:12
Duplicate of https://github.com/rrousselGit/riverpod/issues/2041

**Closed by rrousselGit** 2023-02-06 10:12 UTC
Labels: bug, needs triage
