### ISSUE TITLE
riverpod_lint: support extension getters and methods on WidgetRef or Ref

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/riverpod#3823] opened 2024-10-31 22:10 UTC
**Is your feature request related to a problem? Please describe.**
I often define extension getters or methods on Ref for commonly read providers:

```
extension RefEx on Ref {
  get userId => read(userIdProvider);
}

final userId = ref.userId;
```

The analyzer/riverpod_lint currently doesn't understand this, and isn't able to evaluate a provider dependencies correctly.

**Describe the solution you'd like**
Allow the analyzer to understand ref.read or ref.watch inside an extension expression.

**Describe alternatives you've considered**

**Additional context**
I have had a go at trying to get riverpod_analyzer to understand this, but it's a bit beyond me. I haven't been able to figure out how to retrieve the inner MethodInvocation of the extension expression

**Comment by rrousselGit** [comment] 2024-10-31 23:18
Duplicate of https://github.com/rrousselGit/riverpod/issues/2995

**Closed by rrousselGit** 2024-10-31 23:18 UTC
Labels: enhancement, needs triage
