### ISSUE TITLE
Type error thrown when using StateNotifierProvider.family

### ISSUE THREAD

**Issue by eli1stark** [rrousselGit/riverpod#1733] opened 2022-10-05 14:55 UTC
**Describe the bug**
In riverpod 2.0.2 I started to get the error below:
```
[log] type '((StateNotifierProviderRef<Y0, Y1>) => Y0, {String? name, Family<dynamic>? from, Object? argument, List<ProviderOrFamily>? dependencies, (() => String)? debugGetCreateSourceHash}) => StateNotifierProvider<AnimatorNotifier, AnimatorState>' is not a subtype of type '((StateNotifierProviderRef<AnimatorNotifier, AnimatorState>) => AnimatorNotifier, {Object? argument, List<ProviderOrFamily>? dependencies, Family<dynamic> from, String? name}) => StateNotifierProvider<AnimatorNotifier, AnimatorState>' of 'function result'
```

**To Reproduce**

It's hard to reproduce, the error appears at random times and very rarely but the code that causes is:

```dart
    ref.listen<Type of someVal>(
      someProvider{ERROR THROWN HERE}(someArg).select((state) => state.someVal),
      (_, __) {},
    );
 ```
The whole code sequence works without an error, but after X time this error is thrown for the same code that worked a couple of minutes ago.

Edit: This problem can be fixed only by HotRestart. When I leave the screen, invalidate this provider and go back or try to use this provider again, then this problem is thrown.

<details>
  <summary>Logs</summary>

```

[log] type '((StateNotifierProviderRef<Y0, Y1>) => Y0, {String? name, Family<dynamic>? from, Object? argument, List<ProviderOrFamily>? dependencies, (() => String)? debugGetCreateSourceHash}) => StateNotifierProvider<AnimatorNotifier, AnimatorState>' is not a subtype of type '((StateNotifierProviderRef<AnimatorNotifier, AnimatorState>) => AnimatorNotifier, {Object? argument, List<ProviderOrFamily>? dependencies, Family<dynamic> from, String? name}) => StateNotifierProvider<AnimatorNotifier, AnimatorState>' of 'function result'
[log] #0      FamilyBase.call (package:riverpod/src/framework/family.dart)
package:riverpod/…/framework/family.dart:1
#1      WidgetRefAnimatorX.listenIndexAnimation
package:package_name/…/extension/widget_ref_animator_extension.dart:107
#2      _MyWidgetState.build
package:package_name/…/components/my_widget.dart:115
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4992
#4      ConsumerStatefulElement.build
package:flutter_riverpod/src/consumer.dart:488
#5      HookElement.build
package:flutter_hooks/src/framework.dart:416
#6      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4878
#7      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:5050
#8      Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#9      BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2667
#10     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#11     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
#12     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#13     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
#14     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#15     _rootRun (dart:async/zone.dart:1391:13)
#16     _CustomZone.run (dart:async/zone.dart:1293:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#18     _invoke (dart:ui/hooks.dart:150:10)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#20     _drawFrame (dart:ui/hooks.dart:115:31)

```

**Comment by rrousselGit** [comment] 2022-10-05 15:35
I'd love to help, but without something that I can execute, I don't know what's going on

**Comment by rrousselGit** [comment] 2022-10-05 15:36
Do you have some stacktrace maybe?

**Comment by eli1stark** [comment] 2022-10-05 16:42
Once I hit this error again I'll provide the stack trace, sorry for that. In the meantime, I'm trying to come up with a minimal reproducible example. Can you hint me please on this error, what's it about, so I can research this problem further? From the description, I can think of maybe some type inference related issue, the provider is not recognizing the type...

**Comment by rrousselGit** [comment] 2022-10-05 16:44
That's the thing. I've never seen this before

It could be a bug. But if so, you're the first to report it. So I can't really help you without more info

**Comment by eli1stark** [comment] 2022-10-05 16:46
Ok, I return with more info soon

**Comment by eli1stark** [comment] 2022-10-05 17:15
Attached logs and update a little bit of code that causing the problem, when I come up with MRE, I post it as well.

**Comment by rrousselGit** [comment] 2022-10-05 17:19
Are you maybe overriding the provider? What's your provider definition?

**Comment by eli1stark** [comment] 2022-10-05 17:24
Provider definition:
```dart
final animatorNotipod = StateNotifierProvider.family<AnimatorNotifier, AnimatorState, String>(
  (ref, key) {
    return AnimatorNotifier();
  },
  name: 'animatorNotipod',
);
```

No, I'm not overriding this provider, just use family. But I'm extending `WidgetRef.listen` method to write additional logic and in this logic, I'm updating `AnimatorNotifier` but it should be fine since I'm not updating the value I'm listening to.

**Comment by eli1stark** [comment] 2022-10-05 17:47
If I remove the `.family` from this provider without changing the other code, the error is not reproducible. Something in the `Family` modifier causing this.

**Comment by roscale** [comment] 2022-10-05 21:37
I was going to open an issue about this problem. In my case, the error only appears after I hot reload a few times the file where my providers are declared. I'm just watching on a `StreamProvider.family`, nothing custom.

**Comment by roscale** [comment] 2022-10-05 22:34
I managed to create a minimal reproducible example.
Run this code and do a hot reload by adding a blank line for example.
Hope this helps.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final counter = StreamProvider.family<int, void>((ref, _) async* {
  yield 0;
});

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerStatefulWidget {
  const MyApp({super.key});

  @override
  ConsumerState<MyApp> createState() => _MyAppState();
}

class _MyAppState extends ConsumerState<MyApp> {
  @override
  Widget build(BuildContext context) {
    Future.microtask(() {
      const int iterations = 1000; // A smaller number will trigger the error slower.
      for (int i = 0; i < iterations; i++) {
        ref.read(counter(i));
      }
    });

    Future.microtask(() {
      setState(() {});
    });

    return Container();
  }
}
```

**Comment by eli1stark** [comment] 2022-10-06 04:05
Providing my implementation of custom `listen` and `state` I operate with:

**State:**
```dart
@freezed
class AnimatorState with _$AnimatorState {
  const factory AnimatorState({
    @Default(<AnimationModel>[]) List<AnimationModel> animations,
    @Default(<RunningAnimation>[]) List<RunningAnimation> running,
  }) = _AnimatorState;
}
```
**`listen` extension:**
```dart
// IndexAnimation implements AnimationModel
void listenIndexAnimation<T extends IndexAnimation>(
    String key,
    String uid,
    int index,
    TickerFuture Function(T animation) animator, {
    void Function()? whenComplete,
  }) {
    listen<List<AnimationModel>>(
      // the bug is thrown here
      animatorNotipod(key).select((s) => s.animations),
      (prev, curr) async {
        if ((prev?.length ?? 0) >= curr.length) return;

        final animations = curr.whereTypeAndIndex<T>(index);

        if (animations.isEmpty) return;

        if (animations.length > 1) {
          throw Error();
        }

        final animation = animations.first;

        final state = read(animatorNotipod(key));
        final notifier = read(animatorNotipod(key).notifier);
        final running = RunningAnimation(uid, animation);
        final isRunning = state.running.contains(running);

        if (isRunning) return;

        notifier.addRunning(running);

        animator(animation).whenCompleteOrCancel(() {
          if (!animation.isCompleted) {
            animation.complete();
            notifier.removeAnimation(animation);
          }
          notifier.removeRunning(running);

          whenComplete?.call();
        });
      },
    );
  }
```
I hope this helps.

**Comment by rrousselGit** [comment] 2022-10-06 07:27
Sadly not really haha

**Comment by rrousselGit** [comment] 2022-10-06 12:15
I tried your example @roscale but didn't reproduce the problem (besides it destroying my CPU haha)

**Comment by rrousselGit** [comment] 2022-10-06 12:46
It's weird because the stacktrace is broken

Honestly it sounds like a Dart bug related to hot-reload.

**Comment by roscale** [comment] 2022-10-06 12:57
Yeah, it's actually really weird. From my understanding, FamilyBase receives the wrong providerFactory after the hot-reload, but I don't think it should be possible because you always give it the right constructor.
![Screenshot_20221006_145255](https://user-images.githubusercontent.com/18357220/194318469-a48aa384-edaf-4bfd-83f8-eded3214ffa5.png)

**Comment by rrousselGit** [comment] 2022-10-06 13:00
Ok I found the problem. It's both a Dart bug and a Riverpod bug.

In the internals of Family, it's passing the Provider's constructor as tear-off. 

But the constructor has for prototype `Whatever Function(..., {Family? from})` yet the Family internals expect `Whatever Function(..., {Family from})`

Notice the Family? vs Family
In the function prototype, it's missing either a ? or a `required`. 

So the types mismatch.
But for some reason, the Dart compiler doesn't catch it .... unless you do a hot-reload somehow?

**Comment by rrousselGit** [comment] 2022-10-06 13:02
Actually, Riverpod's code _is_ valid thinking about it. The types should match.

It's probably the opposite instead. The Dart compiler works, but hot-reload doesn't

**Comment by rrousselGit** [comment] 2022-10-06 13:10
Ok removing the constructor tear-off _did_ fix it.

Changing:

```dart
class StreamProviderFamily<R, Arg> extends FamilyBase<StreamProviderRef<R>,
    AsyncValue<R>, Arg, Stream<R>, StreamProvider<R>> {
  /// The [Family] of [StreamProvider].
  StreamProviderFamily(
    super.create, {
    super.name,
    super.dependencies,
  }) : super(providerFactory: StreamProvider<R>.new);
}
```
to:

```dart
/// The [Family] of [StreamProvider].
class StreamProviderFamily<R, Arg> extends FamilyBase<StreamProviderRef<R>,
    AsyncValue<R>, Arg, Stream<R>, StreamProvider<R>> {
  /// The [Family] of [StreamProvider].
  StreamProviderFamily(
    super.create, {
    super.name,
    super.dependencies,
  }) : super(providerFactory: (create, {name, from, argument, dependencies}) {
          return StreamProvider<R>(
            create,
            name: name,
            from: from,
            argument: argument,
            dependencies: dependencies,
          );
        });
}
```

remove the error.

**Comment by rrousselGit** [comment] 2022-10-06 13:52
Done, here's the Dart issue: https://github.com/dart-lang/sdk/issues/50148

I don't feel like changing all the providers to remove the constructor tear-off. It's a bit tedious and error-prone.
To begin with, I refactored families to use constructor tear-offs on purpose ...

It'd be great if the Dart team could fix this and making cherry-pick the bug.

**Comment by mark8044** [comment] 2022-12-20 15:35
> **Describe the bug** In riverpod 2.0.2 I started to get the error below:
> 
> ```
> [log] type '((StateNotifierProviderRef<Y0, Y1>) => Y0, {String? name, Family<dynamic>? from, Object? argument, List<ProviderOrFamily>? dependencies, (() => String)? debugGetCreateSourceHash}) => StateNotifierProvider<AnimatorNotifier, AnimatorState>' is not a subtype of type '((StateNotifierProviderRef<AnimatorNotifier, AnimatorState>) => AnimatorNotifier, {Object? argument, List<ProviderOrFamily>? dependencies, Family<dynamic> from, String? name}) => StateNotifierProvider<AnimatorNotifier, AnimatorState>' of 'function result'
> ```
> 
> **To Reproduce**
> 
> It's hard to reproduce, the error appears at random times and very rarely but the code that causes is:
> 
> ```dart
>     ref.listen<Type of someVal>(
>       someProvider{ERROR THROWN HERE}(someArg).select((state) => state.someVal),
>       (_, __) {},
>     );
> ```
> 
> The whole code sequence works without an error, but after X time this error is thrown for the same code that worked a couple of minutes ago.
> 
> Edit: This problem can be fixed only by HotRestart. When I leave the screen, invalidate this provider and go back or try to use this provider again, then this problem is thrown.
> 
> Logs

I believe I'm having the same error https://github.com/rrousselGit/riverpod/discussions/1984

In my case, my StateProvider is a `bool` that is changed when a scroll position on a listview as at a certain point

```
NotificationListener<ScrollNotification>(
                    onNotification: (scrollNotification) {
                      if ((scrollNotification.metrics.extentBefore > 70) && (ref.read(showTitleProvider(widget.myhash).notifier).state == false))
                      {
                                   ....
                                 ref.read(showTitleProvider(widget.myhash).notifier).state = true;
                      }
...
}
```

Its hard to make the bug come out, but I can make it come out if I very very very quickly scroll back and fourth at that point (70pixels in my case)forcing the flag to repeatedly switch between true and false.  If I do it enough times and fast enough then the bug comes out.  Otherwise I have no rhyme or reason as to how many times forces it to trigger.

**Comment by rrousselGit** [comment] 2023-01-12 20:37
The error was fixed in the Dart SDK recently. So I'll close this

**Closed by rrousselGit** 2023-01-12 20:37 UTC
Labels: bug, dart-bug

**Comment by lzhAndroid** [comment] 2023-01-29 02:54
flutter 3.7 still has this error.

**Comment by lzhAndroid** [comment] 2023-01-29 02:55
type '((StateProviderRef) => Y0, {String? name, Family? from, Object? argument, List? dependencies, (() => String)? debugGetCreateSourceHash}) => StateProvider' is not a subtype of type '((StateProviderRef) => int?, {Object? argument, List? dependencies, Family from, String? name}) => StateProvider' of 'function result'

**Comment by dossiman** [comment] 2023-02-04 06:31
> The error was fixed in the Dart SDK recently. So I'll close this

in which Dark SDK version was it fixed? this error started popping after upgraded to flutter 3.7 / dart 2.19.

The following _TypeError was thrown building DismissibleHint(dirty, dependencies: [UncontrolledProviderScope], state: _ConsumerState#065b9):
type '((AutoDisposeProviderRef<Y0>) => Y0, {String? name, Family<dynamic>? from, Object? argument, List<ProviderOrFamily>? dependencies, (() => String)? debugGetCreateSourceHash}) => AutoDisposeProvider<bool>' is not a subtype of type '((AutoDisposeProviderRef<bool>) => bool, {Object? argument, List<ProviderOrFamily>? dependencies, Family<dynamic> from, String? name}) => AutoDisposeProvider<bool>' of 'function result'

    • Flutter version 3.7.0 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (11 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

**Comment by AguSampietro** [comment] 2023-02-08 21:03
Same here:
`type '((AutoDisposeStateNotifierProviderRef<Y0, Y1>) => Y0, {String? name, Family<dynamic>? from, Object? argument, List<ProviderOrFamily>? dependencies, (() => String)? debugGetCreateSourceHash}) => AutoDisposeStateNotifierProvider<TimerNotifier, TimerState>' is not a subtype of type '((AutoDisposeStateNotifierProviderRef<TimerNotifier, TimerState>) => TimerNotifier, {Object? argument, List<ProviderOrFamily>? dependencies, Family<dynamic> from, String? name}) => AutoDisposeStateNotifierProvider<TimerNotifier, TimerState>' of 'function result'`

I got the same error with: 
- Flutter 3.7
- Dart 2.19

**Comment by mark8044** [comment] 2023-02-12 03:20
@rrousselGit 

Unfortunately, still seeing this problem even with the latest version

```
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (3 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1
```

**Comment by perret123** [comment] 2023-02-13 07:19
If I see this correctly, the commit fixing the mentioned Dart Issue is only in Dart 3.0.0 ? 

https://github.com/dart-lang/sdk/commit/88400bdc4249b592714fd76c61df251e212cca20

**Comment by mark8044** [comment] 2023-02-13 17:14
> If I see this correctly, the commit fixing the mentioned Dart Issue is only in Dart 3.0.0 ?
> 
> [dart-lang/sdk@88400bd](https://github.com/dart-lang/sdk/commit/88400bdc4249b592714fd76c61df251e212cca20)

Ah, ok thanks.  Will wait it out

**Comment by chigo01** [comment] 2023-03-02 19:48
════════ Exception caught by widgets library ═══════════════════════════════════
type '((AutoDisposeStreamProviderRef<Y0>) => Stream<Y0>, {required String? name, required Iterable<ProviderOrFamily>? dependencies, required Iterable<ProviderOrFamily>? allTransitiveDependencies, required (() => String)? debugGetCreateSourceHash, Family<Object?>? from, Object? argument}) => AutoDisposeStreamProvider<List<Transaction>>' is not a subtype of type '((AutoDisposeStreamProviderRef<List<Transaction>>) => Stream<List<Transaction>>, {required Set<ProviderOrFamily>? allTransitiveDependencies, Object? argument, required (() => String)? debugGetCreateSourceHash, required Iterable<ProviderOrFamily>? dependencies, Family<Object?> from, required String? name}) => AutoDisposeStreamProvider<List<Transaction>>' of 'function result'

I occasionally  get this error and I can't figure out the issue

**Comment by mostafiz9900** [comment] 2023-04-07 16:40
start stopwatch 

type '((ChangeNotifierProviderRef<Y0>) => Y0, {required String? name, required Iterable<ProviderOrFamily>? dependencies, required Iterable<ProviderOrFamily>? allTransitiveDependencies, required (() => String)? debugGetCreateSourceHash, Family<Object?>? from, Object? argument}) => ChangeNotifierProvider<TimerChangeNotifier>' is not a subtype of type '((ChangeNotifierProviderRef<TimerChangeNotifier>) => TimerChangeNotifier, {required Set<ProviderOrFamily>? allTransitiveDependencies, Object? argument, required (() => String)? debugGetCreateSourceHash, required Iterable<ProviderOrFamily>? dependencies, Family<Object?> from, required String? name}) => ChangeNotifierProvider<TimerChangeNotifier>' of 'function result'

**Comment by roscale** [comment] 2023-04-27 17:32
I've written some patches for version 2.3.6 that work around the issue by replacing constructor tear-offs with anonymous functions.

[patches.zip](https://github.com/rrousselGit/riverpod/files/11346340/patches.zip)

```shell
cd ~/.pub-cache/hosted/pub.dev/riverpod-2.3.6
git apply fix_riverpod.patch
cd ~/.pub-cache/hosted/pub.dev/flutter_riverpod-2.3.6
git apply fix_flutter_riverpod.patch
```

**Comment by perret123** [comment] 2023-04-28 18:31
@roscale Thank you, this works for me. :-) 

Hope Dart 3 will soon be stable anyway.
