### ISSUE TITLE
AutoDispose - Flutter Web 2.0.0-dev.0 onwards 

### ISSUE THREAD

**Issue by JSlast** [rrousselGit/riverpod#1809] opened 2022-10-24 01:44 UTC
There seems to be an issue with Auto Dispose with Riverpod 2.0.

Platform: Flutter Web
Issue Versions Tested: 2.0.0-dev.0, 2.0.0-dev.1, 2.0.0-dev.2, 2.0.0-dev.3, 2.0.0, 2.0.1, 2.0.2
Functioning Version Tested: 1.0.3
Functionality: Auto Dispose. 
Issue: 
When adding AutoDispose on a Provider and then trying to load that provider on another page it comes up with "Bad State: Source Maps are not done loading". I have tested this with two different providers on two different pages. Providers I have without Auto Dispose prior to upgrade is working perfectly fine post update. So only Provider.autodispose is affected on Flutter Web Riverpod 2.0. On the affected Providers, if I was to only remove .autodispose but keep rest of the code it works fine also.

When does it work?
With exactly the same code and same version it does work on iOS. Have not tested on Android.
If I change the versions for below to 1.0.3 the app works perfectly fine with exactly same code on Flutter Web. 
I can consistently get the Provider to work and not work by only changing the version between 1.0.3 and anything 2.0.0-dev.0 onwards

Packages:
 flutter_riverpod: ^
hooks_riverpod: ^

**Comment by RandalSchwartz** [comment] 2022-10-24 01:49
This affected me too.  The workaround is no autodispose for the moment.  And why it's only on the web, is weird.

**Comment by rrousselGit** [comment] 2022-10-24 09:33
I'll need a snippet to reproduce.

And it's most definitely a Dart issue too. So if you find a way to reproduce the problem without Riverpod, please raise a Dart issue

**Comment by ntoljic** [comment] 2022-10-24 14:19
I hit this issue as well. Upon looking through the existing issues, I think it is at least related to if not the same as https://github.com/rrousselGit/riverpod/issues/1713.

**Comment by RandalSchwartz** [comment] 2022-10-25 01:01
It happened somewhere between dev.9 and 2.0.0 - do you have any sense on what behavior is used by example/counter when autoDispose is enabled might be triggering the dart2js bug?

**Comment by kolotum** [comment] 2022-10-27 10:06
Is this issue related to https://github.com/rrousselGit/riverpod/issues/1713 ?

**Comment by leehack** [comment] 2022-10-27 10:20
Yeah. I think we can close this one as well:
https://github.com/rrousselGit/riverpod/pull/1823

**Comment by JSlast** [comment] 2022-10-27 11:11
Hey @rrousselGit 

My actual app is very reliant on Hooks Riverpod so couldn't test it on there. 

But I created a new app using the code of Riverpod Counter app from Dartpad. I did change the Provider to .autoDispose to reflect the issue we are having.

With the above dependency_overrides the apps works as expected on Flutter Web and when I remove the dependency_overrides the app reverts to crashing on Flutter Web. So seems like the above change fixes the issue for Web.

**Comment by rrousselGit** [comment] 2022-10-27 11:23
> My actual app is very reliant on Hooks Riverpod so couldn't test it on there.

You can use hooks too. Just add the same thing for hooks_riverpod too

**Comment by skreborn** [comment] 2022-10-27 11:25
@rrousselGit Placed the overrides in a fairly large project that was held back at [v2.0.0-dev.9](https://github.com/rrousselGit/riverpod/releases/tag/v2.0.0-dev.9) because of this issue, and everything seems to work flawlessly on the latest `master`.

**Comment by rrousselGit** [comment] 2022-10-27 11:27
Great. I'll close this then

If someone tries the pubspec overrides and still has the issue, please say so

**Closed by rrousselGit** 2022-10-27 11:27 UTC
Labels: bug, dart-bug

**Comment by JSlast** [comment] 2022-10-27 11:32
Thanks Remi 

Hooks working as well as suggested. 

Thanks for looking into this and getting it resolved.
