### ISSUE TITLE
Bad state: No ProviderScope found error infrequently occurring during ref.read calls

### ISSUE THREAD

**Issue by ReeceDrage** [rrousselGit/riverpod#1346] opened 2022-04-08 11:01 UTC
**Describe the bug**
In production code, periodically a `Bad state: No ProviderScope found` is caught in our Sentry logs, originating from various `ref.read` calls throughout the application. This occurs in an application that has a `ProviderScope` as the parent of the full widget tree. So far we haven't been able to reproduce this in local debugging and therefore cannot provide a code snippet to reproduce it, but some code snippets have been provided for context. 

This issue occurs using flutter_riverpod 2.0.0-dev.0 on Flutter 2.10.4, with the issue occurring on a variety of iOS and Android devices.

The ProviderScope for the application:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Kiwi.init();

  if (Config.sentryDsn.isNotEmpty) {
    await SentryFlutter.init(
      (options) {
        options.dsn = Config.sentryDsn;
      },
      appRunner: () => runApp(ProviderScope(child: App())),
    );
  } else {
    runApp(ProviderScope(child: App()));
  }
}
```

One of the `ref.read` calls that has triggered this exception:
```
class _CoreContentState extends ConsumerState<CoreContent>
    with SingleTickerProviderStateMixin {
  late final tabController;

  @override
  void initState() {
    super.initState();
    this.loadProviders();
  }

  void loadProviders() async {
    setState(() => isLoading = true);

    await Future.wait([
      if (mounted) ref.read(historyProvider.notifier).init(),
      if (mounted) ref.read(scheduleProvider.notifier).init(),
    ]);

    transferTabController = TabController(
      initialIndex: ref.read(selectedTabProvider).selectedTab,
      length: _Constants.tabQuantity,
      vsync: this,
    );
    
    setState(() => isLoading = false);
 }
```

The sentry log recorded:
```
StateError: Bad state: No ProviderScope found
  File "framework.dart", line 102, in ProviderScope.containerOf
  File "consumer.dart", line 487, in ConsumerStatefulElement.read
  File "core_content.dart", line 51, in _CoreContentState.loadProviders
```

**Expected behavior**
In this case, a tab controller is intended to be constructed with a selected tab held in the `StateNotifierProvider` `selectedTabProvider`, but Sentry logged a fatal error originating from this action due to a missing `ProviderScope`

**Comment by rrousselGit** [comment] 2022-04-09 12:39
Could you provide a minimal reproducible example?

**Comment by Hamza-Imran75** [comment] 2022-04-09 12:42
I've been also getting the same error and am unable to reproduce in local I'm using river pod version 1.

**Comment by ReeceDrage** [comment] 2022-04-09 14:41
As previously mentioned, this has so far not been reproducible with local builds, only occurring in production builds, and as such I've only been able to see the issue in Sentry logs of captured exceptions, all including the following lines in the stack-trace:
```
StateError: Bad state: No ProviderScope found
  File "framework.dart", line 102, in ProviderScope.containerOf
  File "consumer.dart", line 487, in ConsumerStatefulElement.read
```
As shown in the initial comment, the full application is wrapped in a `ProviderScope`, so I'm wondering if there are any other considerations that are needed for interacting with state, particularly in production applications.

**Comment by Reprevise** [comment] 2022-04-09 17:31
I also find this issue occuring in 1.0.3 only in production builds but on `ref.refresh` calls. I'm wondering if it's because it's being used in an async context? I know `BuildContext` can produce weird behavior in async contexts.

**Comment by rounce** [comment] 2022-04-12 06:19
I don’t think it’s specific to the production build, I once got this exception in debugging. But then doing the same steps I couldn’t reproduce it. v. 2.0.0.dev.5

**Comment by rsbthebest** [comment] 2022-04-13 07:25
I am facing it too in production with hooks_riverpod: ^2.0.0-dev.0

Can not reproduce locally.

**Comment by rsbthebest** [comment] 2022-04-13 07:25
I am facing it too in production with hooks_riverpod: ^2.0.0-dev.0

Can not reproduce locally.

**Comment by rrousselGit** [comment] 2022-04-13 08:37
As much as I would like to help, without a reproducible example there's nothing I can do.

**Comment by rounce** [comment] 2022-04-14 05:38
I managed to find the reason. The case turned out to be in a third-party component that depends on the provider. Made a fork on the riverpod, no more errors occur.

**Comment by rsbthebest** [comment] 2022-04-14 06:33
Would you please share the fork here? and what changes did you made?

**Comment by rsbthebest** [comment] 2022-04-14 06:33
Would you please share the fork here? and what changes did you made?

**Comment by rrousselGit** [comment] 2022-04-14 06:42
> I managed to find the reason. The case turned out to be in a third-party component that depends on the provider. Made a fork on the riverpod, no more errors occur.

What was the problem exactly?

**Comment by rrousselGit** [comment] 2022-04-21 07:05
My theory is that this happens because the widget that tries to read a provider is unmounted

In dev mode, searching for inherited widgets in a disposed widget would throw an assertion error (cf "looking up a deactivated widget"). But in release mode, Flutter would return `null`. This would instead trigger this error

So I doubt that this is a problem with Riverpod.

**Comment by matuella** [comment] 2022-04-26 23:26
I'm also having sporadic issues with this same error - and they only occur in release mode.

Even though these events are really rare, It only occurs in a specific `ConsumerStatefulWidget`, so I'm inclined to say that this is not an error with `riverpod` itself - like @rrousselGit said, something could be disposed.

Either way, I think we could get a better error description on this, is there anything that we could do on `riverpod` side to improve this?

**Comment by rrousselGit** [comment] 2022-05-20 11:12
I'll close this as this is a Flutter issue not a Riverpod one. I'll consider writing a custom lint rule to help catch those problem better though

TD;DR chances are you're doing:

```dart
onPressed: () async {
  await someFuture;
  ref.read(provider);
}
```


The fix is to do:

```dart
onPressed: () async {
  await someFuture;
  if (!mounted) return;
  ref.read(provider);
}
```

**Closed by rrousselGit** 2022-05-20 11:12 UTC
Labels: bug, question

**Comment by pbouttier** [comment] 2023-02-13 10:03
I have encountered the same problem. The if(mounted) did not solve my problem (no context = no update of my data)

On the other hand, doing a ref.invalidate seemed to work.

**Comment by anhhtbk** [comment] 2023-02-19 09:44
> I have encountered the same problem. The if(mounted) did not solve my problem (no context = no update of my data)
> 
> 
> 
> On the other hand, doing a ref.invalidate seemed to work.

I have same problem. How do you use ref.invalidate to fix this issue?

**Comment by pbouttier** [comment] 2023-02-19 14:17
Like this : 

```
//oustide widget
final isSelectedProvider = StateProvider.autoDispose.family<bool, String>((ref, setId) => false);

...

//on pop route, to await the end of the pop animation to deselect the set, that the user keeps track of the changes
Future.delayed(const Duration(milliseconds: 300), (){
     ref.invalidate(isSelectedProvider(set.documentId)); 
 });

//in widget
AnimatedCardEffect(
    isFirst: isFirst,
    isLast: isLast,
    color: ref.watch(isSelectedProvider(set.documentId)) ? Theme.of(context).focusColor : null,
    child: SetText(
        set: set,
        index: index,
        exercise: exercise,
    ),
)
```

it allows me to return to the default value in the ref.watch. Obviously in my case it works because it's a simple bool. For a more complex state, I don't know what to do.
