### ISSUE TITLE
Maximum call stack size exceeded with provider.autoDispose on web (2.x)

### ISSUE THREAD

**Issue by simplecohesion** [rrousselGit/riverpod#1763] opened 2022-10-14 00:11 UTC
**Describe the bug**
Using a 2.x provider with autoDispose fails with an "Invalid argument: Maximum call stack size exceeded" error when run in a web platform.

The same code works correctly across all platforms in Riverpod 1.x, and in 2.x for iOS or Android, however 2.x on a web platform has the error.

**To Reproduce**
Run the flutter app in edge:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TestWidget(),
    );
  }
}

final testProvider = Provider.autoDispose<String>(
  (ref) {
    return 'testing';
  },
);

class TestWidget extends ConsumerWidget {
  const TestWidget({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final testString = ref.watch(testProvider);

    return Text(testString);
  }
}
```

**Expected behavior**
Not have a fatal error when using on a web platform.

**Comment by TimWhiting** [comment] 2022-10-14 01:06
Duplicate of #1713

**Closed by TimWhiting** 2022-10-14 01:06 UTC
Labels: bug, needs triage
