### ISSUE TITLE
[riverpod_generator] 3.0.0-dev.4 The getter 'metadata' isn't defined for the class 'AstNode'.

### ISSUE THREAD

**Issue by dalugm** [rrousselGit/riverpod#3005] opened 2023-10-17 01:46 UTC
**Describe the bug**

As the title show, it works well with 3.0.0-dev.3. After upgrade to 3.0.0-dev.4, it shows the following error:

```
[WARNING] ../../../../.pub-cache/hosted/pub.flutter-io.cn/riverpod_generator-3.0.0-dev.4/lib/src/templates/family.dart:230:48: Error: The getter 'metadata' isn't defined for the class 'AstNode'.
 - 'AstNode' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../../.pub-cache/hosted/pub.flutter-io.cn/analyzer-6.2.0/lib/src/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'metadata'.
    final meta = metaAnnotations(provider.node.metadata);
                                               ^^^^^^^^
[INFO] Precompiling build script... completed, took 12.0s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

**To Reproduce**

```
flutter create test
cd test
flutter pub add riverpod riverpod_annotation dev:build_runner dev:riverpod_generator:^3.0.0-dev.4
dart run build_runner watch
```

The above error appears.

**Expected behavior**

3.0.0-dev.4 works as 3.0.0-dev.3

**Comment by huahua8893** [comment] 2023-10-17 06:18
same issue

**Comment by lightlitebug** [comment] 2023-10-17 07:35
same issue!

**Comment by tusharbhambere** [comment] 2023-10-17 09:55
same issue!!!

**Comment by 2kjm** [comment] 2023-10-17 10:06
same issue

**Comment by locihn** [comment] 2023-10-17 12:00
same issue!!! 😞

**Comment by rrousselGit** [comment] 2023-10-17 12:51
Stop spamming folks. No need to keep posting the same comment over and over

**Comment by simmonsdillon** [comment] 2023-10-17 17:51
In case it helps for others:
I just ran "dart pub downgrade riverpod_generator" and then build_runner was working for me again.

**Comment by woprandi** [comment] 2023-10-18 11:37
I don't know why but 
```
flutter pub add \      
  flutter_riverpod \
  riverpod_annotation \
  dev:riverpod_generator \
  dev:build_runner \
  dev:custom_lint \
  dev:riverpod_lint | grep generator
+ riverpod_generator 3.0.0-dev.4
```

This dev release is installed instead of latest stable

**Comment by rrousselGit** [comment] 2023-10-21 16:24
This is fixed now.

Run `flutter pub uprade` to sort this issue. A simple `pub get` won't do, at the issue is a transitive dependency

**Closed by rrousselGit** 2023-10-21 16:24 UTC
Labels: bug, needs triage
