### ISSUE TITLE
Generator generated AutoDisposeProvider<dynamic> instead of AutoDisposeProvider<NotDynamicClass>

### ISSUE THREAD

**Issue by aedify-swi** [rrousselGit/riverpod#2754] opened 2023-07-20 12:02 UTC
**Describe the bug**
I am using a package called [i18n](https://pub.dev/packages/i18n) to generate translation data classes. I wrote a small provider to return the correct class depending on the currently selected language. Alas, instead of typing the provider value as `Messages` code generation types it as `dynamic`. 

**To Reproduce**
Input:
```dart
@riverpod
Messages translation(final TranslationRef ref) {
  final locale = ref.watch(localeControllerProvider);
  return switch (locale) {
    Locale(languageCode: "es", countryCode: "ES") => const MessagesEs(),
    _ => const Messages(),
  };
}
```
Results in:
```dart
part of 'translation_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$translationHash() => r'95800625233caf0b2b8bc83432b494c8bc9553da';

/// See also [translation].
@ProviderFor(translation)
final translationProvider = AutoDisposeProvider<dynamic>.internal(
  translation,
  name: r'translationProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$translationHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef TranslationRef = AutoDisposeProviderRef<dynamic>;
```
For reference the Messages class from `messages.i18n.dart`:
```dart
class Messages {
  const Messages();
  String get locale => "en";
  String get languageCode => "en";
  SubMessages get sub => SubMessages(this);
}

class SubMessages {
  final Messages _parent;
  const SubMessages(this._parent);
  String get test => """Test""";
}
```

**Expected behavior**

Should look like this:
```dart
/// See also [translation].
@ProviderFor(translation)
final translationProvider = AutoDisposeProvider<Messages>.internal(
  translation,
  name: r'translationProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$translationHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef TranslationRef = AutoDisposeProviderRef<Messages>;
```

**Comment by rrousselGit** [comment] 2023-07-20 12:18
That's a known issue with most code generators.

Closing as duplicate of https://github.com/rrousselGit/riverpod/issues/2298 / https://github.com/rrousselGit/riverpod/issues/1782

**Closed by rrousselGit** 2023-07-20 12:18 UTC
Labels: bug, needs triage
