### ISSUE TITLE
When using Gorouter for navigation, the state of Riverpod does not get updated.

### ISSUE THREAD

**Issue by kulame** [rrousselGit/riverpod#3082] opened 2023-11-01 10:01 UTC
**Describe the bug**
my provider code 
```dart 
@riverpod
class SelectTask extends _$SelectTask {
  @override
  Task? build() {
    return null;
  }

  setTask(Task task) {
    state = task.copyWith();
  }
}
```

my set action 
```dart
                onPressed: () {
                  ref.read(selectTaskProvider.notifier).setTask(Task(
                      duration: duration.value, detail: detailController.text));
                  logger.d(
                      "set task successfully ${duration.value}, ${detailController.text}");
                  context.go("/startpage");
                },
```

my read page code
```
class StartScreen extends HookConsumerWidget {
  const StartScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final task = ref.watch(selectTaskProvider);
    logger.d(task);
   ....

```

when i update selectTaskProvider,

the log is set successful

I/flutter (32476): │ 🐛 {
I/flutter (32476): │ 🐛   provider: selectTaskProvider,
I/flutter (32476): │ 🐛   oldValue: null,
I/flutter (32476): │ 🐛   newValue: Task(duration: 0:10:00.000000, detail: ss)
I/flutter (32476): │ 🐛 }
I/flutter (32476): │ 🐛 

but in startpage, i also read a null value from selectTaskProvider.  Is there a problem?

**Comment by rrousselGit** [comment] 2023-11-01 10:35
I assume your provider got disposed because it isn't listened anywhere

**Comment by kulame** [comment] 2023-11-01 10:47
I don't quite understand. How can I  watch the latest state?

**Comment by kulame** [comment] 2023-11-01 11:16
i must add code    "ref.watch(selectTaskProvider)"  on NewTaskScreen.   it can updated on StartScreen.
It's a bit confusing to me. 🤔

**Comment by wph144** [comment] 2023-11-03 01:48
I have the same issue. When navigating from Screen A to Screen B and there is a class-type notifier that I want to use in Screen B, the problem is how to initialize that notifier.

The first solution is to make SelectedTask with @Riverpod(keepAlive: true). However, SelectedTask is not a state that is used globally across the app, but only within a single screen. Furthermore, I expect that this SelectedTask will often be modified within that screen. In my experience, adding keepAlive in such cases tends to increase the possibility of bugs.

Another solution I have considered is creating an additional class-type notifier for initial value.

```dart
@Riverpod(keepAlive: true)
class SelectedTaskInitialValue extends _$SelectedTaskInitialValue { 
  Task build() => ...
  void set(Task task) { state = task } 
}

@riverpod
class SelectedTask extends _$SelectedTask { 
  Task? build() => ref.watch(selectedTaskInitialValueProvider)
}

```

A more simplified version would be to create a late variable for the initial value like this:
```dart
late Task selectedTaskInitialValue;

@riverpod
class SelectedTask extends _$SelectedTask { 
  Task? build() => selectedTaskInitialValue
}
```

I have chosen the last solution.
Discussions, opinions, and critiques are welcome.

**Comment by AhmedLSayed9** [comment] 2023-11-03 02:02
```dart
extension AutoDisposeRefExtension<T> on AutoDisposeRef<T> {
  /// Keep listening to an autoDispose provider until last listener is removed.
  ///
  /// This is primarily used to initialize and preserve the state of the provider
  /// when navigating to a route until that route is popped off.
  void keepAliveUntilNoListeners() {
    keepAlive();
    onCancel(invalidateSelf);
  }
}

@riverpod
class SelectTask extends _$SelectTask {
  @override
  Task? build() {
    ref.keepAliveUntilNoListeners();
    return null;
  }

  setTask(Task task) {
    state = task.copyWith();
  }
}
```

**Comment by wph144** [comment] 2023-11-03 03:18
> ```dart
> extension AutoDisposeRefExtension<T> on AutoDisposeRef<T> {
>   /// Keep listening to an autoDispose provider until last listener is removed.
>   ///
>   /// This is primarily used to initialize and preserve the state of the provider
>   /// when navigating to a route until that route is popped off.
>   void keepAliveUntilNoListeners() {
>     keepAlive();
>     onCancel(invalidateSelf);
>   }
> }
> 
> @riverpod
> class SelectTask extends _$SelectTask {
>   @override
>   Task? build() {
>     ref.keepAliveUntilNoListeners();
>     return null;
>   }
> 
>   setTask(Task task) {
>     state = task.copyWith();
>   }
> }
> ```
> 
> This will mark your provider as a keep-Alive but will also auto-dispose it when you leave Screen-B

It is cool

**Comment by wujek-srujek** [comment] 2023-12-09 23:43
This is pretty useful, thanks, it will let me get rid of my very own dirty workaround.

However, I still consider this a workaround for the very common use case, I don't get why this is so hard and not part of Riverpod proper.

**Comment by rrousselGit** [comment] 2024-03-01 17:05
A solution was given. This is not really a bug, so closing :)

**Closed by rrousselGit** 2024-03-01 17:05 UTC
Labels: bug, needs triage
