### ISSUE TITLE
Riverpod lint is not working in Windows

### ISSUE THREAD

**Issue by Shreemanarjun** [rrousselGit/riverpod#2252] opened 2023-03-02 19:33 UTC
Riverpod lint is not working windows.

[custom_lint.log](https://github.com/rrousselGit/riverpod/files/10875196/custom_lint.log)

**Comment by Harishwarrior** [comment] 2023-03-03 04:51
I had a similar issue before. but now I am having another issue.
```
PS C:\Users\Harish\StudioProjects\apps> fvm dart run custom_lint
Plugin stateless_ref threw while analyzing C:\Users\Harish\StudioProjects\apps\lib\src\app.dart:
Unsupported operation: Unknown type Null
#0      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:156:7)
#1      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)
#2      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13695:50)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#4      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:13794:16)
#5      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1719:10)
#6      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:13788:15)
#7      TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:13083:19)
#8      RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1677:10)
#9      TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13078:15)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#11     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2596:21)
#12     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:923:10)
#13     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2589:50)
#14     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:19)
#15     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)
<asynchronous suspension>
#16     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)
<asynchronous suspension>
#17     _ClientAnalyzerPlugin._startUpLintRule (package:custom_lint_builder/src/client.dart:876:5)
<asynchronous suspension>
#18     Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#19     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:752:7)
<asynchronous suspension>
#20     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:821:14)
<asynchronous suspension>
#21     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:746:5)
```

**Comment by PGScully** [comment] 2023-03-10 01:27
I'm also having the same problem.

@Harishwarrior I get this the _second_ time I try to run the lint.  `flutter pub get` resets it somehow, and it goes back to the first problem, and then re-appears the next time you run the lint.

[custom_lint.log](https://github.com/rrousselGit/riverpod/files/10937610/custom_lint.log)

**Comment by Harishwarrior** [comment] 2023-03-10 03:19
> I'm also having the same problem.  Also, it doesn't exit, but hangs indefinitely.  Log attached.
> 
> @Harishwarrior I get this the _second_ time I try to run the lint.  `flutter pub get` resets it somehow, and it goes back to the first problem, and then re-appears the next time you run the lint.
> 
> [custom_lint.log](https://github.com/rrousselGit/riverpod/files/10937610/custom_lint.log)
> 

The problem somehow disappeared for me entirely 😅.

**Comment by rrousselGit** [comment] 2023-03-10 11:13
@Harishwarrior Some of your dependencies are out of date I think.

**Comment by Harishwarrior** [comment] 2023-03-10 12:46
> @Harishwarrior Some of your dependencies are out of date I think.

It's quite opposite actually 😅. It was working fine before I ran flutter pub upgrade. I'll debug and share the log here soon.

**Comment by Harishwarrior** [comment] 2023-03-10 12:58
[custom_lint.log](https://github.com/rrousselGit/riverpod/files/10942211/custom_lint.log)

Log file attached. 

Dependency tree:

```
Dart SDK 2.19.4
Flutter SDK 3.7.7
team 1.0.0+1
├── build_runner 2.3.3
│   ├── analyzer 5.7.1
│   │   ├── _fe_analyzer_shared 55.0.0
│   │   │   └── meta...
│   │   ├── collection...
│   │   ├── convert 3.1.1
│   │   │   └── typed_data...
│   │   ├── crypto...
│   │   ├── glob...
│   │   ├── meta...
│   │   ├── package_config...
│   │   ├── path...
│   │   ├── pub_semver...
│   │   ├── source_span...
│   │   ├── watcher...
│   │   └── yaml...
│   ├── args 2.4.0
│   ├── async 2.10.0
│   │   ├── collection...
│   │   └── meta...
│   ├── build 2.3.1
│   │   ├── analyzer...
│   │   ├── async...
│   │   ├── convert...
│   │   ├── crypto...
│   │   ├── glob...
│   │   ├── logging...
│   │   ├── meta...
│   │   └── path...
│   ├── build_config 1.1.1
│   │   ├── checked_yaml 2.0.2
│   │   │   ├── json_annotation...
│   │   │   ├── source_span...
│   │   │   └── yaml...
│   │   ├── json_annotation...
│   │   ├── path...
│   │   ├── pubspec_parse...
│   │   └── yaml...
│   ├── build_daemon 3.1.1
│   │   ├── built_collection 5.1.1
│   │   ├── built_value 8.4.4
│   │   │   ├── built_collection...
│   │   │   ├── collection...
│   │   │   ├── fixnum 1.1.0
│   │   │   └── meta...
│   │   ├── http_multi_server...
│   │   ├── logging...
│   │   ├── path...
│   │   ├── pool...
│   │   ├── shelf...
│   │   ├── shelf_web_socket...
│   │   ├── stream_transform...
│   │   ├── watcher...
│   │   └── web_socket_channel...
│   ├── build_resolvers 2.2.0
│   │   ├── analyzer...
│   │   ├── async...
│   │   ├── build...
│   │   ├── collection...
│   │   ├── crypto...
│   │   ├── graphs...
│   │   ├── logging...
│   │   ├── package_config...
│   │   ├── path...
│   │   ├── pool...
│   │   ├── pub_semver...
│   │   ├── stream_transform...
│   │   └── yaml...
│   ├── build_runner_core 7.2.7
│   │   ├── async...
│   │   ├── build...
│   │   ├── build_config...
│   │   ├── build_resolvers...
│   │   ├── collection...
│   │   ├── convert...
│   │   ├── crypto...
│   │   ├── glob...
│   │   ├── graphs...
│   │   ├── json_annotation...
│   │   ├── logging...
│   │   ├── meta...
│   │   ├── package_config...
│   │   ├── path...
│   │   ├── pool...
│   │   ├── timing...
│   │   ├── watcher...
│   │   └── yaml...
│   ├── code_builder 4.4.0
│   │   ├── built_collection...
│   │   ├── built_value...
│   │   ├── collection...
│   │   ├── matcher...
│   │   └── meta...
│   ├── collection...
│   ├── crypto 3.0.2
│   │   └── typed_data 1.3.1
│   │       └── collection...
│   ├── dart_style 2.2.5
│   │   ├── analyzer...
│   │   ├── args...
│   │   ├── path...
│   │   ├── pub_semver...
│   │   └── source_span...
│   ├── frontend_server_client 3.2.0
│   │   ├── async...
│   │   └── path...
│   ├── glob 2.1.1
│   │   ├── async...
│   │   ├── collection...
│   │   ├── file...
│   │   ├── path...
│   │   └── string_scanner...
│   ├── graphs 2.2.0
│   │   └── collection...
│   ├── http_multi_server 3.2.1
│   │   └── async...
│   ├── io 1.0.4
│   │   ├── meta...
│   │   ├── path...
│   │   └── string_scanner...
│   ├── js...
│   ├── logging...
│   ├── meta...
│   ├── mime 1.0.4
│   ├── package_config 2.1.0
│   │   └── path...
│   ├── path...
│   ├── pool 1.5.1
│   │   ├── async...
│   │   └── stack_trace...
│   ├── pub_semver 2.1.3
│   │   ├── collection...
│   │   └── meta...
│   ├── pubspec_parse 1.2.2
│   │   ├── checked_yaml...
│   │   ├── collection...
│   │   ├── json_annotation...
│   │   ├── pub_semver...
│   │   └── yaml...
│   ├── shelf 1.4.0
│   │   ├── async...
│   │   ├── collection...
│   │   ├── http_parser 4.0.2
│   │   │   ├── collection...
│   │   │   ├── source_span...
│   │   │   ├── string_scanner...
│   │   │   └── typed_data...
│   │   ├── path...
│   │   ├── stack_trace...
│   │   └── stream_channel...
│   ├── shelf_web_socket 1.0.3
│   │   ├── shelf...
│   │   ├── stream_channel...
│   │   └── web_socket_channel...
│   ├── stack_trace 1.11.0
│   │   └── path...
│   ├── stream_transform 2.1.0
│   ├── timing 1.0.1
│   │   └── json_annotation...
│   ├── watcher 1.0.2
│   │   ├── async...
│   │   └── path...
│   ├── web_socket_channel 2.3.0
│   │   ├── async...
│   │   ├── crypto...
│   │   └── stream_channel...
│   └── yaml 3.1.1
│       ├── collection...
│       ├── source_span...
│       └── string_scanner...
├── connectivity_plus 3.0.3
│   ├── connectivity_plus_platform_interface 1.2.4
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── plugin_platform_interface 2.1.4
│   │       └── meta...
│   ├── flutter...
│   ├── flutter_web_plugins 0.0.0
│   │   ├── characters...
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── js...
│   │   ├── material_color_utilities...
│   │   ├── meta...
│   │   └── vector_math...
│   ├── js 0.6.5
│   │   └── meta...
│   ├── meta 1.8.0
│   └── nm 0.5.0
│       └── dbus 0.7.8
│           ├── args...
│           ├── ffi...
│           ├── meta...
│           └── xml...
├── cupertino_icons 1.0.5
├── custom_lint 0.3.2
│   ├── analyzer...
│   ├── analyzer_plugin 0.11.2
│   │   ├── analyzer...
│   │   ├── collection...
│   │   ├── dart_style...
│   │   ├── pub_semver...
│   │   └── yaml...
│   ├── args...
│   ├── async...
│   ├── cli_util 0.3.5
│   │   ├── meta...
│   │   └── path...
│   ├── freezed_annotation 2.2.0
│   │   ├── collection...
│   │   ├── json_annotation...
│   │   └── meta...
│   ├── json_annotation 4.8.0
│   │   └── meta...
│   ├── meta...
│   ├── package_config...
│   ├── path...
│   ├── pub_semver...
│   ├── pubspec_parse...
│   ├── riverpod...
│   ├── rxdart 0.27.7
│   └── uuid 3.0.7
│       └── crypto...
├── firebase_core 2.7.1
│   ├── firebase_core_platform_interface 4.5.3
│   │   ├── collection...
│   │   ├── flutter...
│   │   ├── flutter_test...
│   │   ├── meta...
│   │   └── plugin_platform_interface...
│   ├── firebase_core_web 2.2.2
│   │   ├── firebase_core_platform_interface...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── js...
│   │   └── meta...
│   ├── flutter...
│   └── meta...
├── firebase_performance 0.9.0+15
│   ├── firebase_core...
│   ├── firebase_core_platform_interface...
│   ├── firebase_performance_platform_interface 0.1.1+34
│   │   ├── _flutterfire_internals 1.0.17
│   │   │   ├── collection...
│   │   │   ├── firebase_core...
│   │   │   ├── firebase_core_platform_interface...
│   │   │   ├── flutter...
│   │   │   └── meta...
│   │   ├── firebase_core...
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── firebase_performance_web 0.1.1+23
│   │   ├── _flutterfire_internals...
│   │   ├── firebase_core...
│   │   ├── firebase_core_web...
│   │   ├── firebase_performance_platform_interface...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── js...
│   └── flutter...
├── flutter 0.0.0
│   ├── characters 1.2.1
│   ├── collection 1.17.0
│   ├── js...
│   ├── material_color_utilities 0.2.0
│   ├── meta...
│   ├── sky_engine 0.0.99
│   └── vector_math 2.1.4
├── flutter_adaptive_scaffold 0.1.0
│   └── flutter...
├── flutter_gen_runner 5.2.0
│   ├── build...
│   ├── collection...
│   ├── crypto...
│   ├── flutter_gen_core 5.2.0
│   │   ├── analyzer...
│   │   ├── args...
│   │   ├── collection...
│   │   ├── color 3.0.0
│   │   ├── dart_style...
│   │   ├── dartx 1.1.0
│   │   │   ├── characters...
│   │   │   ├── collection...
│   │   │   ├── crypto...
│   │   │   ├── meta...
│   │   │   ├── path...
│   │   │   └── time 2.1.3
│   │   │       └── clock...
│   │   ├── glob...
│   │   ├── json_annotation...
│   │   ├── mime...
│   │   ├── path...
│   │   ├── pub_semver...
│   │   ├── source_span...
│   │   ├── xml...
│   │   └── yaml...
│   ├── glob...
│   └── path...
├── flutter_local_notifications 13.0.0
│   ├── clock 1.1.1
│   ├── flutter...
│   ├── flutter_local_notifications_linux 3.0.0+1
│   │   ├── dbus...
│   │   ├── ffi 2.0.1
│   │   ├── flutter...
│   │   ├── flutter_local_notifications_platform_interface...
│   │   ├── path...
│   │   └── xdg_directories 0.2.0+3
│   │       ├── meta...
│   │       ├── path...
│   │       └── process 4.2.4
│   │           ├── file...
│   │           ├── path...
│   │           └── platform...
│   ├── flutter_local_notifications_platform_interface 6.0.0
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   └── timezone 0.9.1
│       └── path...
├── flutter_localizations 0.0.0
│   ├── characters...
│   ├── clock...
│   ├── collection...
│   ├── flutter...
│   ├── intl...
│   ├── js...
│   ├── material_color_utilities...
│   ├── meta...
│   ├── path 1.8.2
│   └── vector_math...
├── flutter_riverpod 2.3.1
│   ├── collection...
│   ├── flutter...
│   ├── meta...
│   ├── riverpod 2.3.1
│   │   ├── collection...
│   │   ├── meta...
│   │   ├── stack_trace...
│   │   └── state_notifier...
│   └── state_notifier 0.7.2+1
│       └── meta...
├── flutter_svg 2.0.3
│   ├── flutter...
│   ├── vector_graphics 1.1.3
│   │   ├── flutter...
│   │   └── vector_graphics_codec...
│   ├── vector_graphics_codec 1.1.3
│   └── vector_graphics_compiler 1.1.3
│       ├── args...
│       ├── meta...
│       ├── path_parsing 1.0.1
│       │   ├── meta...
│       │   └── vector_math...
│       ├── vector_graphics_codec...
│       └── xml 6.2.2
│           ├── collection...
│           ├── meta...
│           └── petitparser 5.1.0
│               └── meta...
├── flutter_test 0.0.0
│   ├── async...
│   ├── boolean_selector 2.1.1
│   │   ├── source_span...
│   │   └── string_scanner...
│   ├── characters...
│   ├── clock...
│   ├── collection...
│   ├── fake_async 1.3.1
│   │   ├── clock...
│   │   └── collection...
│   ├── flutter...
│   ├── js...
│   ├── matcher 0.12.13
│   │   ├── meta...
│   │   └── stack_trace...
│   ├── material_color_utilities...
│   ├── meta...
│   ├── path...
│   ├── source_span 1.9.1
│   │   ├── collection...
│   │   ├── path...
│   │   └── term_glyph...
│   ├── stack_trace...
│   ├── stream_channel 2.1.1
│   │   └── async...
│   ├── string_scanner 1.2.0
│   │   └── source_span...
│   ├── term_glyph 1.2.1
│   ├── test_api 0.4.16
│   │   ├── async...
│   │   ├── boolean_selector...
│   │   ├── collection...
│   │   ├── matcher...
│   │   ├── meta...
│   │   ├── source_span...
│   │   ├── stack_trace...
│   │   ├── stream_channel...
│   │   ├── string_scanner...
│   │   └── term_glyph...
│   └── vector_math...
├── go_router 6.2.0
│   ├── collection...
│   ├── flutter...
│   ├── flutter_web_plugins...
│   ├── logging 1.1.1
│   └── meta...
├── intl 0.17.0
│   ├── clock...
│   └── path...
├── riverpod_annotation 2.0.1
│   ├── meta...
│   └── riverpod...
├── riverpod_generator 2.1.2
│   ├── analyzer...
│   ├── build...
│   ├── build_config...
│   ├── collection...
│   ├── crypto...
│   ├── meta...
│   ├── path...
│   ├── riverpod_analyzer_utils 0.1.3
│   │   ├── analyzer...
│   │   ├── collection...
│   │   ├── crypto...
│   │   ├── custom_lint_core 0.3.2
│   │   │   ├── analyzer...
│   │   │   ├── analyzer_plugin...
│   │   │   ├── collection...
│   │   │   ├── custom_lint...
│   │   │   ├── matcher...
│   │   │   ├── meta...
│   │   │   ├── path...
│   │   │   ├── source_span...
│   │   │   └── yaml...
│   │   ├── freezed_annotation...
│   │   ├── meta...
│   │   ├── path...
│   │   └── source_span...
│   ├── riverpod_annotation...
│   └── source_gen 1.2.7
│       ├── analyzer...
│       ├── async...
│       ├── build...
│       ├── dart_style...
│       ├── glob...
│       ├── path...
│       ├── source_span...
│       └── yaml...
├── riverpod_lint 1.1.4
│   ├── analyzer...
│   ├── analyzer_plugin...
│   ├── collection...
│   ├── custom_lint_builder 0.3.2
│   │   ├── analyzer...
│   │   ├── analyzer_plugin...
│   │   ├── collection...
│   │   ├── custom_lint...
│   │   ├── custom_lint_core...
│   │   ├── glob...
│   │   ├── hotreloader 3.0.5
│   │   │   ├── collection...
│   │   │   ├── logging...
│   │   │   ├── path...
│   │   │   ├── stream_transform...
│   │   │   ├── vm_service 9.4.0
│   │   │   └── watcher...
│   │   ├── meta...
│   │   ├── path...
│   │   ├── pubspec_parse...
│   │   └── rxdart...
│   ├── meta...
│   ├── path...
│   ├── riverpod...
│   ├── riverpod_analyzer_utils...
│   ├── source_span...
│   └── yaml...
├── shared_preferences 2.0.18
│   ├── flutter...
│   ├── shared_preferences_android 2.0.17
│   │   ├── flutter...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_foundation 2.1.5
│   │   ├── flutter...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_linux 2.1.5
│   │   ├── file 6.1.4
│   │   │   ├── meta...
│   │   │   └── path...
│   │   ├── flutter...
│   │   ├── path...
│   │   ├── path_provider_linux 2.1.10
│   │   │   ├── ffi...
│   │   │   ├── flutter...
│   │   │   ├── path...
│   │   │   ├── path_provider_platform_interface...
│   │   │   └── xdg_directories...
│   │   ├── path_provider_platform_interface 2.0.6
│   │   │   ├── flutter...
│   │   │   ├── platform 3.1.0
│   │   │   └── plugin_platform_interface...
│   │   └── shared_preferences_platform_interface...
│   ├── shared_preferences_platform_interface 2.1.1
│   │   ├── flutter...
│   │   └── plugin_platform_interface...
│   ├── shared_preferences_web 2.0.6
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   └── shared_preferences_platform_interface...
│   └── shared_preferences_windows 2.1.5
│       ├── file...
│       ├── flutter...
│       ├── path...
│       ├── path_provider_platform_interface...
│       ├── path_provider_windows 2.1.5
│       │   ├── ffi...
│       │   ├── flutter...
│       │   ├── path...
│       │   ├── path_provider_platform_interface...
│       │   └── win32 3.1.3
│       │       └── ffi...
│       └── shared_preferences_platform_interface...
├── team_icons 0.0.4
│   └── flutter...
├── team_ui_kit 0.0.2
│   ├── flutter...
│   └── vector_math...
└── very_good_analysis 4.0.0+1
```

**Comment by rrousselGit** [comment] 2023-03-10 14:10
@Harishwarrior Please make a reproducible example for this, because it works for me.  
custom_lint doesn't even pass the "watchMode" parameter to that runSocket function. So your error doesn't make sense.

In any case, your problem is unrelated to this issue. Please make a new issue :)

**Comment by rrousselGit** [comment] 2023-03-18 09:32
Closing in favour of https://github.com/invertase/dart_custom_lint/issues/115, to center all the information in one place

**Closed by rrousselGit** 2023-03-18 09:32 UTC
Labels: bug, question
