### ISSUE TITLE
Got "warning: Missing concrete implementation of 'overrideWith'." from generated file 

### ISSUE THREAD

**Issue by dokinkon** [rrousselGit/riverpod#2949] opened 2023-10-04 07:25 UTC
**Describe the bug**
When use code gen to generate notifier provider, I got such warning message from dart analysis:

warning: Missing concrete implementation of 'overrideWith'. (missing_override_of_must_be_overridden at [obank_app] lib/feature/charge/ui/order_detail_page.g.dart:168)

**To Reproduce**

```
@riverpod
class _UploadFilesNotifier extends _$UploadFilesNotifier {
  @override
  List<File> build(_AttachmentType type) {
    return [];
  }

  void addFile(File file) {
    state = List.of(state..add(file));
  }

  void removeFile(int index) {
    state = List.of(state..removeAt(index));
  }
}
```

**Expected behavior**
No warning at all.

Have no idea what this warning meaning. How can I fix this warning? thank you.

**Comment by rrousselGit** [comment] 2023-10-05 09:23
I do not have this issue. What version of riverpod/riverpod_generator are you using? It'd help if you could make a git repository to reproduce the issue

**Comment by rrousselGit** [comment] 2023-10-05 22:39
I've managed to encounter the issue. I'll see what I can do

**Comment by Mixron469** [comment] 2023-10-17 06:06
<img width="709" alt="Screenshot 2566-10-17 at 13 03 42" src="https://github.com/rrousselGit/riverpod/assets/110093186/826ff1c9-f447-4f14-84e2-c82a7dee1f2c">

I have the same issue, in many file that I create the family of the state provider

**Comment by Mixron469** [comment] 2023-10-25 08:44
> Please make a repository to reproduce the issue. As it is, everything works fine for me.
> 
> In fact, chances are you're on a lower version of the generator. This issue shouldn't be happening nowadays, as `overrideWith` is always generated in the notifier.

![image](https://github.com/rrousselGit/riverpod/assets/110093186/85b0cd6e-4303-489a-870d-4d5e424c3ea0)

Thanks a lot.

**Comment by rrousselGit** [comment] 2023-10-25 09:31
Sounds like the issue is indeed that a lower version was used.
So closing :)

**Closed by rrousselGit** 2023-10-25 09:31 UTC
Labels: bug, question
