### ISSUE TITLE
Providers Doesnt Dispose After  Navigator.of(context).pushReplacement

### ISSUE THREAD

**Issue by smurat** [rrousselGit/riverpod#1265] opened 2022-03-08 21:39 UTC
I have multiple multiple AutoDisposeFutureProvider widget tree. After some specific network response i use Navigator.of(context) .pushReplacement for return the login page. Then i logged in again but  all FutureProviders states still alive, not disposed.

How can i archive dispose all used provider in widget tree with after use Navigator.pushReplacement. Am i doing something wrong?
Thanks for all your efforts on this awesome package after Provider

**Comment by lucavenir** [comment] 2022-03-09 13:32
Hi there,
it would help if you post a reproducible example if you're submitting a bug issue.

Anyways, if you expect your Providers to be disposed (as you say: no one listens to them anymore), but they aren't, unexpectedly, then someone is still listening to those providers. The `autoDispose` clause will dispose a provider iff no one listens to them.

More debugging tools are on their way (by reading [this](https://github.com/rrousselGit/river_pod/milestone/1)): they should help you debugging your code quicker.

**Comment by smurat** [comment] 2022-03-10 08:33
Here is the reproducible example

main.dart
```dart
import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:dio_http_formatter/dio_http_formatter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:logger/logger.dart';

void main() {
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    dio = ref.watch(networkManagerProvider).dio;

    return MaterialApp(
      title: 'Riverpod Autodispoe Bug Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Autodispoe Bug Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(MaterialPageRoute(builder: (context) => const TodoPage()));
              },
              child: const Text("Login"),
            )
          ],
        ),
      ),
    );
  }
}

class TodoPage extends ConsumerStatefulWidget {
  const TodoPage({Key? key}) : super(key: key);

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _TodoPageState();
}

class _TodoPageState extends ConsumerState<TodoPage> {
  @override
  Widget build(BuildContext context) {
    final todoListFuturePr = ref.watch(todosListFutureProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text("Todo List"),
      ),
      body: todoListFuturePr.when(
        data: (data) {
          return ListView.builder(
            itemBuilder: (context, index) {
              final item = data[index];
              return Padding(
                padding: const EdgeInsets.all(8.0),
                child: Card(
                  child: InkWell(
                    onTap: () {
                      Navigator.of(context)
                          .push(MaterialPageRoute(builder: (context) => ItemDetailsPage(item.id.toString())));
                    },
                    child: ListTile(
                      title: Text(item.title ?? '-'),
                      subtitle: Text(item.id?.toString() ?? '-'),
                    ),
                  ),
                ),
              );
            },
          );
        },
        error: (error, stackTrace) => Center(
          child: Text("$error"),
        ),
        loading: () => const Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
}

class ItemDetailsPage extends ConsumerStatefulWidget {
  final String id;
  const ItemDetailsPage(this.id, {Key? key}) : super(key: key);

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _ItemDetailsPageState();
}

class _ItemDetailsPageState extends ConsumerState<ItemDetailsPage> {
  @override
  Widget build(BuildContext context) {
    final todoItemFuturePr = ref.watch(todosItemFutureProvider(widget.id));

    return Scaffold(
        appBar: AppBar(
          title: const Text("Item Details"),
        ),
        body: Center(
          child: todoItemFuturePr.when(
            data: (data) {
              return Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  OutlinedButton(
                      onPressed: () {
                        Navigator.of(context).push(MaterialPageRoute(
                          builder: (context) => const MyHomePage(title: "Login"),
                        ));
                      },
                      child: const Text("Go to LoginPage with pushreplacement")),
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Card(
                      child: ListTile(
                        title: Text(data.title ?? '-'),
                        subtitle: Text(data.id?.toString() ?? '-'),
                      ),
                    ),
                  ),
                ],
              );
            },
            error: (error, stackTrace) => Center(
              child: Text("$error"),
            ),
            loading: () => const Center(
              child: CircularProgressIndicator(),
            ),
          ),
        ));
  }
}

final networkManagerProvider = Provider<NetworkManager>((ref) {
  return NetworkManager();
});

late Dio dio;

class NetworkManager {
  Dio dio = Dio();

  NetworkManager() {
    initDio();
  }

  initDio() {
    dio.options.sendTimeout = 8000; //8s
    dio.options.receiveTimeout = 8000; //8s
    dio.options.contentType = 'application/json';
    dio.interceptors.addAll([
      HttpFormatter(),
    ]);

    logger.i("Dio initialized");
  }
}

final todosListFutureProvider = FutureProvider.autoDispose<List<Todo>>((ref) async {
  try {
    final response = await dio.get("https://jsonplaceholder.typicode.com/todos",
        options: Options(responseType: ResponseType.plain));
    final todoList = todosListFromJson(response.data);
    ref.onDispose(() {
      logger.i("todosListFutureProvider disposed");
    });
    return todoList;
  } catch (e, s) {
    return Future.error(e, s);
  }
});

final todosItemFutureProvider = FutureProvider.autoDispose.family<Todo, String>((ref, id) async {
  try {
    final response = await dio.get("https://jsonplaceholder.typicode.com/todos/$id",
        options: Options(responseType: ResponseType.plain));
    final todoItem = Todo.fromJson(jsonDecode(response.data));
    ref.onDispose(() {
      logger.i("todosItemFutureProvider disposed");
    });
    return todoItem;
  } catch (e, s) {
    return Future.error(e, s);
  }
});

var logger = Logger();

List<Todo> todosListFromJson(String str) => List<Todo>.from(json.decode(str).map((e) => Todo.fromJson(e)));

class Todo {
  int? userId;
  int? id;
  String? title;
  bool? completed;

  Todo({this.userId, this.id, this.title, this.completed});

  Todo.fromJson(Map<String, dynamic> json) {
    userId = json['userId'];
    id = json['id'];
    title = json['title'];
    completed = json['completed'];
  }
}
```

pubspec.yaml
```yaml
name: riverpod_dispose_bug
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_riverpod: ^1.0.3
  dio_http_formatter: ^2.1.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter          
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
```

**Comment by lucavenir** [comment] 2022-03-10 10:05
Hi there,

As expected, I don't think Riverpod is bugged. Riverpod is behaving as expected.
On the "Go to LoginPage with Pushreplacement" button's `onPressed` event, you're just pushing a route.

This implies that:
1. The widget tree up until that point isn't disposed, since you're _not_ using a `pushReplacement`, but instead just a `push: this causes a new route to be added on top of everything else, meaning you're not disposing anything, and therefore your tree is still listening to the providers you've created, and therefore they're not disposed as intended by Riverpod's documentation;
2. Even if you'd use `pushReplacement`, you're just replacing the last page you're viewing. You'd need to replace all and then push the login page. This means you'd need to `Navigator.of(context).popUntil((route) => false)` and then `Navigator.of(context).push(... your route ...)`.

Keep in mind that these kind of questions usually belong to stackoverflow.
Also, and this is just my curiosity, why are you using `dio = ref.watch(networkManagerProvider).dio`, even though that variable is global? If you wanted to use dio as a Singleton, why not just initialize it outside?

Hope this helps (note: I'm just trying to be helpful, I'm not a maintainer or anything)

**Comment by rrousselGit** [comment] 2022-04-16 10:05
Closing as this is working as expected, as explained previously 😄 

Hopefully the new devtools will help debugging this when they are available.

**Closed by rrousselGit** 2022-04-16 10:05 UTC
Labels: bug, needs triage
