### ISSUE TITLE
Riverpod doesn't understand provider's dependency gets overridden.

### ISSUE THREAD

**Issue by AlexanderFarkas** [rrousselGit/riverpod#1629] opened 2022-09-13 11:50 UTC
**Describe the bug**
This test fails.

**Test**
```dart

class Counter {
  Counter(this.count);

  final int count;
}

void main() {
  final provider1 = Provider((_) => Counter(1));
  final provider2 =
      Provider((ref) => Counter(ref.watch(provider1).count + 1), dependencies: [provider1]);
  final provider3 =
      Provider((ref) => Counter(ref.watch(provider2).count + 1), dependencies: [provider2]);

  final root = ProviderContainer();
  final child1 = ProviderContainer(parent: root);
  final child2 = ProviderContainer(parent: child1, overrides: [provider2, provider3]);
  final child3 = ProviderContainer(parent: child2, overrides: [provider1]);

  test("description", () {
    child3.read(provider3);
    expect(child3.getAllProviderElements().length, equals(3));
    expect(child2.getAllProviderElements().length, equals(0));
    expect(child1.getAllProviderElements().length, equals(0));
    expect(root.getAllProviderElements().length, equals(0));
  });
}

```

Error:
'package:riverpod/src/framework/container.dart': Failed assertion: line 482 pos 17: 'targetElement.provider != targetElement.origin ||
                    dependencyElement ==
                        targetElement.container
                            .readProviderElement<Object?>(dependency)': Tried to read Provider<Counter>#f0056 from a place where one of its dependencies were overridden but the provider is not.

To fix this error, you can add add "dependencies" to Provider<Counter>#f0056 such that we have:

```
final a = Provider(...);
final b = Provider((ref) => ref.watch(a), dependencies: [a]);
```

**Comment by AlexanderFarkas** [comment] 2022-09-13 11:55
If child2 is defined like that: `final child2 = ProviderContainer(parent: child1);`, test passes.

**Comment by AlexanderFarkas** [comment] 2022-09-13 11:59
Also, this test fails (but without error - only failed `expect`), though it should pass.

```dart

class Counter {
  Counter(this.count);

  final int count;
}

void main() {
  final provider1 = Provider((_) => Counter(1));
  final provider2 =
      Provider((ref) => Counter(ref.watch(provider1).count + 1), dependencies: [provider1]);
  final provider3 =
      Provider((ref) => Counter(ref.watch(provider2).count + 1), dependencies: [provider2]);

  final root = ProviderContainer();
  final child1 = ProviderContainer(parent: root);
  final child2 = ProviderContainer(parent: child1, overrides: [provider2]);
  final child3 = ProviderContainer(parent: child2, overrides: [provider1]);

  test("description", () {
    child3.read(provider3);
    expect(child3.getAllProviderElements().length, equals(3));
    expect(child2.getAllProviderElements().length, equals(0));
    expect(child1.getAllProviderElements().length, equals(0));
    expect(root.getAllProviderElements().length, equals(0));
  });
}

```

**Comment by AlexanderFarkas** [comment] 2022-09-13 12:12
I believe problem is that riverpod doesn't traverse all transtitive dependencies for each provider in nested `watch`/`read`. It only calls `_allTransitiveDependencies` once - for provider you call with `container.read`

**Comment by rrousselGit** [comment] 2022-09-18 17:38
Thanks for the report and the nice examples to reproduce the issue.

**Comment by rrousselGit** [comment] 2022-10-28 17:33
So apparently when implementing `dependencies`, this behavior was done on purpose. I have some tests that explicitly verify this behavior

My guess is that my thought process was: This behavior is useful for testing scoped providers.  
Because otherwise, it's very difficult to mock automatically scoped providers.    
Also, thinking about it, it's a bit unusual to mix and match automatic override through `depenencies` vs manual overrides. I can't immediately think of a reason to do so besides testing.


Could you maybe describe how your use-case? I'm happy to change this if useful. But I'd like to know more about it to know whether it's truly an improvement.

**Comment by AlexanderFarkas** [comment] 2022-11-07 16:02
No real use case actually. I was just specing behaviour of my own DI package and validated some usages against yours.

**Comment by rrousselGit** [comment] 2022-11-07 20:45
I see. I'll close this then. Unless there's a real use-case, I don't see a reason to revisitate this behavior.

**Closed by rrousselGit** 2022-11-07 20:45 UTC
Labels: bug, enhancement, question
