### ISSUE TITLE
[riverpod_lint] `provider_dependencies` false positive

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/riverpod#3085] opened 2023-11-01 20:27 UTC
**Describe the bug**
![image](https://github.com/rrousselGit/riverpod/assets/30291302/f24d156e-0ba5-4998-b6f3-c1a849479524)

As you can see, it triggers `provider_dependencies` (the quick fix is to *remove* dependencies) when it shouldn't

notice: Opening the source and .g files of the depended-on providers fixes this.

This is sometimes accompanied by the lint for depending on non-generated providers (when the provider in question is in fact generated)

**To Reproduce**

No clue to be honest. Needs triage.

It feels to me like the linter just isn't getting everything it should be. Could this be a bug in `custom_lint` instead?

**Expected behavior**
`provider_dependencies` shouldn't trigger at all.

**Comment by rrousselGit** [comment] 2023-11-01 21:52
I'd need to see the other two providers to know. It could be normal

You should only specify providers which are themselves specifying `dependencies`

**Comment by TekExplorer** [comment] 2023-11-01 22:22
They are specifying `dependencies`

```dart
// considering converting these two into a family parameter in all watchers
@Riverpod(keepAlive: true, dependencies: [])
String? maybeServerId(MaybeServerIdRef ref) => null;
@Riverpod(keepAlive: true, dependencies: [maybeServerId])
String serverId(ServerIdRef ref) {
  final maybeServerId = ref.watch(maybeServerIdProvider);
  if (maybeServerId != null) return maybeServerId;

  throw StateError(
    'serverIdProvider was not overridden!'
    ' Make sure you are scoping the correct BuildContext!',
  );
}
//
@Riverpod(dependencies: [pterodactylRepository])
PteroClient pterodactylClient(PterodactylClientRef ref) {
  final repo = ref.watch(pterodactylRepositoryProvider);
  return repo.client;
}
@Riverpod(dependencies: [authData, ProfileNotifier, localPterodactylRepository])
PterodactylRepository pterodactylRepository(PterodactylRepositoryRef ref) {...}
// etc etc.
```

**Comment by catalunha** [comment] 2023-11-01 22:28
Enjoying the theme.
I still don't understand the use of dependencies in Riverpod.
What is it for?
When to use?
When not to use?
In the documentation I still haven't found enough content to form this concept.

**Comment by TekExplorer** [comment] 2023-11-01 22:36
This isn't the place to ask.

Right now i have it specified everywhere because i override serverId in the route that uses it

realistically serverId should be a family parameter and i should prop-drill the value

**Comment by catalunha** [comment] 2023-11-01 22:41
> This isn't the place to ask.

I'm sure this is not the place for questions. I just took the opportunity to highlight that some are unaware of its applications. Maybe Remi or another colleague I can build documentation. Success in resolving your issue.

**Comment by rrousselGit** [comment] 2023-11-01 23:06
@TekExplorer In that case it may be because the analysis was out of date somehow.

Not sure what exactly is the issue as is. But that's more of a custom_lint issue for sure

**Comment by TekExplorer** [comment] 2023-11-06 03:06
I think it shows up more when I use build_runner watch. Maybe that has something to do with it? Those periods where stuff doesnt exist confuses it maybe?

**Comment by rrousselGit** [comment] 2023-11-20 21:18
A reliable way to reproduce the issue appears to be:
- delete the generated files
- open a file with a provider using `depencies: [...]`
- run the generator

The lints will not update when the generated file appears

**Comment by rrousselGit** [comment] 2023-11-21 10:52
My understanding is that this is an SDK issue. I've opened https://github.com/dart-lang/sdk/issues/54113

**Comment by rrousselGit** [comment] 2023-11-21 17:21
This is pretty much confirmed to be a Dart bug at this point, so closing as there's nothing I can do

As a workaround, you can tap on `alt` and hover a type in your IDE. This generally does the trick

**Closed by rrousselGit** 2023-11-21 17:21 UTC
Labels: bug, linter, dart-bug
