### ISSUE TITLE
line != 'asynchronous gap' thrown when read provider with a dependency inside Notifier build.

### ISSUE THREAD

**Issue by eli1stark** [rrousselGit/riverpod#2780] opened 2023-07-29 22:10 UTC
**Describe the bug**
When I read provider inside the build of Notifier, and this provider has dependency on other provider and other provider is overridden in the local ProviderScope, the error below is thrown.

<details><summary>Error</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder:
Got a stack frame from package:stack_trace, where a vm or web frame was expected. This can happen if FlutterError.demangleStackTrace was not set in an environment that propagates non-standard stack traces to the framework, such as during tests.
'package:flutter/src/foundation/stack_frame.dart':
stack_frame.dart:1
Failed assertion: line 180 pos 7: 'line != '===== asynchronous gap ===========================''


The relevant error-causing widget was
UncontrolledProviderScope
framework.dart:250
When the exception was thrown, this was the stack
#2      StackFrame.fromStackTraceLine
stack_frame.dart:180
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:393:20)
#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:871:20)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:47:28)
#8      Iterable.toList (dart:core/iterable.dart:494:7)
#9      StackFrame.fromStackString
stack_frame.dart:82
#10     FlutterError.defaultStackFilter
assertions.dart:1075
#11     DiagnosticsStackTrace._applyStackFilter
assertions.dart:1269
#12     new DiagnosticsStackTrace
assertions.dart:1245
#13     FlutterErrorDetails.debugFillProperties
assertions.dart:732
#14     DiagnosticableNode.builder.<anonymous closure>
diagnostics.dart:2891
#15     DiagnosticableNode.builder
diagnostics.dart:2894
#16     _FlutterErrorDetailsNode.builder
assertions.dart:1290
#17     DiagnosticableNode.emptyBodyDescription
diagnostics.dart:2905
#18     DiagnosticsNode.toJsonMap.<anonymous closure>
diagnostics.dart:1621
#19     DiagnosticsNode.toJsonMap
diagnostics.dart:1650
#20     WidgetInspectorService._nodeToJson
widget_inspector.dart:1652
#21     WidgetInspectorService._reportStructuredError
widget_inspector.dart:929
#22     FlutterError.reportError
assertions.dart:1185
#23     _reportException
framework.dart:6628
#24     ComponentElement.performRebuild
framework.dart:5095
#25     StatefulElement.performRebuild
framework.dart:5251
#26     Element.rebuild
framework.dart:4805
#27     ComponentElement._firstBuild
framework.dart:5068
#28     StatefulElement._firstBuild
framework.dart:5242
#29     ComponentElement.mount
framework.dart:5062
...     Normal element mounting (24 frames)
#53     Element.inflateWidget
framework.dart:3971
#54     MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#55     MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (178 frames)
#233    Element.inflateWidget
framework.dart:3971
#234    MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#235    MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (94 frames)
#329    _UncontrolledProviderScopeElement.mount
framework.dart:309
...     Normal element mounting (399 frames)
#728    _UncontrolledProviderScopeElement.mount
framework.dart:309
...     Normal element mounting (35 frames)
#763    Element.inflateWidget
framework.dart:3971
#764    Element.updateChild
framework.dart:3708
#765    RenderObjectToWidgetElement._rebuild
binding.dart:1240
#766    RenderObjectToWidgetElement.mount
binding.dart:1209
#767    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
binding.dart:1156
#768    BuildOwner.buildScope
framework.dart:2720
#769    RenderObjectToWidgetAdapter.attachToRenderTree
binding.dart:1155
#770    WidgetsBinding.attachRootWidget
binding.dart:988
#771    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
binding.dart:968
#775    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
```

</details>

**To Reproduce**

flutter: `3.10.5`
hooks_riverpod: `2.3.6`

<details><summary>Code (60 lines)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

Future<void> main() async {
  runApp(const ProviderScope(child: Root()));
}

final podA = Provider<int>(
  (ref) {
    throw UnimplementedError();
  },
);

final podB = Provider<int>(
  (ref) {
    ref.watch(podA);
    return 1;
  },
  dependencies: [podA],
);

final notipod = NotifierProvider<MyNotifier, int>(MyNotifier.new);

class MyNotifier extends Notifier<int> {
  @override
  int build() => ref.read(podB) + 1;
}

class Root extends StatelessWidget {
  const Root({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const Home(),
      builder: (context, child) {
        return ProviderScope(
          overrides: [
            podA.overrideWithValue(1),
          ],
          child: child!,
        );
      },
    );
  }
}

class Home extends ConsumerWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    print('build');
    ref.watch(podA);
    print('podA is good');
    ref.watch(podB);
    print('podB is good');
    ref.watch(notipod);
    print('notipod is good');
    return const Scaffold();
  }
}

```

</details>

**Expected behavior**

In the code example above I expect 'notipod is good' to be printed, instead it throws the error, which is weird because 'podA is good' and 'podB is good' are printed without a problem.

**Comment by rrousselGit** [comment] 2023-07-31 09:45
Duplicate of https://github.com/rrousselGit/riverpod/issues/1874

**Closed by rrousselGit** 2023-07-31 09:45 UTC
Labels: bug, needs triage

**Comment by eli1stark** [comment] 2023-07-31 15:27
@rrousselGit 

I added the code to the main:

```dart
FlutterError.demangleStackTrace = (stack) {
  if (stack is Trace) return stack.vmTrace;
  if (stack is Chain) return stack.toTrace().vmTrace;
  return stack;
};
```

But this issue was more about why `notipod` is crashing.

I have this error now, which is more clear with `demangleStackTrace` but still remains an error.

<details>
<summary>Error</summary>

```
#1527   _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#1528   ConsumerStatefulElement.watch
consumer.dart:553
#1529   Home.build
main_development.dart:74
#1530   _ConsumerState.build
consumer.dart:479
#1531   StatefulElement.build
framework.dart:5198
#1532   ConsumerStatefulElement.build
consumer.dart:542
#1533   ComponentElement.performRebuild
framework.dart:5086
#1534   StatefulElement.performRebuild
framework.dart:5251
#1535   Element.rebuild
framework.dart:4805
#1536   ComponentElement._firstBuild
framework.dart:5068
#1537   StatefulElement._firstBuild
framework.dart:5242
#1538   ComponentElement.mount
framework.dart:5062
...     Normal element mounting (24 frames)
#1562   Element.inflateWidget
framework.dart:3971
#1563   MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#1564   MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (178 frames)
#1742   Element.inflateWidget
framework.dart:3971
#1743   MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#1744   MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (94 frames)
#1838   _UncontrolledProviderScopeElement.mount
framework.dart:309
...     Normal element mounting (399 frames)
#2237   _UncontrolledProviderScopeElement.mount
framework.dart:309
...     Normal element mounting (35 frames)
#2272   Element.inflateWidget
framework.dart:3971
#2273   Element.updateChild
framework.dart:3708
#2274   RenderObjectToWidgetElement._rebuild
binding.dart:1240
#2275   RenderObjectToWidgetElement.mount
binding.dart:1209
#2276   RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
binding.dart:1156
#2277   BuildOwner.buildScope
framework.dart:2720
#2278   RenderObjectToWidgetAdapter.attachToRenderTree
binding.dart:1155
#2279   WidgetsBinding.attachRootWidget
binding.dart:988
#2280   WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
binding.dart:968
#2284   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
#2285   podA.<anonymous closure>
main_development.dart:26
#2286   ProviderElementBase.watch
element.dart:713
#2287   podB.<anonymous closure>
main_development.dart:32
#2288   ProviderElementBase.read
element.dart:690
#2289   MyNotifier.build
main_development.dart:42
#2290   ProviderContainer.listen
container.dart:285
#2291   ConsumerStatefulElement.watch.<anonymous closure>
consumer.dart:560
#2292   _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#2293   ConsumerStatefulElement.watch
consumer.dart:553
#2294   Home.build
main_development.dart:74
#2295   _ConsumerState.build
consumer.dart:479
#2296   StatefulElement.build
framework.dart:5198
#2297   ConsumerStatefulElement.build
consumer.dart:542
#2298   ComponentElement.performRebuild
framework.dart:5086
#2299   StatefulElement.performRebuild
framework.dart:5251
#2300   Element.rebuild
framework.dart:4805
#2301   ComponentElement._firstBuild
framework.dart:5068
#2302   StatefulElement._firstBuild
framework.dart:5242
#2303   ComponentElement.mount
framework.dart:5062
...     Normal element mounting (24 frames)
#2327   Element.inflateWidget
framework.dart:3971
#2328   MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#2329   MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (178 frames)
#2507   Element.inflateWidget
framework.dart:3971
#2508   MultiChildRenderObjectElement.inflateWidget
framework.dart:6570
#2509   MultiChildRenderObjectElement.mount
framework.dart:6582
...     Normal element mounting (94 frames)
#2603   _UncontrolledProviderScopeElement.mount
framework.dart:309
...     Normal element mounting (399 frames)
#3002   _UncontrolledProviderScopeElement.mount
framework.dart:309
...     Normal element mounting (35 frames)
#3037   Element.inflateWidget
framework.dart:3971
#3038   Element.updateChild
framework.dart:3708
#3039   RenderObjectToWidgetElement._rebuild
binding.dart:1240
#3040   RenderObjectToWidgetElement.mount
binding.dart:1209
#3041   RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
binding.dart:1156
#3042   BuildOwner.buildScope
framework.dart:2720
#3043   RenderObjectToWidgetAdapter.attachToRenderTree
binding.dart:1155
#3044   WidgetsBinding.attachRootWidget
binding.dart:988
#3045   WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
binding.dart:968
#3049   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 12 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
```

</details>


I think I can rephrase the issue now to: "Override with value doesn't work properly when accessed from Notifier".

**Comment by rrousselGit** [comment] 2023-07-31 15:31
Your `notipod` did not specify `dependencies` on `podB`

**Comment by eli1stark** [comment] 2023-07-31 16:02
Hmm, yes, that works, thank you.

But if I create

```dart
final podC = Provider<int>((ref) => 2);
```

And use it like so:

``` dart
class MyNotifier extends Notifier<int> {
  @override
  int build() => ref.read(podC) + 1;
}
```

`notipod` doesn't require any dependencies to work properly, why is so?

**Comment by rrousselGit** [comment] 2023-07-31 16:06
For the same reason why `podB` specifies `dependencies: [podA]`

When podA is scoped, we want also to scope all of its dependents (podB).   
That logic is recursive. Now that podB is scoped, we want also to scope all of its dependents (notipod).

The whole tree of dependents and transitive dependents relying on a scoped provider need to specify `dependencies`.

You _should_ see an assert telling you you're missing a `dependencies`. And riverpod_lint should show a warning + quick fix too (although only if you were using codegen)
